<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.3.2/select2.css'));

$this->headScript()
    //->appendFile($this->baseUrl('/js/library/twitter/bootstrap-datepicker/js/bootstrap-datepicker.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/library/twitter/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.3.2/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.3.2/select2_locale_pt-BR.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/jquery-ui-1.8.19.custom/js/jquery-ui-1.8.19.custom.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/planejamento/index/index.js'),
        'text/javascript')//->appendFile($this->baseUrl('/js/app/default/documento/edit.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();
?>
<div class="region-east">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar Objetivo Institucional</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->nomobjetivo; ?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->form->submit; ?>
                                <?php echo $this->form->reset; ?>
                                <?php echo $this->form->close; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="region-center">
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a class="btn" href="<?php echo $this->url(array(
                'module' => 'planejamento',
                'controller' => 'index',
                'action' => 'add'
            )); ?>">Cadastrar novo Objetivo Institucional</a>
        </div>
    </div>
    <?php
    /**
     * @todo remover este link (abaixo) após a criação do menu
     */
    ?>

    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>

    <div id="dialog-editar" style="display: none"></div>
    <div id="dialog-excluir" style="display: none"></div>
    <div id="dialog-detalhar" style="display: none"></div>
</div>
