<div class="row">
    <div class="portlet portlet-azul span4">
        <h3>Processo</h3>
        <div class="content">
            <?= $this->processo->nomprocesso; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span4">
        <h3>Processo Pai</h3>
        <div class="content">
            <?= $this->processo->nomprocessopai; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Diretoria</h3>
        <div class="content">
            <?= $this->processo->idsetor; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Código</h3>
        <div class="content">
            <?= $this->processo->nomcodigo; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Dono</h3>
        <div class="content">
            <?= $this->processo->iddono; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Gestor</h3>
        <div class="content">
            <?= $this->processo->idgestor; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span2">
        <h3>Executor</h3>
        <div class="content">
            <?= $this->processo->idexecutor; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Consultor</h3>
        <div class="content">
            <?= $this->processo->idconsultor; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Atualiza&ccedil;&atilde;o</h3>
        <div class="content">
            <?= $this->processo->datatualizacao; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Validade</h3>
        <div class="content">
            <?= $this->processo->numvalidade; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span8">
        <h3>Descri&ccedil;&atilde;o</h3>
        <div class="content">
            <?= $this->processo->desprocesso; ?>
        </div>
    </div>
</div>