<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.3.2/select2.css'));

$this->headScript()
    //->appendFile($this->baseUrl('/js/library/twitter/bootstrap-datepicker/js/bootstrap-datepicker.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/library/twitter/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.3.2/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.3.2/select2_locale_pt-BR.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/jquery-ui-1.8.19.custom/js/jquery-ui-1.8.19.custom.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/processo/index/index.js'),
        'text/javascript')//->appendFile($this->baseUrl('/js/app/default/documento/edit.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();
?>
<div class="row">
    <div class="portlet portlet-marron span12">
        <div class="title">Pesquisar Processo</div>
        <div class="content">
            <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <div class="row">
                    <div class="span4">
                        <?php echo $this->form->diretoria; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->nomprocesso; ?>
                    </div>
                    <div class="span2 actions-pesquisar">
                        <?php echo $this->form->submit; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php
/**
 * @todo remover este link (abaixo) após a criação do menu
 */
?>
<a class="btn"
   href="<?php echo $this->url(array('module' => 'processo', 'controller' => 'index', 'action' => 'add')); ?>">Cadastrar
    novo Processo</a>

<table id="list2"></table>
<div id="toolbar2"></div>
<div id="pager2"></div>

<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>
