<div class="row">

    <div class="portlet portlet-azul span8">
        <h3>Nome Entidade Externa</h3>
        <div class="content">
            <?php echo $this->entidadeexterna->nomentidadeexterna; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span4">
        <h3>Cadastrador</h3>
        <div class="content">
            <?php echo $this->entidadeexterna->nompessoa; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span4">
        <h3>Data de Cadastro</h3>
        <div class="content">
            <?php echo $this->dateBr($this->entidadeexterna->datcadastro); ?>
        </div>
    </div>
   



           





