<?php
$this->headLink()
        ->appendStylesheet($this->baseUrl('/css/form.css'))
        ->appendStylesheet($this->baseUrl('/css/portlet.css'))
        ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
        ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
;

$this->headScript()
        ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
//        ->appendFile($this->baseUrl('/js/app/projeto/relatorio/add.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();

//print "<PRE>";
//print_r($this->form->idmarco);
//print_r($this->semaforo);
//print_r($this->statusreport);
//exit;

?>
<div class="region-center" >
    <?php
        if(isset($this->atividadesDesatualizadas)){
            echo "<div class=\"portlet portlet-marron span12\">";
            echo "<tr><td > <font size=2 color=red> ATENÇÃO: <b> As atividades abaixo estão desatualizadas no cronograma, todas estão com data fim menor ou igual a data de <b>Hoje</b>!</b>";
            echo "<p></b> <br>Para  gerar o Relatório de Situação (Status Report), atualize o cronograma.</font>";

            foreach ($this->atividadesDesatualizadas as $ativ)	{
                echo "<li><b>". $ativ["idatividadecronograma"] . "</b> - " .  $ativ["datinicio"]  . " à <font color=red><u>" .$ativ["datfim"] . "</u></font> - ". $ativ["nomatividadecronograma"] . "<br>";
            }
             echo "</div>";
        } else {
    ?>
        <form id="<?php echo $frmAttr['id']; ?>"
              name="<?php echo $frmAttr['id']; ?>"
              action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $frmAttr['method']; ?>">
            <div class="row" style="margin-top: 20px; margin-left: 1px;">
                <div class="span3">
                    <?= $this->form->domstatusprojeto; ?>
                </div>
                <div class="span3">
                    <label>Data Acompanhamento</label>
                    <?= date('d/m/Y'); ?>
                    <input type="hidden" id="datacompanhamento" name="datacompanhamento" value="<?= date('Y-m-d'); ?>">
                </div>
                <div class="span3">
                    <label>Previsto</label>
                    <?= $this->statusreport['estimativas']->numpercentualprevisto . "%"; ?>
                    <input type="hidden" id="numpercentualprevisto" name="numpercentualprevisto" value="<?= $this->statusreport['estimativas']->numpercentualprevisto; ?>">
                </div>
                <div class="span2">
                    <label>Concluído</label>
                    <?= $this->statusreport['estimativas']->numpercentualconcluido . "%"; ?>
                    <input type="hidden" id="numpercentualconcluido" name="numpercentualconcluido" value="<?= $this->statusreport['estimativas']->numpercentualconcluido; ?>">
                </div>
            </div>
            <div class="row" style=" margin-left: 1px;">
                <div class="span3">
                    <?= $this->form->idmarco ? $this->form->idmarco : "";?>
                </div>
                <div class="span1">
                    <?= $this->semaforo ? $this->semaforo : "";?>
                </div>
                <div class="span3">
                    <label>Tendência do Projeto</label>
                    <?= $this->datfimprojetotendencia;; ?>
                    <input type="hidden" id="datfimprojetotendencia" name="datfimprojetotendencia" value="<?= $this->datfimprojetotendencia; ?>">

                </div>
                <div class="span3">
                    <?= $this->form->domcorrisco; ?>
                </div>
            </div>
            <div class="row" style="margin-top: 20px; margin-left: 1px;">
                <div class="span5">
                    <?php echo $this->form->desatividadeconcluida; ?>
                </div>
                <div class="span5">
                    <?php echo $this->form->desatividadeandamento; ?>
                </div>
            </div>
            <div class="row" style="margin-left: 1px;">
                <div class="span5">
                    <?php echo $this->form->desmotivoatraso; ?>
                </div>
                <div class="span5">
                    <?php echo $this->form->descontramedida; ?>
                </div>
            </div>
            <div class="row" style="margin-left: 1px;">
                <div class="span5">
                    <?php echo $this->form->desirregularidade; ?>
                </div>
                <div class="span5">
                    <?php echo $this->form->desrisco; ?>
                </div>
            </div>
            <div class="row" style="margin-left: 1px;">
                <div class="span10">
                    <b>Cronograma em PDF </b> (Clique aqui <a href="<?php echo $this->baseUrl('/projeto/cronograma/imprimir-pdf/idprojeto/' . $this->idprojeto); ?>" target="_blank"> <i class="icon-download-alt"/> </a> gere um arquivo PDF do cronograma atual do projeto. Esse procedimento será essencial no futuro.)
                </div>
            </div>
            <div class="row" style="margin-left: 1px;margin-top: 5px;">
                <div class="span5">
                   <?php echo $this->form->descaminho; ?>
                </div>
            </div>
            <?php echo $this->form->idprojeto; ?>
        </form>
<?php } ?>


    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>
    <input type="hidden" id="isr" value="<?php echo $this->idprojeto; ?>">
</div>
