<?php
$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");

$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/relatorio/relatorio.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();

?>

<script type="text/javascript">
    $(document).ready(function () {
        $.pnotify.defaults.history = false;

        $("#numprocessosei").mask("99999.999999/9999-99", {reverse: true});

        var valor = $("#domstatusprojetoDois option:selected").val();
        $("#domstatusprojeto option[value=" + valor + "]").attr("selected", "selected");


        $('#idmarco').prop('required', true);
        $("#proximomarco").addClass('required');

        $('#flaaprovado').change(function () {
            if ($("#domstatusprojetoDois option:selected").val() == 2) {
                $("#idmarco").addClass('required', 'required');
            }
        });

        $('#flaaprovado, #pgpassinado').on('change', function () {
            var tapAssinado = $('#flaaprovado').val();
            var pgpassinado = $('#pgpassinado').val();
            $("#idmarco").addClass('required', 'required');

            if ($("#idmarco option:selected").val() == "" && (tapAssinado == 1 && pgpassinado == 'N')) {
                $('#idmarco').html("Não há marco cadastrado.");
                $("#idmarco").append('<option value="1">Não há marco cadastrado.</option>');
                $("#proximomarco").removeClass('required success');
                $("label[for='idmarco']").remove();
            } else if ($("#idmarco option:selected").val() == "" || $("#idmarco option:selected").val() == 1) {
                $('#idmarco').html("");
                $("#idmarco").append('<option value=""></option>');
                $("#proximomarco").addClass('required');
            } else {
                $("#idmarco option:selected").val();
            }

            if ($("#idmarco option:selected").val() == "" || (tapAssinado == 2 && pgpassinado == 'N')) {
                $("#idmarco").addClass('required', 'required');
            } else {
                $("#idmarco").removeClass('required', 'required');
                $("label[for='idmarco']").remove();
            }

        });

    });
</script>
<div class="region-center">
    <?php
    if ((isset($this->atividadesDesatualizadas)) && (!$this->ignoreatividadesatrasadas)){ ?>
    <form id="<?php echo $frmAttr['id']; ?>"
          name="<?php echo $frmAttr['id']; ?>"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">
        <?php
        echo "<div class=\"portlet portlet-marron span12\">";
        echo "<tr><td > <font size=2 color=red> ATENÇÃO: <b> As atividades abaixo estão desatualizadas no cronograma, todas estão com data fim menor ou igual a data de <b>Hoje</b>!</b></font>";
        //echo "<p></b> <br>Para  gerar o Relatório de Situação (Status Report),mesmo com as atividades desatualizadas, clique no botão <b>Continuar</b>.</font>";

        foreach ($this->atividadesDesatualizadas as $ativ) {
            echo "<li><b>" . $ativ["numseq"] . "</b> - " . $ativ["datinicio"] . " à <font color=red><u>" . $ativ["datfim"] . "</u></font> - " . $ativ["nomatividadecronograma"] . "<br>";
        }
        echo "</div>";
        echo "<p></b> <br>Para  gerar o Relatório de Situação (Consulta), atualize o cronograma, informando as novas datas de In&iacute;cio-Fim (Realizado) ou alterando o percentual de conclus&atilde;o para 100%.</font>"
            . "<div style='display:none'>Atualizar cronograma</div>";
        echo $this->form->idprojeto;

        echo "<input type=\"hidden\" id=\"QtAtividadesDesatualizadas\" name=\"QtAtividadesDesatualizadas\" value=\"" . $this->QtAtividadesDesatualizadas . "\"></form>";
        } else {
            ?>
            <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <div class="row" style="margin-top: 20px; margin-left: 1px;">
                    <div class="span2">
                        <?php echo $this->form->flaaprovado; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->pgpassinado; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->tepassinado; ?>
                    </div>
                    <div class="span3" id="numcei">
                        <label class="control-label">Nº do processo</label>
                        <input type="text" name="numprocessosei" id="numprocessosei"
                               value="<?php echo $this->numProcessoSei['numprocessosei']; ?>">
                    </div>
                </div>
                <div class="row" style="margin-top: 20px; margin-left: 1px;">
                    <div class="span3">
                        <?php echo $this->form->domstatusprojeto; ?>
                    </div>
                    <div class="span3" style="display:none">
                        <label class="control-label required">Status do Projeto</label>
                        <select name="domstatusprojetoDois" id="domstatusprojetoDois">
                            <option value="<?php echo $this->statusdoprojeto['idstatusprojeto']; ?>"><?php echo $this->statusdoprojeto['domstatusprojeto']; ?></option>
                        </select>
                    </div>
                    <div class="span3">
                        <label>Data do Relatório</label>
                        <?php echo date('d/m/Y'); ?>
                        <input type="hidden" id="datacompanhamento" name="datacompanhamento"
                               value="<?php echo date('Y-m-d'); ?>">
                    </div>
                    <div class="span3">
                        <label>% Concluído Planejado</label>
                        <?php
                        $planejado = $this->statusreport['estimativas']->numpercentualprevisto;
                        echo $planejado = $planejado ? $planejado . "%" : 0;
                        ?>
                        <input type="hidden" id="numpercentualprevisto" name="numpercentualprevisto"
                               value="<?php echo $this->statusreport['estimativas']->numpercentualprevisto; ?>">
                    </div>
                    <div class="span2">
                        <label>% Concluído Realizado</label>
                        <?php
                        $realizado = $this->statusreport['estimativas']->numpercentualconcluido;
                        echo $realizado = $realizado ? $realizado . "%" : 0;

                        ?>
                        <input type="hidden" id="numpercentualconcluido" name="numpercentualconcluido"
                               value="<?php echo $this->statusreport['estimativas']->numpercentualconcluido; ?>">
                    </div>
                </div>
                <div class="row" style=" margin-left: 1px;">
                    <div class="span3">
                        <?php //echo $this->form->idmarco ? $this->form->idmarco : ""; ?>
                        <label class="control-label">Próximo Marco</label>
                        <select name="idmarco" id="idmarco" readonly='true'>
                            <option value="<?php echo $this->proximoMarco->idatividadecronograma; ?>"><?php echo $this->esc($this->proximoMarco->nomatividadecronograma); ?></option>
                        </select>
                    </div>
                    <div class="span2">
                        <label>Atraso em dias:</label>
                        <span class='badge badge-<?php echo $this->domcoratraso; ?>'
                              title='<?php echo $this->atraso; ?>'><?php echo $this->atraso; ?></span>
                        <?php //echo $this->semaforo ? $this->semaforo : ""; ?>
                        <input type="hidden" name="diaatraso" id="diaatraso" value="<?php echo $this->atraso; ?>">
                        <input type="hidden" name="domcoratraso" id="domcoratraso"
                               value="<?php echo $this->domcoratraso; ?>">
                    </div>
                    <div class="span3">
                        <label>Tendência do Projeto</label>
                        <?php echo $this->datfimprojetotendencia; ?>
                        <input type="hidden" id="datfimprojetotendencia" name="datfimprojetotendencia"
                               value="<?php echo $this->datfimprojetotendencia; ?>">

                    </div>
                    <div class="span3">
                        <?php echo $this->form->domcorrisco; ?>
                    </div>
                </div>
                <div class="row" style="margin-top: 20px; margin-left: 1px;">
                    <div class="span5">
                        <?php echo $this->form->desandamentoprojeto; ?>
                        <strong style="display: none;">Restam <span id="contDesAndamentoProj" style="color: red"></span>
                            caracteres a serem digitados.</strong>
                    </div>
                </div>
                <div class="row" style="margin-top: 20px; margin-left: 1px;">
                    <div class="span5">
                        <label>Atividades Concluídas no
                            Período: <?php echo $this->periodo['datainiperiodo'] . ' a ' . $this->periodo['datafinperiodo']; ?> </label>
                        <?php echo $this->form->desatividadeconcluida; ?>
                        <strong style="display: none;">Restam <span id="contDesConcluida" style="color: red"></span>
                            caracteres a serem digitados.</strong>
                    </div>
                    <div class="span5">
                        <label>Atividades em Andamento até: <?php echo $this->periodo['datafinperiodo']; ?> </label>
                        <?php echo $this->form->desatividadeandamento; ?>
                        <strong style="display: none;">Restam <span id="contDesAndamento" style="color: red"></span>
                            caracteres a serem digitados.</strong>
                    </div>
                </div>
                <div class="row" style="margin-left: 1px;">
                    <div class="span5">
                        <?php echo $this->form->desmotivoatraso; ?>
                        <strong style="display: none;">Restam <span id="contDesAtraso" style="color: red"></span>
                            caracteres a serem digitados.</strong>
                    </div>
                    <div class="span5">
                        <?php echo $this->form->descontramedida; ?>
                        <strong style="display: none;">Restam <span id="contDesContramedida" style="color: red"></span>
                            caracteres a serem digitados.</strong>
                    </div>
                </div>
                <div class="row" style="margin-left: 1px;">
                    <div class="span5">
                        <?php echo $this->form->desirregularidade; ?>
                        <strong style="display: none;">Restam <span id="contDesIrregularidade"
                                                                    style="color: red"></span> caracteres a serem
                            digitados.</strong>
                    </div>
                    <div class="span5">
                        <?php echo $this->form->desrisco; ?>
                        <strong style="display: none;">Restam <span id="contDesRisco" style="color: red"></span>
                            caracteres a serem digitados.</strong>
                    </div>
                </div>
                <div class="row" style="margin-left: 1px;">
                    <div class="span10">
                        <b>Cronograma em PDF </b> (Clique aqui <a
                                href="<?php echo $this->baseUrl('/projeto/cronograma/imprimir-pdf/idprojeto/' . $this->idprojeto); ?>"
                                target="_blank"> <i id="icon" class="icon-download-alt"/> </a> para visualizar o arquivo
                        PDF do cronograma atual do projeto.)
                    </div>
                </div>
                <div class="row" style="margin-left: 1px;margin-top: 5px;" id="divFile">
                    <div class="span5">
                        <?php //echo $this->form->descaminho; ?>
                        <!--Arquivo: <?php //echo $this->descaminho; ?> -->
                        <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->idprojeto; ?>">
                        <input type="hidden" name="descaminho" id="descaminho"
                               value="<?php echo $this->descaminho; ?>"/>
                    </div>
                </div>
                <?php echo $this->form->idprojeto; ?>
                <div class="row">
                    <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 20px;">
                        (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                        obrigatório
                    </div>
                </div>
            </form>
        <?php } ?>
        <table id="list2"></table>
        <div id="toolbar2"></div>
        <div id="pager2"></div>
        <input type="hidden" id="isr" value="<?php echo $this->idprojeto; ?>">
</div>
