
        <div class="row">
            <div class="portlet portlet-cinza span4">
                <h3>Status Projeto</h3>
                <div class="content">
                    <?= $this->statusreport->nomstatusprojeto; ?>
                </div>
            </div>
            <div class="portlet portlet-azul span2">
                <h3>Data Acompanhamento</h3>
                <div class="content">
                    <?= $this->statusreport->datcadastro->toString('d/m/Y'); ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span2">
                <h3>Previsto</h3>
                <div class="content">
                    <?= $this->statusreport->numpercentualprevisto . "%"; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span2">
                <h3>Concluído</h3>
                <div class="content">
                    <?= $this->statusreport->numpercentualconcluido . "%"; ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="portlet portlet-cinza span4">
                <h3>Próximo Marco</h3>
                <div class="content">
                    <?= $this->statusreport->nomproximomarco; ?>
                </div>
            </div>
            <!-- <div class="portlet portlet-cinza span2">
                <h3>Semáforo</h3>
                <div class="content">
                    <?php // /echo $this->semaforo; ?>
                </div>
            </div> -->
            <div class="portlet portlet-cinza span2">
                <h3>Tendência do Projeto</h3>
                <div class="content">
                    <?= $this->statusreport->datcadastro->toString('d/m/Y'); ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span2">
                <h3>Risco Atual do Projeto</h3>
                <div class="content">
                    <?= $this->statusreport->nomrisco; ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="portlet portlet-cinza span5">
                <h3>Atividades Concluídas no Período</h3>
                <div class="content">
                    <?= $this->statusreport->desatividadeconcluida; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span5">
                <h3>Atividades em Andamento no Período</h3>
                <div class="content">
                    <?= $this->statusreport->desatividadeandamento; ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="portlet portlet-cinza span5">
                <h3>Motivo de Atraso no Prazo Final do Projeto</h3>
                <div class="content">
                    <?= $this->statusreport->desmotivoatraso; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span5">
                <h3>Contramedidas (R3G)</h3>
                <div class="content">
                    <?= $this->statusreport->descontramedida; ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="portlet portlet-cinza span5">
                <h3>Irregularidades</h3>
                <div class="content">
                    <?= $this->statusreport->desirregularidade; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span5">
                <h3>Riscos</h3>
                <div class="content">
                    <?= $this->statusreport->desrisco; ?>
                </div>
            </div>
        </div>


<!--<table id="list2"></table>
<div id="toolbar2"></div>
<div id="pager2"></div>
<input type="hidden" id="isr" value="<?php //echo $this->idprojeto;      ?>"> -->
