<div class="row">
    <div class="portlet portlet-cinza span4">
        <h3>TAP assinado?</h3>
        <div class="content">
            <?php
            if ($this->statusreport->flaaprovado == 2) {
                echo 'Não';
            } else {
                echo 'Sim';
            }
            ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>PGP assinado?</h3>
        <div class="content">
            <?php
            if ($this->statusreport->pgpassinado == 'N') {
                echo 'Não';
            } else {
                echo 'Sim';
            }
            ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>TEP assinado?</h3>
        <div class="content">
            <?php
            if ($this->statusreport->tepassinado == 'N') {
                echo 'Não';
            } else {
                echo 'Sim';
            }
            ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Nº do processo</h3>
        <div class="content">
            <?php echo $this->numProcessoSei; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span4">
        <h3>Status Projeto</h3>
        <div class="content">
            <?php echo $this->statusreport->nomstatusprojeto; ?>
        </div>
    </div>
    <div class="portlet portlet-azul span2">
        <h3>Data do Relatório</h3>
        <div class="content">
            <?php echo $this->statusreport->datcadastro->toString('d/m/Y'); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>% Concluído Planejado</h3>
        <div class="content">
            <?php
            $planejado = $this->statusreport->numpercentualprevisto;
            if ($planejado == "0.00") {
                echo '0';
            } else {
                echo $planejado . "%";
            }
            ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>% Concluído Realizado</h3>
        <div class="content">
            <?php
            $realizado = $this->statusreport->numpercentualconcluido;
            if ($realizado == "0.00") {
                echo '0';
            } else {
                echo $realizado . "%";
            }
            ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span4">
        <h3>Próximo Marco</h3>
        <div class="content">
            <?php
            $marco = $this->statusreport->nomproximomarco;
            echo $marco = $marco ? $marco : "Não há marco cadastrado.";
            ?>
        </div>
    </div>
    <!-- <div class="portlet portlet-cinza span2">
                <h3>Semáforo</h3>
                <div class="content">
                    <?php // /echo $this->semaforo; ?>
                </div>
            </div> -->
    <div class="portlet portlet-cinza span2">
        <h3>Tendência do Projeto</h3>
        <div class="content">
            <?php echo $this->statusreport->datfimprojetotendencia->toString('d/m/Y'); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Risco Atual do Projeto</h3>
        <div class="content">
            <?php echo $this->statusreport->nomrisco; ?>
        </div>
    </div>
</div>
<div class="row" style="margin-left: -30px;">
    <div class="portlet portlet-cinza span5">
        <h3>Considerações gerais sobre o andamento do projeto</h3>
        <div class="content">
            <?php
            if ($this->statusreport->desandamentoprojeto != null) {
                echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->desandamentoprojeto);
            } else {
                echo 'Não há considerações.';
            }
            ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span5">
        <h3>Atividades Concluídas no
            Período: <?php echo $this->periodo['datainiperiodo'] . ' a ' . $this->periodo['datafinperiodo']; ?></h3>
        <div class="content">
            <?php echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->desatividadeconcluida); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span5">
        <h3>Atividades em Andamento até: <?php echo $this->periodo['datafinperiodo']; ?></h3>
        <div class="content">
            <?php echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->desatividadeandamento); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span5">
        <h3>Motivo de Atraso no Prazo Final do Projeto</h3>
        <div class="content">
            <?php echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->desmotivoatraso); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span5">
        <h3>Contramedidas (R3G)</h3>
        <div class="content">
            <?php echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->descontramedida); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span5">
        <h3>Irregularidades</h3>
        <div class="content">
            <?php echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->desirregularidade); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span5">
        <h3>Riscos</h3>
        <div class="content">
            <?php echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->statusreport->desrisco); ?>
        </div>
    </div>
</div>


<!--<table id="list2"></table>
<div id="toolbar2"></div>
<div id="pager2"></div>
<input type="hidden" id="isr" value="<?php //echo $this->idprojeto;      ?>"> -->
