<?php
$this->headLink()
        ->appendStylesheet($this->baseUrl('/css/form.css'))
        ->appendStylesheet($this->baseUrl('/css/portlet.css'))
        ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
        ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
;

$this->headScript()
        ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();
?>

<form id="<?php echo $frmAttr['id']; ?>"
      name="<?php echo $frmAttr['id']; ?>"
      action="<?php echo $this->form->getAction(); ?>"
      method="<?php echo $frmAttr['method']; ?>">
    <div class="row" style="margin-top: 20px; margin-left: 1px;">
        <div class="span3">
            <p>Status</p>
            <?php 
                switch ($this->statusreport->domstatusprojeto){
                    case 1 :
                        echo "<p>Proposta</p>";
                        break;
                    case 2:
                        echo "<p>Em andamento</p>";
                        break;
                    case 3:
                        echo "<p>Concluído</p>";
                        break;
                    case 4:
                        echo "<p>Paralisado</p>";
                        break;
                    case 5:
                        echo "<p>Cancelado</p>";
                        break;
                    case 7:
                        echo "<p>Em alteração</p>";
                        break;
                } 
?>
        </div>
        <div class="span3">
            <label>Data Acompanhamento</label>
            <?= $this->statusreport->datcadastro->toString('d/m/Y'); ?>
            <input type="hidden" id="datacompanhamento" name="datacompanhamento" value="<?= $this->statusreport->datcadastro->toString('d/m/Y'); ?>">
        </div>
        <div class="span3">
            <label>Previsto</label>
            <?= $this->statusreport->numpercentualprevisto . "%"; ?>
            <input type="hidden" id="numpercentualprevisto" name="numpercentualprevisto" value="<?= $this->statusreport->numpercentualprevisto; ?>">
        </div>
        <div class="span2">
            <label>Concluído</label>
            <?= $this->statusreport->numpercentualconcluido . "%"; ?>
            <input type="hidden" id="numpercentualconcluido" name="numpercentualconcluido" value="<?= $this->statusreport->numpercentualconcluido; ?>">
        </div>
    </div>
    <div class="row" style=" margin-left: 1px;">
        <div class="span3">
            <?= $this->form->idmarco; ?>
        </div>
        <div class="span1">
            <?= $this->semaforo; ?>
        </div>
        <div class="span3">
            <?= $this->form->datfimprojetotendencia; ?>
        </div>
        <div class="span3">
            <?= $this->form->domcorrisco; ?>
        </div>
    </div>
    <div class="row" style="margin-top: 20px; margin-left: 1px;">
        <div class="span5">
            <?php echo $this->form->desatividadeconcluida; ?>
        </div>
        <div class="span5">
            <?php echo $this->form->desatividadeandamento; ?>
        </div>
    </div>
    <div class="row" style="margin-left: 1px;">
        <div class="span5">
            <?php echo $this->form->desmotivoatraso; ?>
        </div>
        <div class="span5">
            <?php echo $this->form->descontramedida; ?>
        </div>
    </div>
    <div class="row" style="margin-left: 1px;">
        <div class="span5">
            <?php echo $this->form->desirregularidade; ?>
        </div>
        <div class="span5">
            <?php echo $this->form->desrisco; ?>
        </div>
    </div>
    <?php if($this->anexo){ ?>
    <div class="row" style="margin-left: 1px;">
        <div class="span5">
            <a target="_blank" class="btn" href="<?php echo $this->anexo;?>">VISUALIZAR PDF</a>
        </div>
    </div>
    <?php } ?>
    <div class="row" style="margin-left: 1px;">
        <div class="span5">
            <?php echo $this->form->descaminho; ?>
        </div>
    </div>
     <?php echo $this->form->idprojeto; ?>
     <?php echo $this->form->idstatusreport; ?>
</form>


<!--<table id="list2"></table>
<div id="toolbar2"></div>
<div id="pager2"></div>
<input type="hidden" id="isr" value="<?php //echo $this->idprojeto; ?>"> -->
