<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/relatorio/index.css')) /*SAPS 110567*/
;

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/relatorio/relatorio.js'), 'text/javascript')

    //graficos
    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/knockout-2.2.1.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/globalize.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/dx.chartjs.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/statusreport/acompanhamento-chart.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();
?>

<div class="region-west" >
    <?php
    echo $this->partial('_partials/menu-projeto.phtml', array('ativo' => 'relatorio', 'idprojeto' => $this->projeto->idprojeto));
    ?>
</div>
<div class="region-center" >
    <?php echo $this->partial('_partials/projeto.phtml', array('projeto' => $this->projeto)); ?>
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <!--<a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>-->
            <a class="btn incluir" data-target="#dialog-incluir" href="<?php echo $this->url(array('module' => 'projeto', 'controller' => 'relatorio', 'action' => 'add')); ?>">Novo Acompanhamento</a>
        </div>
    </div>

    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>
    <input type="hidden" id="ip" value="<?php echo $this->projeto->idprojeto; ?>">
    <input type="hidden" id="idprojeto" value="<?php echo $this->projeto->idprojeto; ?>">
    <br>
    <div class="row">
        <div class="portlet portlet-cinza span6">
            <div class="title">% Concluído ( Planejado x Realizado)</div>
            <div class="content">
                <div id="chartcontainer-planejado-realizado" style="max-width:580px;height: 160px;"></div>
            </div>
        </div>
        <div class="portlet portlet-cinza span6">
            <div class="title">Evolução Atraso</div>
            <div class="content">
                <div id="chartcontainer-atraso" style="max-width:500px;height: 160px;"></div>
            </div>
        </div>
    </div>
    <!--<div class="region-east" >
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar Relatório</div>
            <div class="content">
                <form id="<?php /*echo $frmAttr['id']; */?>"
                      name="<?php /*echo $frmAttr['id']; */?>"
                      action="<?php /*echo $this->form->getAction(); */?>"
                      method="<?php /*echo $frmAttr['method']; */?>">
                    <div class="row">
                        <div class="span3">
                            <?php /*//echo $this->form->nomprojeto; */?>
                        </div>
                        <div class="span3">
                            <?php /*//echo $this->form->idprograma; */?>
                        </div>
                        <div class="span3">
                            <?php /*//echo $this->form->idescritorio; */?>
                        </div>
                        <div class="span3">
                            <?php /*//echo $this->form->domstatusprojeto; */?>
                        </div>
                        <div class="span2">
                            <?php /*//echo $this->form->nomareaexecutora; */?>
                        </div>

                        <div class="span2">
                            <?php /*//echo $this->form->nomalinhamento; */?>
                        </div>
                        <div class="span2">
                            <?php /*//echo $this->form->nomacao; */?>
                        </div>
                        <div class="span">
                            <?php /*//echo $this->form->nomnatureza; */?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php /*//echo $this->form->submit; */?>
                                <?php /*//echo $this->form->reset; */?>
                                <?php /*//echo $this->form->close; */?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
-->
</div>

<div id="dialog-mensagem" class="alert-error" style="display: none;"></div>
<div id="dialog-incluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>
<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>