<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/termoaceite/add.css')) /*SAPS 110567*/
    ;

$this->headScript()->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/projeto/termoaceite/add.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/termoaceite/index.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml', array('ativo' => 'aceite', 'idprojeto' => $this->idprojeto));
    ?>
</div>
<div class="region-center" >

    <div id="dados-projeto"></div>

    <div class="row">
        <div class="portlet portlet-marron span13">
            <div class="title">Cadastrar Aceite</div>
            <div class="content"> 
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <?php  ?>
                     <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
                    <div class="row">
                        <div class="span6">
                            <?php echo $this->form->identrega; ?>
                        </div>
                        <div class="span4">
                            <?php echo $this->form->flaaceite; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span6">
                            <?php echo $this->form->idmarco; ?>
                        </div>
                    </div>
                        <div class="row dados-entrega" style="display: none;">
                            <div class="span6 well well-small">
                                <p class="descricao-entrega"> Descri&ccedil;&atilde;o Entrega: <span></span> </p>
                                <p class="criterio-aceitacao"> Crit&eacute;rio de Aceita&ccedil;&atilde;o: <span></span> </p>
                                <p class="responsavel">  Respons&aacute;vel: <span></span> </p>
                            </div>
                        </div>
                        <div class="row">
                           <div class="span6">
                                <?php echo $this->form->desprodutoservico; ?>
                           </div>
                        </div>
                        <div class="row">
                           <div class="span6">
                                <?php echo $this->form->desparecerfinal; ?>
                           </div>
                        </div>
                        <div class="row">
                          <div class="span5">
                              <?php echo $this->form->idcadastrador;
                              echo $this->form->submit;
                               ?>
                          </div>
                       </div>
                  </form>
                </div>
            </div>
        </div>
</div>


