<div class="row">
    <div class="portlet portlet-azul span7">
        <h3>Entrega</h3>
        <div class="content">
            <?php echo $this->aceite->nomatividadecronograma; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span1">
        <h3>Aceite?</h3>
        <div class="content">
            <?php echo $this->aceite->desflaaceite; ?>
        </div>
    </div>
</div>
<div class="row" style="display: none">
    <div class="portlet portlet-azul span7">
        <h3>Marco da Entrega</h3>
        <div class="content">
            <?php echo $this->nomarco; ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="portlet portlet-cinza span3">
        <h3>Descri&ccedil;&atilde;o Entrega</h3>
        <div class="content">
            <?php echo $this->aceite->desobs; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span3">
        <h3>Crit&eacute;rio de Aceita&ccedil;&atilde;o</h3>
        <div class="content">
            <?php echo $this->aceite->descriterioaceitacao; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Respons&aacute;vel pela entrega</h3>
        <div class="content">
            <?php echo $this->aceite->nomparteinteressadaentrega; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Respons&aacute;vel pelo aceite</h3>
        <div class="content">
            <?php echo $this->aceite->nomresponsavel; ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="portlet portlet-cinza span8">
        <h3>Produto ou Servi&ccedil;o Entregue</h3>
        <div class="content">
            <?php echo $this->aceite->desprodutoservico; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span8">
        <h3>Parecer Final</h3>
        <div class="content">
            <?php echo $this->aceite->desparecerfinal; ?>
        </div>
    </div>
</div>