<div class="row">
    <div class="portlet portlet-azul span4">
        <h3>Entrega Associada</h3>
        <div class="content">
            <?= $this->aceite->nomatividadecronograma; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span3">
        <h3>Marco da Entrega</h3>
        <div class="content">
            <?= $this->aceite->nomarco; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span1">
        <h3>Aceite?</h3>
        <div class="content">
            <?= $this->aceite->desflaaceite; ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="portlet portlet-cinza span3">
        <h3>Descri&ccedil;&atilde;o Entrega</h3>
        <div class="content">
            <?= $this->aceite->desobs; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span3">
        <h3>Crit&eacute;rio de Aceita&ccedil;&atilde;o</h3>
        <div class="content">
            <?= $this->aceite->descriterioaceitacao; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Respons&aacute;vel</h3>
        <div class="content">
            <?= $this->aceite->nomresponsavel; ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="portlet portlet-cinza span8">
        <h3>Produto ou Servi&ccedil;o Entregue</h3>
        <div class="content">
            <?= $this->aceite->desprodutoservico; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span8">
        <h3>Parecer Final</h3>
        <div class="content">
            <?= $this->aceite->desparecerfinal; ?>
        </div>
    </div>
</div>