
    <form id="form-aceite-excluir"
            name="form-aceite-excluir"
            action="<?php echo $this->baseUrl(); ?>/projeto/termoaceite/excluir/format/json"
            method="post">
    <?php  ?>
     <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
     <input type="hidden" name="idaceite" value="<?php echo $this->aceite->idaceite ?>"/>
     <input type="hidden" name="idaceiteativcronograma" value="<?php echo $this->idaceiteativcronograma ?>"/>
        <div class="row">
            <div class="portlet portlet-azul span7">
                <h3>Entrega</h3>
                <div class="content">
                    <?= $this->aceite->nomatividadecronograma; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span1">
                <h3>Aceite?</h3>
                <div class="content">
                    <?= $this->aceite->desflaaceite; ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="portlet portlet-cinza span3">
                <h3>Descri&ccedil;&atilde;o Entrega</h3>
                <div class="content">
                    <?= $this->aceite->desobs; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span3">
                <h3>Crit&eacute;rio de Aceita&ccedil;&atilde;o</h3>
                <div class="content">
                    <?= $this->aceite->descriterioaceitacao; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span2">
                <h3>Respons&aacute;vel</h3>
                <div class="content">
                    <?= $this->aceite->nomresponsavel; ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="portlet portlet-cinza span8">
                <h3>Produto ou Servi&ccedil;o Entregue</h3>
                <div class="content">
                    <?= $this->aceite->desprodutoservico; ?>
                </div>
            </div>
            <div class="portlet portlet-cinza span8">
                <h3>Parecer Final</h3>
                <div class="content">
                    <?= $this->aceite->desparecerfinal; ?>
                </div>
            </div>
        </div>
  </form>
