<script>

    $(function () {
        $.pnotify.defaults.history = false;
    });

    function resetFormPergunta() {
        $("#form-pergunta :input").val('');
    }

</script>


<?php $frmAttrPergunta = $this->formPergunta->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <form id="<?php echo $frmAttrPergunta['id']; ?>"
              name="<?php echo $frmAttrPergunta['id']; ?>"
              action="<?php echo $this->formPergunta->getAction(); ?>"
              method="<?php echo $frmAttrPergunta['method']; ?>">
            <div class="row-fluid">
                <div class="span">
                    <?php echo $this->formPergunta->desfrase ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span3">
                    <?php echo $this->formPergunta->domtipofrase ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <?php echo $this->formPergunta->flaativo ?>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 190px;">
        (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
    </div>
</div>