<?php $frmAttrPergunta = $this->form->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <form id="<?php echo $frmAttrPergunta['id']; ?>"
              name="<?php echo $frmAttrPergunta['id']; ?>"
              action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $frmAttrPergunta['method']; ?>">    
            <?php echo $this->form->idfrase ?>
            <div class="row-fluid">                                                                       
                <div class="span">
                    <?php echo $this->form->desfrase ?>
                </div>
            </div>
            <div class="row-fluid"> 
                <div class="span3">
                    <?php echo $this->form->domtipofrase ?>
                </div>
            </div>
            <div class="row-fluid"> 
                <div class="span2">
                    <?php echo $this->form->flaativo ?>                
                </div>
            </div>
        </form>
    </div>
</div>