<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/cadastro/documento/add.js'), 'text/javascript');
//echo $this->form;
$frmAttr = $this->form->getAttribs();
?>
<div class="row">
    <div class="portlet portlet-marron span12">
        <div class="title">Cadastrar Documentos</div>
        <div class="content">
            <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  enctype="<?php echo $frmAttr['enctype']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <div class="row">
                    <div class="span8">

                        <div class="row">
                            <div class="span6">
                                <?php echo $this->form->nomdocumento; ?>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="span8">

                        <div class="row">
                            <div class="span4">
                                <?php echo $this->form->idtipodocumento; ?>
                            </div>
                            <div class="span2">
                                <?php echo $this->form->datdocumento; ?>
                            </div>
                            <div class="span2">
                                <?php echo $this->form->flaativo; ?>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="span8">

                        <div class="row">
                            <div class="span2">
                                <?php echo $this->form->descaminho; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="span8">
                        <?php echo $this->form->desobs; ?>
                    </div>
                </div>
                <div class="row form-actions">
                    <div class="span4">
                        <?php echo $this->form->iddocumento; ?>
                        <?php echo $this->form->submit; ?>
                        <?php echo $this->form->reset; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


