<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.layout.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/cadastro/recurso/permissao.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/cadastro/recurso/gerenciar.js'), 'text/javascript');
$frmAttr = $this->form->getAttribs();
?>

<script>
    $('.k-last').remove();
</script>

<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-lateral.phtml', array('id' => 'security'));
    ?>
</div>
<div class="region-east">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->idrecurso; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idpermissao; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->ds_permissao; ?>
                        </div>
                    </div>
                    <div class="btn-group">
                        <?php echo $this->form->submit; ?>
                        <?php echo $this->form->reset; ?>
                        <?php echo $this->form->close; ?>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="abas" class="region-center">
    <div class="form-actions form-actions-mini">
        <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
    </div>
    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>
</div>

<div id="dialog-editar" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>