<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>

<div class="region-center">
    <h4 class="pagination-centered">Formulário - Informações para Adidância da PF em Washington</h4>
    <?php if ($this->message): ?>
        <div class="row-fluid">
            <div class="span alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong><?php echo $this->message; ?></strong>
            </div>
        </div>
    <?php endif; ?>
    <br/>
    <div class="row-fluid">
        <div class="span4">&nbsp</div>
        <div class="portlet portlet-cinza span4">
            <div class="title">Formul&aacute;rio exige identifica&ccedil;&atilde;o!</div>
            <div class="content">
                <div class="row-fluid">
                    <div class="span">
                        <form id="<?php echo $frmAttr['id']; ?>"
                              name="<?php echo $frmAttr['id']; ?>"
                              action="<?php echo $this->form->getAction(); ?>"
                              method="<?php echo $frmAttr['method']; ?>">
                            <div class="row-fluid">
                                <div class="span">
                                    <?php echo $this->form->username; ?>
                                </div>
                            </div>
                            <br/>
                            <div class="row-fluid">
                                <div class="span">
                                    <?php echo $this->form->password; ?>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span pagination-centered">
                                    <?php echo $this->form->enviar ?>
                                    <?php echo $this->form->cancelar ?>
                                    <a href="<?php echo $this->baseUrl('/pesquisa/responder/listar') ?>" class="btn">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="span4">&nbsp</div>
    </div>
    <div class="row-fluid">
        <div class="span">
            <ul> Caso tenha problemas ao efetuar login, envie e-mail com os dados abaixo para <a
                        href="mailto:egp.gabdg@dpf.gov.br">egp.gabdg@dpf.gov.br</a>.
                <ul>
                    <li>Nome Completo;</li>
                    <li>Matrícula DPF;</li>
                    <li>Login de Rede;</li>
                    <li>CPF;</li>
                    <li>E-mail institucional;</li>
                    <li>Número SIAPE; e</li>
                    <li>Cargo.</li>
                </ul>
            </ul>
        </div>
    </div>
</div>