<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'),
    'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/evento/avaliacaoservidor/add.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <div class="row">
        <div class="portlet portlet-marron span-18">
            <div class="title">Cadastrar Avaliação</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row" style="padding: 10px 0;">
                        <div class="span4"> Avaliador: <?php echo $this->nomavaliador; ?></div>
                        <div class="span4"> Data da Avalia&ccedil;&atilde;o: <?php echo date('d/m/Y'); ?> </div>
                    </div>
                    <div class="row">
                        <div class="span4">
                            <?php echo $this->form->idevento; ?>
                        </div>
                        <div class="span4 container-pessoa">
                            <div class="control-group">
                                <?php echo $this->form->nomavaliado->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->nomavaliado->renderViewHelper(); ?>
                                    <?php echo $this->form->idavaliado; ?>
                                </div>
                            </div>
                        </div>
                        <div class="span4">
                            <?php echo $this->form->idtipoavaliacao; ?>
                        </div>
                    </div>
                    <div class="row grid-append" style="display: none;">
                    </div>
                    <div class="row">
                        <div class="span10">
                            <table class="table table-hover table-striped table-condensed"
                                   style="padding: 5px; margin: 15px 0px;">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Sempre</th>
                                    <th>Frequentemente</th>
                                    <th>Raramente</th>
                                    <th>Nunca</th>
                                    <th style="color: red;">*Prejudicado</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->perguntas as $key => $pergunta): ?>
                                    <tr>
                                        <td style="padding: 0px 15px;"> <?php echo $pergunta; ?> </td>
                                        <td style="text-align: center;"><input type="radio" name="<?php echo $key ?>"
                                                                               value="10"/></td>
                                        <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                              value="8"/></td>
                                        <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                              value="2"/></td>
                                        <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                              value="0"/></td>
                                        <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                              value="-1" checked="checked"/></td>
                                    </tr>
                                <?php endforeach; ?>
                                <tr>
                                    <td colspan="6"><?php echo $this->form->numnotaavaliador ?></td>
                                </tr>
                                <tr>
                                    <td colspan="6"> * Não foi possível avaliar</td>
                                </tr>
                                </tbody>
                            </table>
                            <div class="span4"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span8">
                            <?php echo $this->form->desdestaqueservidor; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span6">
                            <?php echo $this->form->desobs; ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="span5">
                            <?php echo $this->form->submit; ?>
                            <?php echo $this->form->voltar; ?>
                        </div>
                    </div>
                    <?php echo $this->form->ideventoavaliacao; ?>
                    <?php echo $this->form->idavaliador; ?>
                    <div class="row">
                        <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                            (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                            obrigatório
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


