<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'));

$frmAttr = $this->form->getAttribs();
?>

<div class="content">
    <form id="form-avaliacao-editar"
          name="form-avaliacao-editar"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">
        <div class="row" style="padding: 10px 0;">
            <div class="span3">
                <strong>Avaliador:</strong> <?php echo $this->dadosBanco['nomavaliador']; ?>
            </div>
            <div class="span2">
                <strong>Data avalia&ccedil;&atilde;o:</strong> <?php echo $this->dadosBanco['datcadastro']; ?>
            </div>
            <div class="span2">
                <strong>Avalia&ccedil;&atilde;o
                    T&eacute;cnica:</strong> <?php echo number_format($this->dadosBanco['nummedia'], 2); ?>
                (<?php echo $this->dadosBanco['numtotalavaliado'] ?>)
            </div>
            <div class="span1_5">
                <strong>Avalia&ccedil;&atilde;o Pessoal:</strong> <?php echo $this->dadosBanco['numnotaavaliador']; ?>
            </div>
            <div class="span1_5">
                <strong>M&eacute;dia Final:</strong> <?php echo number_format($this->dadosBanco['nummediafinal'], 2); ?>
            </div>
        </div>
        <div class="row">
            <div class="span5">
                <?php echo $this->form->idevento; ?>
            </div>
            <div class="span4 container-pessoa">
                <div class="control-group">
                    <?php echo $this->form->nomavaliado->renderLabel(); ?>
                    <div class="input-prepend ">
                        <?php echo $this->form->pessoabutton; ?>
                        <?php echo $this->form->nomavaliado->renderViewHelper(); ?>
                        <?php echo $this->form->idavaliado; ?>
                    </div>
                </div>
            </div>
            <div class="span4">
                <?php echo $this->form->idtipoavaliacao; ?>
            </div>
        </div>
        <div class="row grid-append" style="display: none;">
        </div>
        <div class="row">
            <div class="span10">
                <table class="table table-hover table-striped table-condensed" style="padding: 5px; margin: 15px 0px;">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Sempre</th>
                        <th>Frequentemente</th>
                        <th>Raramente</th>
                        <th>Nunca</th>
                        <th style="color: #ff0000;">*Prejudicado</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->perguntas as $key => $pergunta): ?>
                        <tr>
                            <td style="padding: 0px 15px;"> <?php echo $pergunta; ?> </td>
                            <td style="text-align: center;"><input type="radio" name="<?php echo $key ?>"
                                                                   value="10" <?php echo ($this->dadosBanco[$key] == '10') ? "checked='checked'" : ""; ?>/>
                            </td>
                            <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                  value="8" <?php echo ($this->dadosBanco[$key] == '8') ? "checked='checked'" : ""; ?>/>
                            </td>
                            <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                  value="2" <?php echo ($this->dadosBanco[$key] == '2') ? "checked='checked'" : ""; ?>/>
                            </td>
                            <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                  value="0" <?php echo ($this->dadosBanco[$key] == '0') ? "checked='checked'" : ""; ?>/>
                            </td>
                            <td style="text-align: center"><input type="radio" name="<?php echo $key ?>"
                                                                  value="-1" <?php echo ($this->dadosBanco[$key] == '-1') ? "checked='checked'" : ""; ?>/>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td colspan="6"><?php echo $this->form->numnotaavaliador ?></td>
                    </tr>
                    <tr>
                        <td colspan="6" style="color: #ff0000;"> * Não foi poss&iacute;vel avaliar</td>
                    </tr>
                    </tbody>
                </table>
                <div class="span4"></div>

            </div>
        </div>
        <div class="row">
            <div class="span8">
                <?php echo $this->form->desdestaqueservidor; ?>
            </div>
        </div>
        <div class="row">
            <div class="span6">
                <?php echo $this->form->desobs; ?>
            </div>
        </div>


        <?php echo $this->form->ideventoavaliacao; ?>
        <?php echo $this->form->idavaliador; ?>
        <div class="row">
            <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
            </div>
        </div>
    </form>
</div>
