<?php

$this->headLink()
    // ->appendStylesheet($this->baseUrl('/js/jquery.jqGrid-4.4.0/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.default.css'))
    ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/icons/jquery.pnotify.default.icons.css'))
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/default/log/in.js?1'), 'text/javascript');
?>
<div class="row">
    <div class="portlet portlet-marron span4">
        <div class="title">Login</div>
        <div class="content">
            <?php echo $this->form; ?>
        </div>
    </div>
    <div class="span8">
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
        fj sdflçasdj flaskdjf lçasdkjf lasçdkfj aslkdjf aslçdk fjasdlkfjaslçdjk
    </div>
</div>