<?php
$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");
?>
<head>
    <style>
        .break {
            page-break-before: always;
        }

        @page Section1 {

            size: 1200;
        }

        div.Section1 {

            page: Section1;
        }

        p {
            border-width: medium;
            border-style: solid;
            border-color: #CCCCCC;
            line-height: 1;
            text-indent: 0;
            margin: 3px;
        }

        .container-grupo {
            width: 1500px;
            border: 1px solid red;
        }

        .titulo-tabela {
            font-weight: bold;
        }

        .box-grupo {
            padding-top: 5px;
            float: left;
            margin-bottom: 20px;
        }

        .box-nome-grupo {
            font-size: 12px;
            font-weight: bold;
            padding: 3px;
            text-align: center;
            border: 2px solid #555;
            background: #aaa;
        }

        .box-entrega {
            margin: 8px 0;
        }

        .box-item-entrega {
            font-size: 10px;
            border: 1px solid #fff;
            margin: 5px 0;
            background: #ccc;
            padding: 3px;
        }

        div#estAnalitic {
            font: 12px Arial, Sans-serif;
            vertical-align: middle;
            background-color: #CCCCCC;
        }

        span#tagEspan {
            font-weight: bold;
            text-shadow: 0 0 0.2em #87F 0 0 0.2em #87F, 0 0 0.2em #87F;
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
            border-radius: 50%;
            display: inline-block;
            height: 100px;
            width: 100px;
            color: #fff;
        }

    </style>
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<div class="Section1" style="font-size: 8px;">
    <table align="center" border="0" width="70%" height="90%"
           style="font-size:8.0pt;mso-bidi-font-size: 10.0pt;font-family:Arial;">
        <tr align="center">
            <td style="text-align:center;padding-bottom:20px;">
                <h5>1. TERMO DE ENCERRAMENTO</h5>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;">
                <h5>1.1 PROJETO</h5>
            </td>
        </tr>
        <tr align="left">
            <!--<td style="text-align:left;padding-bottom: 20px;">-->
            <!--<h5>Resumo do projeto conforme último relatório</h5>-->
            <!--</td>-->
        </tr>
        <tr align="left" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table border="1" class="table table-striped table-bordered table-price"
                       style="font-size: 8px !important;">
                    <colgroup>
                        <col style="width: 250px;">
                        <col style="width: 650px;">
                    </colgroup>
                    <tr>
                        <th valign="top" align="left"><b>C&Oacute;DIGO&nbsp;DO&nbsp;PROJETO&nbsp;</b></th>
                        <td><?php echo utf8_decode($this->projeto->nomcodigo); ?></td>
                    </tr>
                    <tr>
                        <th valign="top" align="left"><b>T&Iacute;TULO&nbsp;DO&nbsp;PROJETO</b></th>
                        <td><?php echo $this->projeto->nomprojeto; ?></td>
                    </tr>
                    <tr>
                        <th valign="top" align="left"><b>PATROCINADOR</b></th>
                        <td><?php echo $this->projeto->nompatrocinador; ?></td>
                    </tr>
                    <tr>
                        <th valign="top" align="left"><b>GERENTE&nbsp;DO&nbsp;PROJETO</b></th>
                        <td><?php echo $this->projeto->nomgerenteprojeto; ?></td>
                    </tr>
                    <tr>
                        <th valign="top" align="left"><b>GERENTE&nbsp;ADJUNTO</b></th>
                        <td><?php echo $this->projeto->nomgerenteadjunto; ?></td>
                    </tr>
                    <tr>
                        <th valign="top" align="left"><b>OBJETIVO</b></th>
                        <td><?php echo $this->projeto->desobjetivo; ?></td>
                    </tr>
                    <tr>
                        <th valign="top" align="left"><b>OBJETO</b></th>
                        <td><?php echo $this->projeto->desprojeto; ?></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;">
                <h5>1.2 LIÇÕES APRENDIDAS</h5>
            </td>
        </tr>

        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table style="width: 100%;border-collapse: collapse;" border="1" cellpadding="1" cellspacing="1">
                    <colgroup>
                        <col style="width: 20%">
                        <col style="width: 20%">
                        <col style="width: 20%">
                        <col style="width: 20%">
                        <col style="width: 20%">
                    </colgroup>
                    <thead>
                    <tr class="" style="border:0.1mm solid #220044; background-clip: border-box;">
                        <td><b>ENTREGA</b></td>
                        <td><b>RESULTADOS&nbsp;OBTIDOS</b></td>
                        <td><b>PONTOS&nbsp;FORTES</b></td>
                        <td><b>PONTOS&nbsp;FRACOS&nbsp;/ DIFICULTADES&nbsp;ENCONTRADAS</b></td>
                        <td><b>SUGEST&Otilde;ES&nbsp;PARA&nbsp;UM PROJETO&nbsp;SEMELHANTE</b></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->licao as $licao):
                        if (empty($licao['nomatividadecronograma']) == false): ?>
                            ?>
                            <tr valign="top">
                                <td><?php echo $licao['nomatividadecronograma']; ?></td>
                                <td><?php echo $licao['desresultadosobtidos']; ?></td>
                                <td><?php echo $licao['despontosfortes']; ?></td>
                                <td><?php echo $licao['despontosfracos']; ?></td>
                                <td><?php echo $licao['dessugestoes']; ?></td>
                            </tr>
                        <?php
                        endif;
                    endforeach;
                    if (empty($licao['nomatividadecronograma']) == true):
                        ?>
                        <tr>
                            <td colspan="5">Nenhum registro encontrado.</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;">
                <h5>1.3 CONSIDERA&Ccedil;&Otilde;ES FINAIS</h5>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;padding-left: 20px;">
                <?php echo $this->projeto->desconsideracaofinal; ?>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;">
                <h5>2 ASSINATURAS</h5>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:left;padding-bottom:20px;padding-left: 20px;">
                <div align="left" style="margin-top: 10px">
                    <table class="span10" border="1" WIDTH='100%'>
                        <colgroup>
                            <col style="width: 650px">
                            <col style="width: 250px">
                        </colgroup>
                        <tbody style="text-align: center">
                        <tr style="vertical-align: bottom">
                            <td><?php echo $this->projeto->nompatrocinador; ?></td>
                            <td>____________________________________________________________</td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td><b>Patrocinador</b></td>
                            <td><b>Assinatura</b></td>
                        </tr>
                        </tbody>

                        <tbody style="text-align: center;">
                        <tr style="vertical-align: bottom">
                            <td><?php echo $this->projeto->nomgerenteprojeto; ?></td>
                            <td>____________________________________________________________</td>
                        </tr>
                        <tr style="vertical-align: top">
                            <td><b>Gerente&nbsp;de&nbsp;Projeto</b></td>
                            <td><b>Assinatura</b></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</div>
