<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/diagnostico/sugestaomelhoria/listar.js'), 'text/javascript');

$frmAttr = $this->formPesquisar->getAttribs();
?>
<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml',
        array('ativo' => 'sugestaomelhoria', 'iddiagnostico' => $this->iddiagnostico));
    ?>
</div>
<div class="region-center">
    <h4 class="pagination-centered">Sugestão de Melhorias</h4>
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a data-target="#dialog-inserir" class="btn actionfrm inserir" title="Cadastrar"
               data-id="<?php echo $this->iddiagnostico ?>" href="<?php echo $this->url(array(
                'module' => 'diagnostico',
                'controller' => 'sugestaomelhoria',
                'action' => 'cadastrar'
            )) ?>">
                Cadastrar
            </a>
        </div>
    </div>

    <table id="list-grid-sugestaomelhoria"></table>
    <div id="toolbar-grid-sugestaomelhoria"></div>
    <div id="pager-grid-sugestaomelhoria"></div>
</div>

<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Sugestão de Melhorias - Pesquisar</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->formPesquisar->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <input type="hidden" id="iddiagnostico" name='iddiagnostico'
                               value="<?php echo $this->iddiagnostico ?>"/>
                        <div class="span3">
                            <?php echo $this->formPesquisar->datmelhoria ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->idmacroprocessotrabalho ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->idmacroprocessomelhorar ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formPesquisar->btnpesquisar ?>
                                <?php echo $this->formPesquisar->reset ?>
                                <?php echo $this->formPesquisar->close ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="dialog-editar" style="display: none"></div>
<!--<div id="dialog-excluir" style="display: none"></div>-->
<div id="dialog-detalhar" style="display: none"></div>
<div id="dialog-inserir" style="display: none"></div>
<div id="dialog" title="Confirmação Requerida" style="display: none">
    <!--    <p>Tem certeza que deseja excluir o diagnóstico? </p>-->
</div>​