<style>
    .help-inline {
        display: block;
    }

    #conteudo > .error {
        display: none;
    }
</style>
<div id="login" class="">
    <div class="bem-vindo"><h3>Esqueci a Senha</h3></div>
    <div id="formulario">
        <?php if ($this->message): ?>
            <div class="row-fluid">
                <div class="span alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong><?php echo $this->message; ?></strong>
                </div>
            </div>
        <?php endif; ?>
        <?php
        echo $this->form
        ?>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('button.close').on('click', function () {
            $(this).parents('.row-fluid').remove();
        });
    });
</script>