<style type="text/css">
    
    .error {
        font-size: 18px;
        font-weight: bold;
        color: #cd7f32;
        margin-left: 40%;
        padding-top: 5px;
        width: 20%;
        text-align: center;
        text-shadow: 0 2px 2px #ccc;
    } 
    
</style>

<div id="login" class="">
    <div class="bem-vindo"><h3>Bem vindo ao sistema</h3></div>
    <div id="formulario">
     <?php
        echo $this->form 
      ?>
    </div>
</div>