<style type="text/css">

    .error {
        font-size: 18px;
        font-weight: bold;
        color: #b94a48;
        margin-left: 40%;
        padding-top: 5px;
        width: 20%;
        text-align: center;
        text-shadow: 0 2px 2px #ccc;
    }

    form {
        margin-bottom: 10px;
    }

    form + a {
        display: block;
        margin-bottom: 10px;
    }

</style>

<div id="login" class="">
    <div class="bem-vindo"><h3>Bem vindo ao sistema</h3></div>
    <div id="formulario">
        <?php
        echo $this->form
        ?>
    </div>
</div>