<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
;

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/default/index/perfil.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();
?>
<div class="portlet portlet-marron span12">
    <div class="title">Selecione um perfil</div>
    <div class="content">
        <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
            <div class="span3">
                <?php echo $this->form->idperfil; ?>
            </div>
            <div class="span2 actions-pesquisar">
                <?php echo $this->form->submit; ?>
            </div>
        </form>
    </div>
</div>