<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.3.2/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/agenda/fullcalendar.css'))
    ->appendStylesheet($this->baseUrl('/css/glyphicons/glyphicons.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.3.2/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.3.2/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/agenda/index/fullcalendar.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/app/agenda/index/index.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/agenda/index/participantes.js'), 'text/javascript');


//$frmAttr = $this->form->getAttribs();
?>
<div class="region-west">
    <div class="span3">
        <div class="form-actions form-actions-mini">
            <div class="btn-group">
                <a style="display: none" id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
                <a data-target="#dialog-incluir" class="btn incluir" id="incluir" name="incluir"
                   href="<?php echo $this->baseUrl('/agenda/index/add') ?>">Cadastrar novo agendamento</a>
            </div>
        </div>
        <div id="calendar"></div>
    </div>
</div>
<div class="region-center">
    <!-- <div class="portlet">
         <div class="row-fluid">
             <div class="portlet portlet-marron span9">-->
    <div class="title" id="display-data" data-value-field="<?php echo $this->hoje->format('d/m/Y') ?>">Agenda
        de <?php echo $this->hoje->format('d/m/Y') ?></div>
    <table id="list2" class=""></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>
    <!--        </div>
        </div>
    </div>-->
    <!--<div class="portlet portlet-marron span10">

    </div>-->

</div>

<div id="dialog-incluir" style="display: none"></div>
<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>
<div id="dialog-participantes" style="display: none"></div>
<div id="dialog-email" style="display: none"></div>
