<?php

$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");

$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/css/app/planejamento/portfolio.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.formatCurrency.js'))
    //->appendFile($this->baseUrl('/js/app/projeto/tap/add.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/tap/add.js?' . time()), 'text/javascript');
$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <?php echo $this->partial('_partials/tap-menu.phtml', array('dados' => 'informacoesiniciais')); ?>
    <div class="portlet portlet-marron span12" style="width:98%">
        <h3>Informações</h3>
        <div class="content" style="width:90%">
            <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <input type="hidden" name="feriadosfixos" id="feriadosfixos"
                       value="<?php echo @$this->feriadosfixos; ?>">
                <input type="hidden" name="ano" id="ano" value="<?php echo @date("Y"); ?>">
                <fieldset>
                    <legend>
                        <div>
                            <div style="float:left">Iniciais</div>
                            <div style="float:right; font-size: 10px;">
                                <a href="#" id="portifolio">Visualizar Portifólio</a>
                            </div>
                        </div>
                    </legend>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->nomcodigo; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->nomprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->numprocessosei; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->idprograma; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->vlrorcamentodisponivel; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idobjetivo; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->idacao; ?>
                        </div>
                    </div>
                    <div class="row container-pessoa">
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nomdemandante->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->nomdemandante->renderViewHelper(); ?>
                                    <?php echo $this->form->iddemandante; ?>
                                </div>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nompatrocinador->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idpatrocinador; ?>
                                    <?php echo $this->form->nompatrocinador->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nomgerenteprojeto->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idgerenteprojeto; ?>
                                    <?php echo $this->form->nomgerenteprojeto->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span">
                            <div class="control-group">
                                <?php echo $this->form->nomgerenteadjunto->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idgerenteadjunto; ?>
                                    <?php echo $this->form->nomgerenteadjunto->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row grid-append" style="display: none;">
                    </div>
                    <div class="row" style="position: relative; border-width:2px; height: 100px;">
                        <div class="span3">
                            <?php echo $this->form->datinicio; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datfim; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datinicioplano; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->datfimplano; ?>
                        </div>
                        <div id="msgError" class="error" style='display: none; width: 76%; padding-left: 45%; margin-left:-40px; position:relative; 
                            margin-top: 20px; color: red; font-size:10px;'>
                            <p align="justify">Data fim do plano de projeto maior que a <br/> data de fim do projeto.
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->idnatureza; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idsetor; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idescritorio; ?>
                        </div>
                        <div class="span3"></div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Outras</legend>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->numperiodicidadeatualizacao; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->numcriteriofarol; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flapublicado; ?>
                        </div>
                        <div class="span2" style="display:none">
                            <?php echo $this->form->flaaprovado; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span5">
                            <?php echo $this->form->idprojeto; ?>
                            <?php echo $this->form->submit; ?>
                            <?php echo $this->form->reset; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                            (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                            obrigatório
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

<!-- Modal Portifólio-->
<div id="modal-portifolio" title="Portifólio Estratégico" style="display:none">
    <h5> PORTIFÓLIO ESTRATÉGICO DA ORGANIZAÇÃO - <?php echo $this->escritorio->sigla; ?></h5>
    <div class="content relatorioIndex" style="overflow-x: auto; overflow-y: auto; height: 380px;">
        <?php $contAcao = 0;
        foreach ($this->portfolio as $obj): ?>
            <div class="span2 box-objetivo" id="<?php echo $obj['idobjetivo'] ?>">

                <div class="box-nome-objetivo">
                    <?php if ($obj['totalProjetos'] != 0): ?>
                        <form id='form-pesquisar_<?php echo $obj["idobjetivo"]; ?>' name="form-pesquisar"
                              action="<?php echo $this->baseUrl(); ?>/projeto/statusreport" method="post">
                            <input type="hidden" name="nomprojeto" id="nomprojeto" value="" data-rule-required=""
                                   class="">
                            <input type="hidden" name="codacao" id="codacao" class=""/>
                            <input type="hidden" name="codnatureza" id="codnatureza" class=""/>
                            <input type="hidden" name="codsetor" id="codsetor" class=""/>
                            <input type="hidden" name="domstatusprojeto" id="domstatusprojeto" class=""/>
                            <input type="hidden" name="postite" id="postite" value="1"/>
                            <input type="hidden" name="codobjetivo" id="codobjetivo" class=""
                                   value="<?php echo $obj['idobjetivo'] ?>"/>
                            <span style="margin: 0; padding-top: 5px;"><?php echo $obj['nomobjetivo'] ?></span> <br/>
                            <span style="font-weight: bold;"> (<?php echo $obj['totalProjetos'] ?>) </span>
                        </form>
                    <?php else: ?>
                        <span style="margin: 0; padding-top: 5px;"><?php echo $obj['nomobjetivo'] ?></span> <br/>
                        <span style="font-weight: bold;"> (<?php echo $obj['totalProjetos'] ?>) </span>
                    <?php endif; ?>
                </div>

                <div class="box-acao">
                    <ul>
                        <?php if (count($obj['acoes']) > 1):
                            foreach ($obj['acoes'] as $acao): ?>
                                <li class="content item-acao" id="<?php echo $acao['idacao'] ?>">
                                    <?php if ($acao['totalProjetos'] != 0): ?>
                                        <form id='form-pesquisar_<?php echo $acao['idacao'] ?>' name="form-pesquisar"
                                              action="<?php echo $this->baseUrl(); ?>/projeto/statusreport"
                                              method="post">
                                            <input type="hidden" name="nomprojeto" id="nomprojeto" value=""
                                                   data-rule-required="" class="">
                                            <input type="hidden" name="codacao" id="codacao" class=""
                                                   value="<?php echo $acao['idacao'] ?>"/>
                                            <input type="hidden" name="codnatureza" id="codnatureza" class=""/>
                                            <input type="hidden" name="codsetor" id="codsetor" class=""/>
                                            <input type="hidden" name="domstatusprojeto" id="domstatusprojeto"
                                                   class=""/>
                                            <input type="hidden" name="postite" id="postite" value="1"/>
                                            <input type="hidden" name="codobjetivo" id="codobjetivo" class=""
                                                   value="<?php echo $obj['idobjetivo'] ?>"/>
                                            <span style="margin: 0; padding-top: 5px;"><?php echo $acao['nomacao'] ?></span>
                                            <br/>
                                            <span style="font-weight: bold;"> (<?php echo $acao['totalProjetos'] ?>) </span>
                                        </form>
                                    <?php else: ?>
                                        <span> <?php echo $acao['nomacao'] ?> </span> <br/>
                                        <span style="font-weight: bold;"> (<?php echo $acao['totalProjetos'] ?>)</span>
                                    <?php endif; ?>
                                </li>
                                <?php $contAcao++;
                            endforeach;
                        endif; ?>
                    </ul>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="" style="align:center; justify-content: center;">
        <div class="portlet portlet-cinza span9">
            <div class="title">
                Total de Objetivos: <?php echo count($this->portfolio); ?> <br/>
                Total de Ações: <?php echo $contAcao; ?>
            </div>
        </div>
    </div>
</div>

