<div id="cabecalho">
    <div class="span9">
        <div align='left' style="float:left">
            <img src="<?php echo $this->baseUrl('/img/brasao_fundobranco.png'); ?>"/>
        </div>
        <div class="span6" style="float: left; margin-top: 10px">
            MINISTÉRIO DA JUSTIÇA
            <HR>
        </div>
    </div>
</div>
<div id="content">
    <div align="center" style="margin-top: 170px">
        TERMO DE ABERTURA
    </div>
    <div align="center" style="margin-top: 40px">
        <?php echo $this->processo->nomcodigo; ?>
    </div>
    <div align="center" style="margin-top: 40px">
        <?php echo $this->processo->nomprojeto; ?>
    </div>
    <div align="center" style="margin-top: 40px">
        <?php echo $this->processo->desprojeto; ?>
    </div>
    <div align="left" class="span4" style="margin-top: 60px">
        <h3>1.1 INFORMAÇÕES INICIAIS</h3>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td>CÓDIGO DO PROJETO</td>
                <td><?php echo $this->processo->nomcodigo; ?></td>
            </tr>
            <tr>
                <td>TÍTULO DO PROJETO</td>
                <td><?php echo $this->processo->nomprojeto; ?></td>
            </tr>
            <tr>
                <td>PROGRAMA</td>
                <td><?php echo $this->processo->programa["nomprograma"]; ?></td>
            </tr>
            <tr>
                <td>ALINHAMENTO ESTRATÉGICO</td>
                <td><?php echo $this->processo->objetivo["nomobjetivo"]; ?></td>
            </tr>
            <tr>
                <td>NATUREZA</td>
                <td><?php echo $this->processo->natureza["nomnatureza"]; ?></td>
            </tr>
            <tr>
                <td>ÁREA EXECUTORA</td>
                <td><?php echo $this->processo->setor["nomsetor"]; ?></td>
            </tr>
            <tr>
                <td>PATROCINADOR</td>
                <td><?php echo $this->processo->nompatrocinador; ?></td>
            </tr>
            <tr>
                <td>PROPONENTE</td>
                <td><?php echo $this->processo->nomproponente; ?></td>
            </tr>
            <tr>
                <td>ESCRITORIO REPONSÁVEL</td>
                <td><?php echo $this->processo->escritorio->sigla; ?></td>
            </tr>
            <tr>
                <td>GERENTE DE PROJETO</td>
                <td><?php echo $this->processo->nomgerenteprojeto; ?></td>
            </tr>
            <tr>
                <td>GERENTE ADJUNTO</td>
                <td><?php echo $this->processo->nomgerenteadjunto; ?></td>
            </tr>
            <tr>
                <td>ORÇAMENTO PREVISTO</td>
                <td><?php echo $this->processo->vlrorcamentodisponivel; ?></td>
            </tr>
            <tr>
                <td>PRAZO PREVISTO PARA PROJETO</td>
                <td> De: <?php echo $this->processo->datinicioplano ?>
                    Até: <?php echo $this->processo->datfimplano ?></td>
            </tr>
            <tr>
                <td>PRAZO PARA DESENVOLVIMENTO DO PLANO DO PROJETO</td>
                <td> De: <?php echo $this->processo->datinicio ?> Até: <?php echo $this->processo->datfim ?></td>
            </tr>
            <tr>
                <td>Nº DO PROCESSO</td>
                <td> <?php echo $this->processo->numprocessosei ?></td>
            </tr>
            </tbody>
        </table>

        <div align="left" class="span5" style="margin-top: 60px">
            <h3>1.2 INFORMAÇÕES TÉCNICAS</h3>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                <tr>
                    <td>JUSTIFICATIVA DO PROJETO</td>
                    <td><?php echo $this->processo->desjustificativa; ?></td>
                </tr>
                <tr>
                    <td>OBJETO DO PROJETO (O QUE SERÁ FEITO?)</td>
                    <td><?php echo $this->processo->desprojeto; ?></td>
                </tr>
                <tr>
                    <td>OBJETIVO DO PROJETO (PARA QUE SERÁ FEITO?)</td>
                    <td><?php echo $this->processo->desobjetivo; ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px">
            <h3>1.3 RESUMO DO PROJETO</h3>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                <tr>
                    <td>ESCOPO RESUMIDO (PRINCIPAIS ENTREGAS)</td>
                    <td><?php echo $this->processo->desescopo; ?></td>
                </tr>
                <tr>
                    <td>NÃO ESCOPO (O QUE NÃO SERÁ FEITO?)</td>
                    <td><?php echo $this->processo->desnaoescopo; ?></td>
                </tr>
                <tr>
                    <td>PREMISSAS</td>
                    <td><?php echo $this->processo->despremissa; ?></td>
                </tr>
                <tr>
                    <td>RESTRIÇÕES</td>
                    <td><?php echo $this->processo->desrestricao; ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px">
            <h3>1.4 PARTES INTERESSADAS</h3>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 35px">
                    <col style="width: 25px">
                    <col style="width: 40px">
                    <col style="width: 15px">
                </colgroup>
                <thead>
                <th>Nome</th>
                <th>Função</th>
                <th>Telefone</th>
                <th>Email</th>
                <th>Nível Influência</th>
                </thead>
                <tbody>
                <?php if (count($this->processo->partes) > 0): ?>
                    <?php foreach ($this->processo->partes->getIterator() as $parte): ?>
                        <tr>
                            <td><?php echo $parte->nomparteinteressada; ?></td>
                            <td><?php echo $parte->nomfuncao; ?></td>
                            <td><?php echo $parte->destelefone; ?></td>
                            <td><?php echo $parte->desemail; ?></td>
                            <td><?php echo $parte->domnivelinfluencia; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5">Partes Interessadas não cadastradas no sistema.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px">
            <h3>1.5 DEMAIS INFORMAÇÕES</h3>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                <tr>
                    <td>TIPO DE PROJETO</td>
                    <td><?php echo $this->processo->domtipoprojeto; ?></td>
                </tr>
                <tr>
                    <td>PROJETO DA COPA</td>
                    <td><?php echo $this->processo->flacopa; ?></td>
                </tr>
                <tr>
                    <td>PERIODICIDADE DE ATUALIZAÇÃO (DIAS)</td>
                    <td><?php echo $this->processo->numperiodicidadeatualizacao; ?></td>
                </tr>
                <tr>
                    <td>CRITÉRIO DO FAROL (DIAS)</td>
                    <td><?php echo $this->processo->numcriteriofarol; ?></td>
                </tr>
                <tr>
                    <td>PUBLICAR NA TELA MESTRA</td>
                    <td><?php echo $this->processo->flapublicado; ?></td>
                </tr>
                <!--<tr>
                        <td>PROJETO DO PORTIFÓLIO PF</td>
                        <td><?php // echo $this->processo->desrestricao; ?></td>
                    </tr>-->
                <tr>
                    <td>APROVADO</td>
                    <td><?php echo $this->processo->desrestricao; ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px;margin-bottom: 40px">
            <h3>1.6 APROVAÇÃO DO PATROCINADOR</h3>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="span10">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->processo->nompatrocinador; ?></td>
                    <td>____________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Patrocinador</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprovação</b></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px;margin-bottom: 40px">
            <h3>1.7 CIÊNCIA DO GERENTE DE PROJETO</h3>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="span10">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->processo->nomgerenteprojeto; ?></td>
                    <td>____________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Patrocinador</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprovação</b></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>


