<?php
$this->headLink()
        ->appendStylesheet($this->baseUrl('/css/form.css'))
        ->appendStylesheet($this->baseUrl('/css/portlet.css'))
        ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
        ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
        
        
        
;

$this->headScript()
        ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
        ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/app/projeto/tap/index.js'), 'text/javascript')
        
        // Chamada para personalizar o title dos botões.
//    ->appendFile($this->baseUrl('/js/library/handlebars.js'), 'text/javascript')
//    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/intervalo.js'), 'text/javascript')
//    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/index.js'), 'text/javascript')
//    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/cronograma.js'), 'text/javascript')
//        
;
;

?>

<div class="region-west" >
    <?php
    echo $this->partial('_partials/menu-projeto.phtml', array('ativo' => 'abertura', 'idprojeto' => $this->projeto->idprojeto));
    ?>
</div>
<div class="region-center" >
    <?php echo $this->partial('_partials/projeto.phtml', array('projeto' => $this->objprojeto)); ?>
    
    <!-- Imprime o termo de abertura e o plano de gerenciamento do projeto -->
    <div class="btn-toolbar" align="" style="width: 350px; float: right;">
        <a class="btn btn-cadastrar-grupo" title="Imprimir TERMO DE ABERTURA DE PROJETO (TAP)" target="_blank" href="<?php echo $this->url(
            array('module' => 'projeto', 'controller' => 'tap', 'action' => 'imprimir','idprojeto' => $this->projeto->idprojeto, 'matricula' => $this->matricula)); ?>">
            <i class="icon-print"></i>
        </a>
        <a class="btn btn-cadastrar-grupo" title="Imprimir PLANO DE PROJETO" target="_blank" href="<?php echo $this->url(
            array('module' => 'projeto', 'controller' => 'planoprojeto', 'action' => 'imprimir','idprojeto' => $this->projeto->idprojeto, 'matricula' => $this->matricula)); ?>">
            <i class="icon-print"></i>
        </a>
    </div>
    
    <!-- Informacoes Iniciais -->
    <div id="ii" class="informacoes" style="display: block">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'informacoesiniciais')); ?>
        <fieldset>
            <legend>Informações Iniciais</legend>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Código</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomcodigo; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span6">
                    <h3>Título do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomprojeto; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Programa</h3>
                    <div class="content">
                        <?php echo $this->projeto->programa; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Orçamento Previsto</h3>
                    <div class="content">
                        <?php echo $this->projeto->getVlrorcamentodisponivelFormatado(); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Objetivo Institucional</h3>
                    <div class="content">
                        <?php echo $this->projeto->objetivo; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Ação Estratégica</h3>
                    <div class="content">
                        <?php echo $this->acao; ?>
                    </div>
                </div>
              
            </div>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Demandante</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomdemandante; ?>
                       
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Patrocinador</h3>
                    <div class="content">
                        <?php echo $this->projeto->nompatrocinador; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Gerente do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomgerenteprojeto; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Gerente Adjunto</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomgerenteadjunto; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Início do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datinicio->toString('d/m/Y'); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Fim do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datfim->toString('d/m/Y'); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Início do Plano Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datinicioplano->toString('d/m/Y'); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Fim do Plano Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datfimplano->toString('d/m/Y'); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Natureza</h3>
                    <div class="content">
                        <?php echo $this->projeto->natureza; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Área Executora</h3>
                    <div class="content">
                        <?php echo $this->projeto->setor; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Escritório Responsável</h3>
                    <div class="content">
                        <?php echo $this->nomeEscritorio; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Ano</h3>
                    <div class="content">
                        <?php echo $this->projeto->ano; ?>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>Demais Informações</legend>
            <div class="row">
                <div class="portlet portlet-verde span4">
                    <h3>Portf&oacute;lio do Projeto</h3>
                    <div class="content">
                        <?php echo $this->noPortifolio ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span4">
                    <h3>Tipo do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->domtipoprojeto ?>
                    </div>
                </div>

                <div class="portlet portlet-verde span3">
                    <h3>Grandes Eventos</h3>
                    <div class="content">
                        <?php echo $this->projeto->copa; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Periodicidade de Atualização(Dias)</h3>
                    <div class="content">
                        <?php echo $this->projeto->numperiodicidadeatualizacao; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span4">
                    <h3>Critério Farol Prazo(Dias)</h3>
                    <div class="content">
                        <?php echo $this->projeto->numcriteriofarol; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span4">
                    <h3>Publicar Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->publicado; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Aprovado?(TAP assinado)</h3>
                    <div class="content">
                        <?php echo $this->projeto->aprovado; ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>

    <!-- Informacoes Tecnicas -->
    <div id="it" class="informacoes" style="display: none">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'informacoestecnicas')); ?>
        <fieldset>
            <legend>Informações Técnicas</legend>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Justificativa do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->desjustificativa; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Objeto do Projeto (O que será feito?)</h3>
                    <div class="content">
                        <?php echo $this->projeto->desprojeto; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Objetivo do Projeto (Por que será feito?)</h3>
                    <div class="content">
                        <?php echo $this->projeto->desobjetivo; ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>

    <!-- Resumo do Projeto -->
    <div id="rp" class="informacoes" style="display: none">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'resumodoprojeto')); ?>
        <fieldset>
            <legend>Resumo do Projeto</legend>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Escopo Resumido (Principais Entregas)</h3>
                    <div class="content">
                        <?php echo $this->projeto->desescopo; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Não Escopo (O que não será feito?)</h3>
                    <div class="content">
                        <?php echo $this->projeto->desnaoescopo; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Premissas</h3>
                    <div class="content">
                        <?php echo $this->projeto->despremissa; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Restrições</h3>
                    <div class="content">
                        <?php echo $this->projeto->desrestricao; ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>

    <!-- Partes Interessadas -->
    <div id="pi" class="informacoes" style="display: none">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'partesinteressadas')); ?>
        <fieldset>
            <legend>Partes Interessadas</legend>
            <div class="row">
                <table class="table table-bordered table-hover table-striped span10">
                    <colgroup>
                        <col style="width: 100px">
                        <col style="width: 100px">
                        <col style="width: 50px">
                        <col style="width: 50px">
                        <col style="width: 50px">
                    </colgroup>
                    <thead>
                    <th>Nome</th>
                    <th>Função</th>
                    <th>Telefone</th>
                    <th>Email</th>
                    <th>Nível Influência</th>
                    </thead>
                    <tbody>
                        <?php if (count($this->dados) > 0): ?>
                            <?php foreach ($this->dados as $data) : ?>
                                <tr>
                                    <td>
                                        <?php echo $data->nomparteinteressada; ?>
                                    </td>
                                    <td>
                                        <?php echo $data->nomfuncao; ?>
                                    </td>
                                    <td>
                                        <?php echo $data->destelefone; ?>
                                    </td>
                                    <td>
                                        <?php echo $data->desemail; ?>
                                    </td>
                                    <td>
                                        <?php echo $data->domnivelinfluencia; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr id="nenhumregistro">
                                <td  colspan="6">Nenhum registro encontrado</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>


