<?php

$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");

$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/tap/assinatura.css?' . time()))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/termoaceite/index.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/tap/index.js?' . time()), 'text/javascript');

$frmAttr = $this->formAssinatura->getAttribs();
?>

<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml',
        array('ativo' => 'abertura', 'idprojeto' => $this->projeto->idprojeto));
    ?>
</div>
<div class="region-center" id="barrafer">
    <?php echo $this->partial('_partials/projeto.phtml', array('projeto' => $this->objprojeto)); ?>

    <!-- Imprime o termo de abertura e o plano de gerenciamento do projeto href="<?php //echo $this->url(
    //array('module' => 'projeto', 'controller' => 'tap', 'action' => 'autenticarassinatura','idprojeto' => $this->projeto->idprojeto)); ?>"-->
    <div class="btn-toolbar" align="" style="width: 350px; float: right;">       
        <?php if ($this->projeto->domstatusprojeto == 8): ?>
            <a class="btn actionfrm  <?php echo $this->projeto->domstatusprojeto == 8 ? 'restaurarprojeto' : 'excluirprojeto'; ?>"
               title="<?php echo $this->projeto->domstatusprojeto == 8 ? 'Recuperar' : 'Excluir' ?> Projeto"
               id="<?php echo($this->projeto->domstatusprojeto == 8 ? 'restaurar' : 'excluir'); ?>"
               href="<?php echo($this->projeto->domstatusprojeto == 8 ?
                   $this->url(array(
                       'module' => 'projeto',
                       'controller' => 'gerencia',
                       'action' => 'restaurarprojeto',
                       'idprojeto' => $this->projeto->idprojeto,
                       'matricula' => $this->matricula
                   )) :
                   $this->url(array(
                       'module' => 'projeto',
                       'controller' => 'gerencia',
                       'action' => 'excluirprojeto',
                       'idprojeto' => $this->projeto->idprojeto,
                       'matricula' => $this->matricula
                   ))); ?>
            ">
                <i class="<?php echo $this->projeto->domstatusprojeto == 8 ? 'icon-repeat' : 'icon-trash'; ?>"></i>
            </a>
        <?php endif; ?>
        <a data-target="#dialog-editar" class="btn actionfrm editar" title="Editar TAP" data-id="' + cellvalue + '"
           href="<?php echo $this->url(
               array(
                   'module' => 'projeto',
                   'controller' => 'tap',
                   'action' => 'informacoesiniciais',
                   'idprojeto' => $this->projeto->idprojeto,
                   'matricula' => $this->matricula
               )); ?>"><i class="icon-edit"></i>
        </a>
        <a class="btn btn-imprimir-word" title="Exportar TERMO DE ABERTURA DE PROJETO (TAP)" target="_blank"
           href="<?php echo $this->url(
               array(
                   'module' => 'projeto',
                   'controller' => 'tap',
                   'action' => 'imprimir-word',
                   'idprojeto' => $this->projeto->idprojeto,
                   'matricula' => $this->matricula
               )); ?>">
            <i class="icon-book"></i>
        </a>
        <a class="btn btn-cadastrar-grupo" style="padding-right: 10px;"
           title="Imprimir TERMO DE ABERTURA DE PROJETO (TAP)" target="_blank" href="<?php echo $this->url(
            array(
                'module' => 'projeto',
                'controller' => 'tap',
                'action' => 'imprimir',
                'idprojeto' => $this->projeto->idprojeto,
                'tipodoc' => 1,
                'acao' => urlencode($this->acao),
                'matricula' => $this->matricula
            )); ?>">
            <i class="icon-print"></i>
        </a>
        <a class="btn btn-imprimir-word" title="Exportar PLANO DE PROJETO" target="_blank" href="<?php echo $this->url(
            array(
                'module' => 'projeto',
                'controller' => 'planoprojeto',
                'action' => 'imprimir-word',
                'idprojeto' => $this->projeto->idprojeto,
                'matricula' => $this->matricula
            )); ?>">
            <i class="icon-book"></i>
        </a>
        <a class="btn btn-cadastrar-grupo" title="Imprimir PLANO DE PROJETO" target="_blank"
           href="<?php echo $this->url(
               array(
                   'module' => 'projeto',
                   'controller' => 'planoprojeto',
                   'action' => 'imprimir',
                   'idprojeto' => $this->projeto->idprojeto,
                   'tipodoc' => 2,
                   'matricula' => $this->matricula
               )); ?>">
            <i class="icon-print"></i>
        </a>
        <?php if ($this->projeto->domstatusprojeto != 8): ?>
            <a class="btn actionfrm  <?php echo $this->projeto->domstatusprojeto == 8 ? 'restaurarprojeto' : 'excluirprojeto'; ?>"
               title="<?php echo $this->projeto->domstatusprojeto == 8 ? 'Recuperar' : 'Excluir' ?> Projeto"
               id="<?php echo($this->projeto->domstatusprojeto == 8 ? 'restaurar' : 'excluir'); ?>"
               href="<?php echo($this->projeto->domstatusprojeto == 8 ?
                   $this->url(array(
                       'module' => 'projeto',
                       'controller' => 'gerencia',
                       'action' => 'restaurarprojeto',
                       'idprojeto' => $this->projeto->idprojeto,
                       'matricula' => $this->matricula
                   )) :
                   $this->url(array(
                       'module' => 'projeto',
                       'controller' => 'gerencia',
                       'action' => 'excluirprojeto',
                       'idprojeto' => $this->projeto->idprojeto,
                       'matricula' => $this->matricula
                   ))); ?>
            ">
                <i class="<?php echo $this->projeto->domstatusprojeto == 8 ? 'icon-repeat' : 'icon-trash'; ?>"></i>
            </a>
        <?php endif; ?>
    </div>


    <!-- Informacoes Iniciais -->
    <div id="ii" class="informacoes" style="display: block">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'informacoesiniciais')); ?>
        <fieldset>
            <legend>Informações Iniciais</legend>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Código</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomcodigo; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span6">
                    <h3>Título do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomprojeto; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Programa</h3>
                    <div class="content">
                        <?php echo $this->projeto->programa; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Orçamento Previsto</h3>
                    <div class="content">
                        <?php echo $this->projeto->getVlrorcamentodisponivelFormatado(); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Objetivo Institucional</h3>
                    <div class="content">
                        <?php echo $this->projeto->objetivo; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Ação Estratégica</h3>
                    <div class="content">
                        <?php echo $this->acao; ?>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Demandante</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomdemandante; ?>

                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Patrocinador</h3>
                    <div class="content">
                        <?php echo $this->projeto->nompatrocinador; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Gerente do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomgerenteprojeto; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Gerente Adjunto</h3>
                    <div class="content">
                        <?php echo $this->projeto->nomgerenteadjunto; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Início do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datinicio->toString('d/m/Y'); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Fim do Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datfim->toString('d/m/Y'); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Início do Plano Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datinicioplano->toString('d/m/Y'); ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Fim do Plano Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->datfimplano->toString('d/m/Y'); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span3">
                    <h3>Área Executora</h3>
                    <div class="content">
                        <?php echo $this->projeto->setor; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Escritório Responsável</h3>
                    <div class="content">
                        <?php echo $this->nomeEscritorio; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Periodicidade de Atualização(Dias)</h3>
                    <div class="content">
                        <?php echo $this->projeto->numperiodicidadeatualizacao; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span3">
                    <h3>Critério Farol Prazo(Dias)</h3>
                    <div class="content">
                        <?php echo $this->projeto->numcriteriofarol; ?>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>Demais Informações</legend>
            <div class="row">
                <div class="portlet portlet-verde span4">
                    <h3>Publicar Projeto</h3>
                    <div class="content">
                        <?php echo $this->projeto->publicado; ?>
                    </div>
                </div>
                <div class="portlet portlet-verde span4">
                    <h3>Aprovado?(TAP assinado)</h3>
                    <div class="content">
                        <?php echo $this->projeto->aprovado; ?>
                    </div>
                </div>
            </div>
            <div class="row">
            </div>
        </fieldset>
    </div>

    <!-- Informacoes Tecnicas -->
    <div id="it" class="informacoes" style="display: none">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'informacoestecnicas')); ?>
        <fieldset>
            <legend>Informações Técnicas</legend>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Justificativa do Projeto</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->desjustificativa); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Objeto do Projeto (O que será feito?)</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->desprojeto); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Objetivo do Projeto (Por que será feito?)</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->desobjetivo); ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>

    <!-- Resumo do Projeto -->
    <div id="rp" class="informacoes" style="display: none">
        <?php echo $this->partial('_partials/tap-menu-report.phtml', array('dados' => 'resumodoprojeto')); ?>
        <fieldset>
            <legend>Resumo do Projeto</legend>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Escopo Resumido (Principais Entregas)</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->desescopo); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Não Escopo (O que não será feito?)</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->desnaoescopo); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Premissas</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->despremissa); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-verde span8">
                    <h3>Restrições</h3>
                    <div class="content">
                        <?php echo nl2br($this->projeto->desrestricao); ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>   
</div>
<div id="dialog-excluirprojeto" style="display: none"></div>
<div id="dialog-restaurarprojeto" style="display: none"></div>


