<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/projeto/tap/parteinteressada.js?' . time()), 'text/javascript');

$frmAttr = $this->form->getAttribs();
$frmAttrExterno = $this->formExterno->getAttribs();
//Zend_Debug::dump($this->dados); exit;
?>
<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml', array('ativo' => 'abertura', 'idprojeto' => $this->idprojeto));
    ?>
</div>
<div class="region-center">
    <div class="row">
        <?php echo $this->partial('_partials/tap-menu.phtml', array('dados' => 'partesinteressadas')); ?>
    </div>
    <div class="portlet portlet-marron span13">
        <h3>Partes Interessadas</h3>
        <div class="content">
            <div class="row span12">
                <div class="portlet">
                    <ul class="nav nav-pills">
                        <li class="origem origem-interno active" data-cont="interno"><a id="origem-interno-link"
                                                                                        class="link"
                                                                                        href="#">Interno</a></li>
                        <li class="origem origem-externo" data-cont="externo"><a id="origem-externo-link" class="link"
                                                                                 href="#">Externo</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row span12">
            <div>
                <div class="interno formulario cont">
                    <form id="<?php echo $frmAttr['id']; ?>"
                          name="<?php echo $frmAttr['id']; ?>"
                          action="<?php echo $this->form->getAction(); ?>"
                          method="<?php echo $frmAttr['method']; ?>">
                        <div class="row">
                            <div class="span10">
                                <div class="row">
                                    <div class="container-pessoa">
                                        <div class="span">
                                            <div class="control-group">
                                                <?php echo $this->form->nomparteinteressada->renderLabel(); ?>
                                                <div class="controls">
                                                    <div class="input-prepend ">
                                                        <?php echo $this->form->pessoabutton; ?>
                                                        <?php echo $this->form->nomparteinteressada->renderViewHelper(); ?>
                                                        <?php echo $this->form->idparteinteressada; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!--<div class="span">
                                            <label class="control-label optional" for="nomparteinteressada">Nome</label>
                                        <?php //echo $this->formSelect('nomparteinteressada', null, null, App_Service::getService('Default_Service_Pessoa')->fetchPairs());  ?>
                                        </div>-->
                                    <div class="span">
                                        <?php echo $this->form->nomfuncao; ?>
                                    </div>
                                    <!--<div class="span">
                                        <label class="control-label optional" for="dessituacao">Situação</label>
                                        <input type="text" id="dessituacao" name="dessituacao" class="span2">
                                    </div>-->
                                    <div class="span">
                                        <!--                                            <label class="control-label optional" for="domnivelinfluencia">Nível de Influência</label>
                                                                                    <select id="domnivelinfluencia" name="domnivelinfluencia" class="span1">
                                                                                        <option value="Baixo">Baixo</option>
                                                                                        <option value="Médio">Médio</option>
                                                                                        <option value="Alto">Alto</option>
                                                                                    </select>-->
                                        <?php echo $this->form->domnivelinfluencia; ?>
                                    </div>
                                    <div class="span" style="margin-top: 22px">
                                        <input id="idprojeto" type="hidden" value="<?php echo $this->idprojeto; ?>"
                                               name="idprojeto">
                                        <!--<button class="btn" type="button" id="btn-adicionar">Adicionar</button>-->
                                        <?php echo $this->form->adicionar; ?>
                                    </div>
                                </div>
                                <!--<div class="span2 actions-pesquisar" style="float:left;">-->
                                <div class="row grid-append" style="display: none;">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="externo formulario cont">
                    <form id="<?php echo $frmAttrExterno['id']; ?>"
                          name="<?php echo $frmAttrExterno['id']; ?>"
                          action="<?php echo $this->formExterno->getAction(); ?>"
                          method="<?php echo $frmAttrExterno['method']; ?>">
                        <div class="row">
                            <div class="span10">
                                <div class="row">
                                    <div class="span">
                                        <?php echo $this->formExterno->nomparteinteressadaexterno; ?>
                                    </div>
                                    <div class="span">
                                        <?php echo $this->formExterno->nomfuncaoexterno; ?>
                                    </div>
                                    <!--                                    <div class="span">
                                                                                <label class="control-label optional" for="dessituacao">Situação</label>
                                                                                <input type="text" id="dessituacao" name="dessituacao" class="span2">
                                                                            </div>-->
                                    <div class="span">
                                        <?php echo $this->formExterno->domnivelinfluenciaexterno; ?>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="span">
                                        <?php echo $this->formExterno->destelefoneexterno; ?>
                                    </div>
                                    <div class="span">
                                        <?php echo $this->formExterno->desemailexterno; ?>
                                    </div>
                                    <div class="span" style="margin-top: 22px">
                                        <?php echo $this->formExterno->adicionarexterno; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <input id="idprojeto" type="hidden" value="<?php echo $this->idprojeto; ?>"
                                   name="idprojeto">
                        </div>
                    </form>
                </div>
            </div>

            <div id="listagemInteressados" class="row">
                <?php if (count($this->dados) > 0): ?>
                    <table class="table table-bordered table-hover table-striped span10">
                        <colgroup>
                            <col style="width: 150px">
                            <col style="width: 100px">
                            <col style="width: 50px">
                            <col style="width: 50px">
                            <col style="width: 55px">
                            <col style="width: 8px;">
                            <col style="width: 8px;height: 5px;">
                        </colgroup>
                        <thead>
                        <th>Nome</th>
                        <th>Função</th>
                        <th>Telefone</th>
                        <th>Email</th>
                        <th>Nível&nbsp;Influência</th>
                        <th style="text-align: center;" colspan="2">Operações</th>
                        </thead>
                        <tbody>
                        <?php foreach ($this->dados as $data) : ?>
                            <tr>
                                <td>
                                    <?php echo $data->nomparteinteressada; ?>
                                </td>
                                <td>
                                    <?php echo $data->nomfuncao; ?>
                                </td>
                                <td style="width: 60px">
                                    <?php
                                    $ocorrencia = substr_count($data->destelefone, '-');
                                    if ($ocorrencia >= 1) {
                                        $ocorrencia = str_replace('-,', '', $data->destelefone);
                                        echo $ocorrencia;
                                    } else {
                                        echo $data->destelefone;
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    $str = $data->desemail;
                                    $dst = implode("", array_unique(str_split($str, 2)));
                                    echo $novaString = preg_replace('/(.*),[ ]*$/', '${1}', $dst);
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    $str = $data->domnivelinfluencia;
                                    $dst = implode("", array_unique(str_split($str, 2)));
                                    echo $novaString = preg_replace('/(.*),[ ]*$/', '${1}', $dst);
                                    ?>
                                </td>
                                <td align="center" class="tabela" style="width: 8px;" nowrap>
                                    <a style="margin-right: -13px;" class='btn actionfrm editar editarbutton'
                                       title='Editar Interessado' data-id="<?php echo $data->idparteinteressada ?>"
                                       data-idprojeto="<?php echo $data->idprojeto ?>"
                                       data-idpessoainterna="<?php echo $data->idpessoainterna ?>">
                                        <i class='icon-edit'></i>
                                    </a>
                                </td>
                                <td align="center" class="tabela" style="width: 8px;" nowrap>
                                    <a style="margin-right: -13px;" class='btn actionfrm excluir excluirbutton'
                                       data-target="#dialog-editar" title='Excluir Interessado'
                                       data-id="<?php echo $data->idparteinteressada ?>"
                                       data-idprojeto="<?php echo $data->idprojeto ?>"
                                       data-idpessoainterna="<?php echo $data->idpessoainterna ?>">
                                        <i class='icon-trash'></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div id="nenhumregistro" class="alert alert-block" style="display: none">Nenhum registro
                        encontrado
                    </div>
                <?php else: ?>
                    <div id="nenhumregistro" class="alert alert-danger">Nenhum registro encontrado</div>
                <?php endif; ?>
            </div>
            <div class="row span12">
                <div class="span2" style="float: right;margin-bottom: 10px;margin-right: 7px;">
                    (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)&nbsp;Preenchimento
                    obrigatório
                </div>
            </div>
        </div>
    </div>
</div>
<div id="dialog-editar" style="display: none"></div>



