<div class="row">
    <div class="portlet portlet-azul span4">
        <h3>Processo</h3>
        <div class="content">
            <?= $this->processo->nomprocesso; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Diretoria</h3>
        <div class="content">
            <?= $this->processo->nomsetor; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Responsável</h3>
        <div class="content">
            <?= $this->processo->idresponsavel; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span2">
        <h3>Início Previsto</h3>
        <div class="content">
            <?= $this->dateBr($this->processo->datinicioprevisto); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Término Previsto</h3>
        <div class="content">
            <?= $this->dateBr($this->processo->datterminoprevisto); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Situa&ccedil;&atilde;o</h3>
        <div class="content">
            <?= $this->processo->domsituacao; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Data Situa&ccedil;&atilde;o</h3>
        <div class="content">
            <?= $this->dateBr($this->processo->datsituacao); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span4">
        <h3>Cadastrador</h3>
        <div class="content">
            <?= $this->processo->idcadastrador; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Data Cadastro</h3>
        <div class="content">
            <?= $this->dateBr($this->processo->datcadastro); ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Orçamento</h3>
        <div class="content">
            <?= $this->processo->vlrorcamento; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span8">
        <h3>Descri&ccedil;&atilde;o</h3>
        <div class="content">
            <?= $this->processo->desprojetoprocesso; ?>
        </div>
    </div>
</div>