<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/jquery-ui-1.8.12/css/custom-theme/jquery-ui-1.8.12.custom.css',
        'screen, projection'))
    ->appendStylesheet($this->baseUrl('/css/layout.css', 'screen, projection'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery-ui-1.10.2.custom/css/dpf/jquery-ui-1.10.2.custom.css',
        'screen, projection'));
$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/kendoui.web/js/kendo.web.min.js'))
    ->appendFile($this->baseUrl('/js/library/kendoui.web/styles/kendo.common.min.css'))
    ->appendFile($this->baseUrl('/js/library/kendoui.web/styles/kendo.bootstrap.min.css'));

$frmAttr = $this->form->getAttribs();

$Cont = 0;
?>
<style>
    #content-tabs ul a:hover {
        background-color: #08c;
    }

    #content-tabs ul li.current, .ui-state-active a, .ui-state-active a:link, .ui-state-active a:visited {
        background-color: #08c;
        border-style: none;
        border-image: none;
        background-image: none;
        outline: none;
        border: none;
        outline-width: 0;
        outline-color: transparent;
        box-shadow: none;
    }

    div.content-tabs {
        margin-left: 1px;
        border-color: transparent;
    }

    li.li-tab, span.img-tab {
        padding: 1px 1px;
        font-size: 2px;
    }
</style>

<div class="content">
    <form id="<?php echo $frmAttr['id']; ?>"
          name="<?php echo $frmAttr['id']; ?>"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">
        <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->idprojeto; ?>"/>
        <input type="hidden" name="idparteinteressada" id="idparteinteressada"
               value="<?php echo $this->idparteinteressada; ?>"/>
        <input type="hidden" name="idpessoa" id="idpessoa" value="<?php echo $this->idpessoa; ?>"/>

        <div class="row">
            <div class="portlet portlet-marron span5">
                <h3>Nome</h3>
                <div class="content">
                    <?php echo $this->dadosParte['nomparteinteressada']; ?>
                </div>
            </div>
            <div class="portlet portlet-marron span5">
                <h3>Email</h3>
                <div class="content">
                    <?php echo $this->dadosParte['desemail']; ?>
                </div>
            </div>
        </div>

        <div class="row">
            <tbody>
            <div class="portlet portlet-marron span10" style="height: 360px;">
                <h3>Permissões do Projeto</h3>
                <div id="tabs" class="content-tabs tabs span9">
                    <?php if (count($this->dadosPermissao) > 0): ?>
                        <ul class="tabs-menu">
                            <?php foreach ($this->dadosPermissao as $dataPermissao) : ?>
                                <li class="li-tab" id="<?php echo $dataPermissao['idrecurso']; ?>"
                                    name="<?php echo strtolower($dataPermissao['txrecurso']); ?>">
                                    <a class="lnk-permissao" id="<?php echo strtolower($dataPermissao['txrecurso']); ?>"
                                       title="<?php echo $frmAttr['titles'][strtoupper($dataPermissao['txrecurso'])]; ?>"
                                       href="#tabs-<?php echo strtolower($dataPermissao['txrecurso']); ?>">
                                        <span class="glyphicons-<?php echo strtolower($dataPermissao['txrecurso']); ?> img-tab"></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <?php foreach ($this->dadosPermissao as $listaPermissao) : ?>
                            <div id="tabs-<?php echo strtolower($listaPermissao['txrecurso']); ?>"
                                 class="tabs-<?php echo strtolower($listaPermissao['txrecurso']); ?>"
                                 idrecurso="<?php echo $listaPermissao['idrecurso']; ?>"
                                 title="<?php echo strtolower($listaPermissao['ds_recurso']); ?>"
                                 style="overflow: scroll;overflow-y: scroll;height: 300px;"></div>
                        <?php
                        endforeach;
                        ?>
                    <?php else: ?>
                        <div class="content">Nenhuma permissão encontrada.</div>
                    <?php endif; ?>
                </div>
            </div>
            </tbody>
        </div>

    </form>
</div>



