<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.3.2/select2.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/gerencia/add.js'), 'text/javascript');


//echo $this->form;
$frmAttr = $this->form->getAttribs();
?>

<div class="content">

    <form id="<?php echo $frmAttr['id']; ?>"
          name="<?php echo $frmAttr['id']; ?>"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">

        <fieldset>
            <legend>Informações Iniciais</legend>
            <div class="row">
                <div class="span3">
                    <?php echo $this->form->codprojeto; ?>
                </div>
                <div class="span6">
                    <?php echo $this->form->nomprojeto; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->vlrorcamentodisponivel; ?>
                </div>
            </div>
            <div class="row">
                <div class="span3">
                    <?php echo $this->form->nomcodigo; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->idobjetivo; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->idnatureza; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->idsetor; ?>
                </div>
            </div>
            <div class="row">
                <div class="span3">
                    <?php echo $this->form->iddemandante; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->idpatrocinador; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->idgerenteprojeto; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->idgerenteadjunto; ?>
                </div>
            </div>
            <div class="row">
                <div class="span3">
                    <?php echo $this->form->datinicio; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->datfim; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->datinicioplano; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->datfimplano; ?>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    &nbsp;
                </div>
            </div>
        </fieldset>

        <div id="accordion">
            <h3><a href="#">Section 1</a></h3>
            <div>
                <p>
                <fieldset>
                    <legend>Demais Informações</legend>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->domtipoprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flacopa; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->numperiodicidadeatualizacao; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->numcriteriofarol; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flapublicado; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flaaprovado; ?>
                        </div>
                    </div>
                </fieldset>
                </p>
            </div>
            <h3><a href="#">Section 2</a></h3>
            <div>
                <p>Sed non urna. Phasellus eu ligula. Vestibulum sit amet purus.
                    Vivamus hendrerit, dolor aliquet laoreet, mauris turpis velit,
                    faucibus interdum tellus libero ac justo.</p>
            </div>
            <h3><a href="#">Section 3</a></h3>
            <div>
                <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus.
                    Quisque lobortis.Phasellus pellentesque purus in massa.</p>
                <ul>
                    <li>List item one</li>
                    <li>List item two</li>
                    <li>List item three</li>
                </ul>
            </div>
        </div>

        <div class="row form">
            <div class="span4">
                <?php echo $this->form->submit; ?>
                <?php echo $this->form->reset; ?>
            </div>
        </div>

    </form>
</div>