<?php

$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");

$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/gerencia/index.css?' . time()))
    ->appendStylesheet($this->baseUrl('/css/app/versaoSistema/versao.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/versaoSistema/jQuery-QuickSearch.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/gerencia/index.js?' . time()), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/versaoSistema/versao.js?' . time()), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a class="btn"
               href="<?php echo $this->url(array('module' => 'projeto', 'controller' => 'tap', 'action' => 'add')); ?>">Novo
                Termo de Abertura (TAP)</a>
        </div>
    </div>

    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>

    <?php if (count($this->versaoHTML) > 0) { ?>
        <!-- Modal -->
        <div id="modalNotaVersao" class="modal hide fade portlet portlet-marron" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header nopadding">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;&nbsp;&nbsp;
                </button>
                <h3 id="myModalLabel">Vers&atilde;o Atual:&nbsp;<?php echo $this->versaoHTML->versao; ?> </h3>
            </div>
            <div class="modal-body">
                <?php echo $this->versaoHTML->corpoHTML; ?>
            </div>
        </div>
    <?php } ?>

</div>

<div class="region-east">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Gerência - Tela Mestra</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->nomprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idprograma; ?>
                        </div>
                        <div class="span3">
                            <?php

                            //                                if($this->identiti->perfilAtivo->idperfil == 1){
                            echo $this->form->idescritorio;
                            //                                }
                            ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->domstatusprojeto; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->codobjetivo; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->codacao; ?>
                        </div>
                        <div class="span">
                            <?php echo $this->form->acompanhamento; ?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->form->submit; ?>
                                <?php echo $this->form->reset; ?>
                                <?php echo $this->form->close; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php
/**
 *
 * @todo remover este link (abaixo) após a criação do menu
 */
?>

<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>
<div id="dialog-clonarprojeto" style="display: none"></div>
<div id="dialog-excluirprojeto" style="display: none"></div>
<div id="dialog-restaurarprojeto" style="display: none"></div>
<!--<div id="dialog-desbloquear" style="display: none"></div>-->