<div class="row">
    <div class="portlet portlet-azul span4">
        <h3>Recurso</h3>
        <div class="content">
            <?php echo $this->permissao['ds_recurso']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Nome da Permissão</h3>
        <div class="content">
            <?php echo $this->permissao['no_permissao']; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span6">
        <h3>Descrição da Permissão</h3>
        <div class="content">
            <?php echo $this->permissao['ds_permissao']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Visualizar</h3>
        <div class="content">
            <?php echo $this->permissao['detalhevisualizar']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Tipo</h3>
        <div class="content">
            <?php echo $this->permissao['detalhetipo']; ?>
        </div>
    </div>
</div>