<script>

    $(function () {
        $.pnotify.defaults.history = false;

        $('#desobservacao').limit('800', '#maxChars');

    });


    function resetFormQuestionario() {
        $("#form-questionario :input").not('#idquestionario').val('');
    }

</script>


<?php $frmAttrQuestionario = $this->formQuestionario->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <form id="<?php echo $frmAttrQuestionario['id']; ?>"
              name="<?php echo $frmAttrQuestionario['id']; ?>"
              action="<?php echo $this->formQuestionario->getAction(); ?>"
              method="<?php echo $frmAttrQuestionario['method']; ?>">
            <div class="row-fluid">
                <div class="span">
                    <?php echo $this->formQuestionario->nomquestionario ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span">
                    <?php echo $this->formQuestionario->desobservacao ?>
                    Número caracteres restantes: <span id="maxChars" style="color: red;"></span><br/><br/>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span3">
                    <?php echo $this->formQuestionario->tipoquestionario ?>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
        (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
    </div>
</div>