<?php $frmAttrQuestionario = $this->formQuestionarioFrase->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <?php if ($this->boolDisponivel): ?>
            <div class="alert alert-block alert-danger"></i>Este question&aacute;rio econtra-se dispon&iacute;vel para
                publica&ccedil;&atilde;o, para alter&aacute;-lo &eacute; preciso torn&aacute;-lo indispon&iacute;vel.
            </div>
        <?php else: ?>
            <form id="<?php echo $frmAttrQuestionario['id']; ?>"
                  name="<?php echo $frmAttrQuestionario['id']; ?>"
                  action="<?php echo $this->formQuestionarioFrase->getAction(); ?>"
                  method="<?php echo $frmAttrQuestionario['method']; ?>">
                <?php echo $this->formQuestionarioFrase->idquestionario ?>
                <?php echo $this->formQuestionarioFrase->idfrase ?>
                <div class="row-fluid">
                    <div class="span2">
                        <?php echo $this->formQuestionarioFrase->numordempergunta ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->formQuestionarioFrase->obrigatoriedade ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span">
                        <label for="descricaofrase">Pergunta</label>
                        <div id="descricaofrase" style=" padding: 5px; border-radius: 5px; font-size: 12px"
                             class="input-selecionado">
                            <?php echo '(' . $this->nomescritorio . ') ' . $this->desfrase; ?>
                        </div>
                        <br/>
                    </div>
                </div>
            </form>
        <?php endif; ?>
    </div>
</div>