<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/max-chars.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/pesquisa/questionario/listar.js'), 'text/javascript');

$frmAttr = $this->formPesquisar->getAttribs();

?>
<div class="region-center">
    <h4 class="pagination-centered">Consulta de Question&aacute;rio</h4>
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a data-target="#dialog-inserir" class="btn inserir" title="Cadastrar" href="<?php echo $this->url(array(
                'module' => 'pesquisa',
                'controller' => 'questionario',
                'action' => 'cadastrar'
            )) ?>">
                Cadastrar
            </a>
        </div>
    </div>


    <table id="list-grid-questionario"></table>
    <div id="toolbar-grid-questionario"></div>
    <div id="pager-grid-questionario"></div>
</div>

<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Question&aacute;rio - Pesquisar</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->formPesquisar->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <div class="span">
                            <?php echo $this->formPesquisar->nomquestionario ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->tipoquestionario ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formPesquisar->btnpesquisar ?>
                                <?php echo $this->formPesquisar->reset ?>
                                <?php echo $this->formPesquisar->close ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="dialog-editar" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>
<div id="dialog-inserir" style="display: none"></div>
<div id="dialog-disponivel" style="display: none">
    <p>Esta operação tornará o questionário disponível para publicação.
    <p>
    <p><b class="icon-exclamation-sign"></b> <strong>Considerações:</strong></p>
    <p>
        1. Perguntas do tipo "uma escolha", "múltipla escolha" e "UF" que não
        possuírem itens de respostas cadastrados e ativos, não serão publicadas;<br/>
        2. Perguntas com status inativo não serão publicadas;<br/>
        3. Itens de respostas inativos não serão publicadas;<br/>
        4. Caso ocorra alguma das situações anteriores a exibição da ordem das perguntas na pesquisa poderá ser
        afetada.;<br/>
    </p>
</div>
<input type="hidden" id="questionario" name="questionario" value=""/>

<div id="dialog-error" style="display: none">
    <p><i class="icon-exclamation-sign"></i> Question&aacute;io inválido.
    <p>
    <p style="color: red;">Para tornar o question&aacute;rio dispon&iacute;vel para publi&ccedil;&atilde;o
        é preciso ter pelo menos uma pergunta ativa e se depender de respostas cadastradas,
        essas tamb&eacute;m devem estar ativas.
    <p>
</div>
<div id="dialog-error-editar" style="display: none">
    <p style="color: red;">Este question&aacute;rio econtra-se dispon&iacute;vel para publica&ccedil;&atilde;o, para
        alter&aacute;-lo &eacute; preciso torn&aacute;-lo indispon&iacute;vel.
    <p>
</div>