<script>

    $(function () {
        $.pnotify.defaults.history = false;

        var
            grid = null,
            lastsel = null,
            gridEnd = null,
            colModel = null,
            colNames = null,
            colNames = ['Escrit&oacute;rio', 'Pergunta', 'Tipo', ''];
        colModel = [{
            name: 'nomescritorio',
            index: 'nomescritorio',
            width: 10,
            search: true,
            hidden: false,
            sortable: true
        }, {
            name: 'desfrase',
            index: 'desfrase',
            width: 70,
            search: true,
            hidden: false,
            sortable: true
        }, {
            name: 'domtipofrase',
            index: 'domtipofrase',
            width: 20,
            hidden: false,
            search: false,
            sortable: true
        }, {
            name: 'idfrase',
            index: 'idfrase',
            width: 0,
            hidden: true,
            search: false,
            sortable: false,
            //formatter: formatadorLink
        }];


        grid = jQuery("#list-grid-vincular-pergunta").jqGrid({
            //caption: "Documentos",
            url: base_url + "/pesquisa/questionario/pesquisar-perguntas/operacao/vincular/idquestionario/" + $('#id-questionario').val(),
            datatype: "json",
            mtype: 'post',
            width: '945',
            height: '210',
            colNames: colNames,
            colModel: colModel,
            rownumbers: true,
            rowNum: 50,
            rowList: [20, 50, 100],
            pager: '#pager-grid-vincular-pergunta',
            sortname: 'desfrase',
            viewrecords: true,
            sortorder: "asc",
            gridComplete: function () {
                //console.log('teste');
                //$("a.actionfrm").tooltip();
            },
            onSelectRow: function (id) {
                if (window.selectRow) {
                    var row = grid.getRowData(id);
                    selectRow(row);
                } else {
                    alert('Função [selectRow] não está definida');
                }
            },
        });

        grid.jqGrid('navGrid', '#pager-grid-vincular-pergunta', {
            search: false,
            edit: false,
            add: false,
            del: false,
            view: false
        });

        grid.jqGrid('setLabel', 'rn', 'Ord');
        resizeGrid();
    });

    var timeoutHnd;
    var flAuto = false;


    $("#inserir-vinculo").click(function () {
        $('form#form-questionario-frase').submit();
    });


    function selectRow(row) {
        $('#form-questionario-frase #descricaofrase').html('(' + row.nomescritorio + ') ' + row.desfrase);
        $('#form-questionario-frase #idfrase').val(row.idfrase);
        $('#form-questionario-frase #numordempergunta').focus();

        return true;
    }

    function resetFormQuestionarioFrase() {
        $("#form-questionario-frase :input").not("#idquestionario").val('');
        $('#form-questionario-frase #descricaofrase').html('&nbsp;');
        $('#list-grid-vincular-pergunta').trigger('reloadGrid');
    }

    function pesquisar() {
        if (timeoutHnd)
            clearTimeout(timeoutHnd)
        timeoutHnd = setTimeout(gridReload, 500)
    }

    function gridReload() {
        var pergunta = $("#persquisar_pergunta").val();
        $('#list-grid-vincular-pergunta').jqGrid(
            'setGridParam', {
                url: base_url + "/pesquisa/questionario/pesquisar-perguntas/operacao/vincular/idquestionario/" + $('#id-questionario').val() + "/desfrase/" + pergunta,
                page: 1
            }).trigger("reloadGrid");
    }


</script>


<?php $frmAttrQuestionario = $this->formQuestionarioFrase->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <?php if ($this->boolDisponivel): ?>
            <div class="alert alert-block alert-danger"></i>Este question&aacute;rio econtra-se dispon&iacute;vel para
                publica&ccedil;&atilde;o, para alter&aacute;-lo &eacute; preciso torn&aacute;-lo indispon&iacute;vel.
            </div>
        <?php else: ?>
            <form id="<?php echo $frmAttrQuestionario['id']; ?>"
                  name="<?php echo $frmAttrQuestionario['id']; ?>"
                  action="<?php echo $this->formQuestionarioFrase->getAction(); ?>"
                  method="<?php echo $frmAttrQuestionario['method']; ?>">
                <?php echo $this->formQuestionarioFrase->idquestionario ?>
                <?php echo $this->formQuestionarioFrase->idfrase ?>
                <div class="row-fluid">
                    <div class="span2">
                        <?php echo $this->formQuestionarioFrase->numordempergunta ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->formQuestionarioFrase->obrigatoriedade ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span">
                        <label for="descricaofrase">Pergunta</label>
                        <div id="descricaofrase" style=" padding: 5px; border-radius: 5px; font-size: 12px;"
                             class="input-selecionado">
                            &nbsp;
                        </div>
                        <br/>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span pagination-centered">
                        <div class="btn" id="inserir-vinculo"><i class="icon-plus-sign"></i> Adicionar</div>
                    </div>
                </div>
            </form>
            <div class="portlet portlet-cinza">
                <div class="title">Selecione as perguntas que farão parte do seu questionário</div>
                <div class="content">
                    <div class="row-fluid">
                        <div class="span container">
                            <div class="portlet portlet-cinza span">
                                <div class="content">
                                    <div class="control-group">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-search"></i></span>
                                            <input class="span" type="text" id="persquisar_pergunta"
                                                   onkeydown="pesquisar()"/>
                                        </div>
                                    </div>
                                    <table id="list-grid-vincular-pergunta" class="noresize"></table>
                                    <div id="toolbar-grid-vincular-pergunta"></div>
                                    <div id="pager-grid-vincular-pergunta"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
            </div>
        </div>
    </div>
</div>