<?php
$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");
?>
<head>
    <style>
        .break {
            page-break-before: always;
        }

        @page Section1 {

            size: 1200;
        }

        div.Section1 {

            page: Section1;
        }

        p {
            border-width: medium;
            border-style: solid;
            border-color: #CCCCCC;
            line-height: 1;
            text-indent: 0;
            margin: 3px;
        }

        .container-grupo {
            width: 1500px;
            border: 1px solid red;
        }

        .titulo-tabela {
            font-weight: bold;
        }

        .box-grupo {
            padding-top: 5px;
            float: left;
            margin-bottom: 20px;
        }

        .box-nome-grupo {
            font-size: 12px;
            font-weight: bold;
            padding: 3px;
            text-align: center;
            border: 2px solid #555;
            background: #aaa;
        }

        .box-entrega {
            margin: 8px 0;
        }

        .box-item-entrega {
            font-size: 10px;
            border: 1px solid #fff;
            margin: 5px 0;
            background: #ccc;
            padding: 3px;
        }

        div#estAnalitic {
            font: 12px Arial, Sans-serif;
            vertical-align: middle;
            background-color: #CCCCCC;
        }

        span#tagEspan {
            font-weight: bold;
            text-shadow: 0 0 0.2em #87F 0 0 0.2em #87F, 0 0 0.2em #87F;
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
            border-radius: 50%;
            display: inline-block;
            height: 100px;
            width: 100px;
            color: #fff;
        }

    </style>
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<div class="Section1" style="font-size: 8px;">
    <table align="center" border="0" width="70%" height="90"
           style="font-size:8.0pt;mso-bidi-font-size: 10.0pt;font-family:Arial">
        <tr align="center">
            <td style="text-align:center;padding-bottom:20px;">
                <h5>PLANO DE GERENCIAMENTO DO PROJETO</h5>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:center;padding-bottom: 20px;">
                <h5><?php echo $this->projetos->nomcodigo; ?></h5>
            </td>
        </tr>
        <tr align="center">
            <td style="text-align:center;padding-bottom: 20px;">
                <h5><?php echo $this->projetos->nomprojeto; ?></h5>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5><?php echo $this->projetos->desprojeto; ?></h5>
            </td>
        </tr>
        <tr align="left">
            <!--<td style="text-align:left;padding-bottom: 20px;">-->
            <!--<h5>Resumo do projeto conforme último relatório</h5>-->
            <!--</td>-->
        </tr>
        <div style="color: #0064CD">
            <h5><?php echo $this->projetos->nomcodigo . ' - ' . $this->projetos->nomprojeto; ?></h5></div>
        <h5>Resumo do projeto</h5>
        <table border="1" class="table table-striped table-bordered table-price" style="font-size: 8px !important;">
            <colgroup>
                <col style="width: 50px;">
                <col style="width: 300px;">
                <col style="width: 50px;">
                <col style="width: 200px;">
                <col style="width: 50px;">
                <col style="width: 50px;">
                <col style="width: 100px;">
                <col style="width: 50px;">
                <col style="width: 50px;">
            </colgroup>
            <tr>
                <th>Patroci.:</th>
                <td><?php echo $this->projeto['patrocinador']['nompessoa'] ?></td>
                <th>Meta:</th>
                <td><?php echo $this->projeto['datinicio'] ?>
                    a <?php echo $this->projeto['datfim'] . ' - ' . $this->projeto['metaEmDias'] . ' dias' ?></td>
                <th>Previsto:</th>
                <td><?php echo $this->projeto['ultimoStatusReport']['numpercentualprevisto'] ?>%</td>
                <th>&Uacute;ltimo Relat&oacute;rio:</th>
                <td><?php echo $this->projeto['ultimoStatusReport']['datacompanhamento'] ?></td>
                <th>Atraso:</th>
                <td style="text-align: right; padding-right:5px;" bgcolor="<?php
                if ($this->projeto['descricaoPrazo'] == "important") {
                    $sinal = '#b94a48'; //"important";
                } elseif ($this->projeto['descricaoPrazo'] == "warning") {
                    $sinal = '#f89406';
                } else {
                    $sinal = '#468847'; //success
                }
                if ((int)$this->projeto['ultimoStatusReport']['numpercentualprevisto'] == 100) {
                    $sinal = "#cccccc";
                }
                echo $sinal; ?>"> <?php echo isset($this->projeto['descricaoPrazo']) ? $this->projeto['prazoEmDias'] . ' dias' : ""; ?> </td>
            </tr>
            <tr>
                <th>Gerente:</th>
                <td><?php echo $this->projeto['gerenteprojeto']['nompessoa'] ?></td>
                <th>Tend&ecirc;ncia:</th>
                <td><?php echo $this->projeto['datinicio'] . ' a ' . @mb_substr($this->projeto['ultimoStatusReport']['datfimprojetotendencia'],
                            0, 10) . ' - ' . $this->projeto['tendenciaEmDias'] . ' dias' ?></td>
                <th>Conclu&iacute;do:</th>
                <td><?php echo $this->projeto['ultimoStatusReport']['numpercentualconcluido'] ?>%</td>
                <th>Status:</th>
                <td><?php echo $this->projeto['ultimoStatusReport']['nomdomstatusprojeto'] ?></td>
                <th>Risco:</th>
                <td style="text-align: right; padding-right:5px;" bgcolor="<?php
                if ($this->projeto['descricaoRisco'] == "important") {
                    $sinal = '#b94a48'; //"important";
                } elseif ($this->projeto['descricaoRisco'] == "warning") {
                    $sinal = '#f89406';
                } else {
                    $sinal = '#468847'; //success
                }
                if ((int)$this->projeto['ultimoStatusReport']['numpercentualconcluido'] == 100) {
                    $sinal = "#cccccc";
                }
                echo $sinal; ?>"> <?php echo isset($this->projeto['descricaoRisco']) ? $this->projeto['ultimoStatusReport']['nomdomcorrisco'] : ""; ?>
                </td>
            </tr>
            <tr>
                <th>Adjunto:</th>
                <td><?php echo $this->projeto['gerenteadjunto']['nompessoa'] ?></td>
                <th>Alinhamento Estrat&eacute;gico:</th>
                <td colspan=""><?php echo $this->projeto['objetivo']['nomobjetivo'] ?>
                    <br/> <?php echo $this->projeto['acao']['nomacao'] ?></td>
                <th>% de Marcos Concluído do Projeto:</th>
                <td colspan=""><?php echo $this->projeto['percentualConcluidoMarco'] . "%"; ?></td>
                <th>Nº do Processo:</th>
                <td colspan=""><?php echo $this->numProcessoSei; ?></td>
                <th>Natureza:</th>
                <td><?php echo $this->projeto['natureza']['nomnatureza']; ?></td>
            </tr>
            <tr>
                <th>Ativ. não iniciadas:</th>
                <td>
                    <?php
                    echo $this->projeto["qtdeatividadeiniciada"]['qtdeatividadenaoiniciada'] . ' atividade(s)';
                    echo ' (' . $this->projeto["qtdeatividadeiniciada"]['numpercentualnaoiniciado'] . '%)';
                    ?>
                </td>
                <th>Atividades iniciadas:</th>
                <td>
                    <?php
                    echo $this->projeto["qtdeatividadeiniciada"]['qtdeatividadeiniciada'] . ' atividade(s)';
                    echo ' (' . $this->projeto["qtdeatividadeiniciada"]['numpercentualiniciado'] . '%)';
                    ?>
                </td>
                <th>Atividades concluídas:</th>
                <td>
                    <?php
                    echo $this->projeto["qtdeatividadeiniciada"]['qtdeatividadeconcluida'] . ' atividade(s)';
                    echo ' (' . $this->projeto["qtdeatividadeiniciada"]['numpercentualatividadeconcluido'] . '%)';
                    ?>
                </td>
                <th></th>
                <td></td>
                <th></th>
                <td></td>
            </tr>
        </table>
        <tr align="left">
            <td style="text-align:left;width: 100%;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>

        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>1. DECLARA&Ccedil;&Atilde;O DO ESCOPO/QUALIDADE</h5>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>1.1 ESTRUTURA ANAL&Iacute;TICA DO PROJETO - EAP</h5>
            </td>
        </tr>
        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">

                <table style="width: 80%;" align="left" border="0" cellpadding="1" cellspacing="1">
                    <tr>
                        <?php
                        if (isset($this->projeto['grupos'])):
                            foreach ($this->projetos->grupos as $grupo): ?>
                                <td id="entr" id="entr"
                                    style="border:0.1mm solid #AAAAAA; background-color: #808080; text-align: center"
                                    valign="center" height="115px" width="30%">
                                    <b><?php echo $grupo->nomatividadecronograma; ?></b>
                                </td>
                            <?php endforeach;
                        endif; ?>
                    </tr>
                    <tr>
                        <?php
                        if (isset($this->projeto['grupos'])):
                            foreach ($this->projeto['grupos'] as $gr): ?>
                                <td valign="top" height="115px" style="width:'30%'">
                                    <?php
                                    if (isset($gr['entregas'])):
                                        foreach ($gr['entregas'] as $en) :
                                            if ($en['descricaoprazo'] == "important") {
                                                $sinal = '#b94a48'; //"important";
                                            } elseif ($en['descricaoprazo'] == "warning") {
                                                $sinal = '#f89406';
                                            } elseif ($en['descricaoprazo'] == "success") {
                                                $sinal = '#468847'; //success
                                            } else {
                                                $sinal = '#DCDCDC';
                                            }
                                            if ((int)$en['numpercentualconcluido'] == 100) {
                                                $sinal = '#cccccc';
                                            }
                                            echo "<div id='estAnalitic'> <p>" . "<span id='tagEspan' style='background-color: $sinal; '> " . ' &nbsp ' . $en['prazo'] . ' dias' . ' </span>' . ' &nbsp ' . $en['numpercentualconcluido'] . '% ' . $en['nomatividadecronograma'] . "</p></div> " ?>
                                        <?php endforeach;
                                    endif; ?>
                                </td>
                            <?php endforeach;
                        else: ?>
                            <td valign="center" height="115px">
                            </td>
                        <?php endif; ?>
                    </tr>
                </table>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;width: 100%;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>

        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>1.2 DICION&Aacute;RIO DA EAP E CRIT&Eacute;RIO DE ACEITA&Ccedil;&Atilde;O (QUALIDADE)</h5>
            </td>
        </tr>
        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table style="width: 100%;border-collapse: collapse;" border="1" cellpadding="1" cellspacing="1">
                    <colgroup>
                        <col style="width: 3%">
                        <col style="width: 10%">
                        <col style="width: 25%">
                        <col style="width: 25%">
                        <col style="width: 37%">
                    </colgroup>
                    <thead>
                    <tr class="table table-hover table-striped table-condensed"
                        style="width: 100%; background-clip: border-box; background-color: #ccc;" valign="top">
                        <!--<td><b>ID</b></td>-->
                        <td><b>IDENTIFICA&Ccedil;&Atilde;O EAP</b></td>
                        <td><b>DESCRI&Ccedil;&Atilde;O</b></td>
                        <td><b>CRIT&Eacute;RIO DE ACEITA&Ccedil;&Atilde;O/DESVIO ACEIT&Aacute;VEL (QUALIDADE)</b></td>
                        <td><b>RESPONS&Aacute;VEL PELA ENTREGA</b></td>
                        <td><b>RESPONS&Aacute;VEL PELA ACEITA&Ccedil;&Atilde;O</b></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if (isset($this->projetos->grupos)):
                        foreach ($this->projetos->grupos->getIterator() as $grupo): ?>
                            <tr>
                                <hr>
                                <td colspan="5"
                                    style="font-weight: bold; border: none; padding-top: 2px;"><?php echo $grupo->nomatividadecronograma ?>
                                    diasxyz
                                </td>
                            </tr>
                            <?php
                            foreach ($grupo->entregas->getIterator() as $entrega):
                                ?>
                                <tr valign="top">
                                    <!--<td style="text-align: center;"><?//= $entrega->numseq;
                                    ?></td>-->
                                    <hr>
                                    <td style="border: none"><?php echo $entrega->nomatividadecronograma; ?></td>
                                    <hr>
                                    <td style="border: none"><?php echo $entrega->desobs; ?> </td>
                                    <hr>
                                    <td style="border: none"><?php echo $entrega->descriterioaceitacao; ?></td>
                                    <hr>
                                    <td style="border: none"><?php echo $entrega->parteinteressada->nomparteinteressada; ?></td>
                                    <hr>
                                    <td style="border: none"><?php echo $entrega->responsavelAceitacao->nomparteinteressada; ?></td>
                                </tr>
                            <?php
                            endforeach;
                        endforeach;
                    endif;
                    ?>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>1.3 N&Atilde;O ESCOPO (O QUE N&Atilde;O SER&Aacute; FEITO)</h5>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <?php echo nl2br($this->projetos->desnaoescopo); ?>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;width: 100%;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>

        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>2. CRONOGRAMA</h5>
            </td>
        </tr>
        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table style="width: 100%;border-collapse: collapse;" border="1" cellpadding="1" cellspacing="1">
                    <thead>
                    <tr>
                        <th>Grupo/Evento/Atividade</th>
                        <th>(P)</th>
                        <th>In&iacute;cio/Fim(Planejado)</th>
                        <th>(D/P)</th>
                        <th>Custo</th>
                        <th>In&iacute;cio/Fim(Realizado)</th>
                        <th>(D/R)</th>
                        <th>%</th>
                        <th>Respons&aacute;vel</th>
                        <th>Atraso</th>
                    </tr>
                    </thead>
                    <tbody>
                    <colgroup>
                        <col style="width: 35%; border: 1px solid red;">
                        <col style="width: 20%; text-align: center;border: 1px solid red;">
                        <col style="width: 7%; text-align: center;border: 1px solid red;">
                        <col style="width: 7%;text-align: center;">
                        <col style="width: 20%;">
                        <col style="width: 5%;">
                        <col style="width: 15%;">
                        <col style="width: 15%;">
                    </colgroup>
                    <tr style="border-bottom: thick solid #ccc; background: #b3b3b3">
                        <td style="font-weight: bold; text-align: left">
                            <?php
                            echo $imagem = "<img src=\"" . $this->server . 'img/icon-folder-close.png' . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                            //echo"<img src=\"" . $this->baseUrl('/img/icon-folder-close.png') . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                            echo isset($this->linhaResumoNomProjeto) ? $this->linhaResumoNomProjeto : ""; ?>
                        </td>
                        <td></td>
                        <td style="font-weight: bold; text-align: left"><?php echo isset($this->linhaResumoDtPlanejado) ? $this->linhaResumoDtPlanejado : ""; ?></td>
                        <td style="font-weight: bold; text-align: left"><?php echo isset($this->linhaResumoDiasBaseLine) ? $this->linhaResumoDiasBaseLine : ""; ?></td>
                        <td style="font-weight: bold; text-align: left"><?php echo isset($this->linhaResumoCusto) ? $this->linhaResumoCusto : ""; ?></td>
                        <td style="font-weight: bold; text-align: left"><?php echo isset($this->linhaResumoDtRealizado) ? $this->linhaResumoDtRealizado : ""; ?> </td>
                        <td style="font-weight: bold; text-align: left"><?php echo isset($this->linhaResumoDiasRealizados) ? $this->linhaResumoDiasRealizados : ""; ?></td>
                        <?php $percentual = isset($this->linhaResumoPercentual) ? $this->linhaResumoPercentual : ""; ?>
                        <td style="font-weight: bold; text-align: left"><?php echo $percentual; ?></td>
                        <td style="font-weight: bold; text-align: left"></td>
                        <td style="text-align: right; padding-right:5px;" bgcolor="<?php

                        if ($this->linhaCorFarol == "important") {
                            $sinal = '#b94a48'; //"important";        
                        } elseif ($this->linhaCorFarol == "warning") {
                            $sinal = '#f89406';
                        } else {
                            $sinal = '#468847'; //success
                        }
                        if ((int)$percentual == 100) {
                            $sinal = '#cccccc';
                        }
                        echo $sinal; ?>"> <?php echo isset($this->linhaResumoFarol) ? $this->linhaResumoFarol : ""; ?>
                            dias
                        </td>
                    </tr>
                    <?php
                    if (isset($this->projeto['grupos'])):
                        foreach ($this->projeto['grupos'] as $gr):

                            if (@$gr['descricaoprazo'] == "important") {
                                $sinal = '#b94a48'; //"important";
                            } elseif (@$gr['descricaoprazo'] == "warning") {
                                $sinal = '#f89406';
                            } else {
                                $sinal = '#468847'; //success
                            }
                            if ((int)$gr['numpercentualconcluido'] == 100) {
                                $sinal = '#cccccc';
                            }
                            ?>
                            <tr style="border-bottom: thick solid #ccc;">
                                <td style="font-weight: bold;">
                                    <?php
                                    echo $imagem = "<img src=\"" . $this->server . 'img/icon-folder-open.png' . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                    //echo"<img src=\"" . $this->baseUrl('/img/icon-folder-open.png') . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                    echo $gr['numseq'] . ' - ' . $gr['nomatividadecronograma'] ?>
                                </td>
                                <td></td>
                                <td>
                                    <?php echo isset($gr['datiniciobaseline']) ? $gr['datiniciobaseline'] : ""; ?> a
                                    <?php echo isset($gr['datfimbaseline']) ? $gr['datfimbaseline'] : ""; ?>
                                </td>
                                <td style="text-align: left"><?php echo $gr['diasbaseline'] ?></td>
                                <td style="text-align: left"><?php echo $gr['vlratividade'] ?></td>
                                <td>
                                    <?php echo isset($gr['datinicio']) ? $gr['datinicio'] : ""; ?> a
                                    <?php echo isset($gr['datfim']) ? $gr['datfim'] : ""; ?>
                                </td>
                                <td><?php echo $gr['diasreal']; ?> </td>
                                <td>
                                    <?php echo $gr['numpercentualconcluido'] ?>%
                                </td>
                                <td>&nbsp;</td>
                                <?php $sinal = (int)$gr['numpercentualconcluido'] == 100 ? '#cccccc' : $sinal; ?>
                                <td bgcolor="<?php echo $sinal; ?>" style="text-align: right; padding-right:5px;">
                                    <?php echo isset($gr['prazo']) ? $gr['prazo'] : "" ?> dias
                                </td>
                            </tr>
                            <?php if (isset($gr['entregas'])):
                            foreach ($gr['entregas'] as $en):

                                if (@$en['descricaoprazo'] == "important") {
                                    $sinal = '#b94a48'; //"important";
                                } elseif (@$en['descricaoprazo'] == "warning") {
                                    $sinal = '#f89406';
                                } else {
                                    $sinal = '#468847'; //success
                                }
                                if ($en['numpercentualconcluido']) {
                                    $sinal = '#cccccc';
                                }
                                ?>
                                <tr>
                                    <td style="padding-left: 15px;">
                                        <?php
                                        echo $imagem = "<img src=\"" . $this->server . 'img/icon-tag.png' . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                        //echo"<img src=\"" . $this->baseUrl('/img/icon-tag.png') . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                        echo $en['numseq'] . ' - ' . $en['nomatividadecronograma'] ?>
                                    </td>
                                    <td></td>
                                    <td>
                                        <?php echo isset($en['datiniciobaseline']) ? $en['datiniciobaseline'] : ""; ?> a
                                        <?php echo isset($en['datfimbaseline']) ? $en['datfimbaseline'] : ""; ?>
                                    </td>
                                    <td style="text-align: left">
                                        <?php echo $en['diasbaseline'] ?></td>
                                    <td style="text-align: left">
                                        <?php echo $en['vlratividade'] ?></td>
                                    <td>
                                        <?php echo isset($en['datinicio']) ? $en['datinicio'] : ""; ?> a
                                        <?php echo isset($en['datfim']) ? $en['datfim'] : ""; ?>
                                    </td>
                                    <td><?php echo $en['diasreal']; ?></td>
                                    <td><?php echo $en['numpercentualconcluido'] ?>%</td>
                                    <td><?php echo $en['desemail'] = $en['desemail'] ? $en['desemail'] : "" ?></td>
                                    <?php $sinal = (int)$en['numpercentualconcluido'] == 100 ? '#cccccc' : $sinal; ?>
                                    <td bgcolor="<?php echo $sinal; ?>" style="text-align: right; padding-right:5px;">
                                        <?php echo isset($en['prazo']) ? $en['prazo'] : ""; ?> dias
                                    </td>
                                </tr>
                                <?php if (isset($en['atividades'])):
                                foreach ($en['atividades'] as $at):

                                    if (@$at['descricaoprazo'] == "important") {
                                        $sinal = '#b94a48'; //"important";
                                    } elseif (@$at['descricaoprazo'] == "warning") {
                                        $sinal = '#f89406';
                                    } else {
                                        $sinal = '#468847'; //success
                                    }
                                    if ((int)$at["numpercentualconcluido"] == 100) {
                                        $sinal = '#cccccc';
                                    }
                                    //$hoje = new DateTime('now');
                                    $hoje = date("Y-m-d");

                                    if ($at["flacancelada"] == 'S') {//item-cancelado
                                        $verificaCancelada = 'text-decoration: line-through; color: #996699;';
                                    } elseif ($at["numpercentualconcluido"] == '100.00' && $at["flacancelada"] != 'S') { //item concluido
                                        $verificaCancelada = 'font-style:italic; color:#A8A8A8;';
                                    }

                                    $arr_dt = explode("/", $at['datfim']);
                                    $dia = $arr_dt[0];
                                    $mes = $arr_dt[1];
                                    $ano = mb_substr($arr_dt[2], 0, 4);
                                    $data = $ano . '-' . $mes . '-' . $dia;

                                    if ($at["numpercentualconcluido"] != '100.00' && $at["flacancelada"] != 'S') {
                                        if (strtotime($data) < strtotime($hoje)) {//item atrasado
                                            $verificaCancelada = 'color:#FF0000;';
                                        }
                                        if (strtotime($data) >= strtotime($hoje)) { //item em dia
                                            $verificaCancelada = 'color:#339900;';
                                        }
                                    }

                                    if ($at["domtipoatividade"] == 4) {
                                        $imagem = "<img src=\"" . $this->server . 'img/icon-flag.png' . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                        //$imagem = "<img src=\"" . $this->baseUrl('/img/icon-flag.png') . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                    } else {
                                        $imagem = "<img src=\"" . $this->server . 'img/icon-list-alt.png' . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                        //$imagem = "<img src=\"" . $this->baseUrl('/img/icon-list-alt.png') . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                    }
                                    ?>
                                    <tr>
                                        <td style="padding-left: 30px; <?php echo $verificaCancelada ?>">
                                            <?php echo $imagem;
                                            echo $at['numseq'] . ' - ' . $at['nomatividadecronograma'] ?>
                                        </td>
                                        <td style="<?php echo $verificaCancelada ?>; font-size: 11px;">
                                            <?php if (count($at['predecessoras']) > 0) {
                                                $array = $at['predecessoras'];
                                                $arrayCount = count($array);
                                                $i = 0;
                                                foreach ($at['predecessoras'] as $pr) {
                                                    if (++$i === $arrayCount) { // fazemos isto para todas as voltas menos para a ultima
                                                        echo $pr['numseq'];
                                                        continue;
                                                    }
                                                    echo $pr['numseq'] . ', ';
                                                }
                                            } ?>
                                        </td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo $at['datiniciobaseline'] ?>
                                            a <?php echo $at['datfimbaseline'] ?></td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo $at['diasbaseline'] ?></td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo $at['vlratividade'] ?></td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo $at['datinicio'] ?>
                                            a <?php echo $at['datfim'] ?></td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo $at['numdiasrealizados'] ?></td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo $at['numpercentualconcluido'] ?>
                                            %
                                        </td>
                                        <td style="<?php echo $verificaCancelada ?>"><?php echo @$at['desemail'] = $at['desemail'] ? $at['desemail'] : '' ?></td>
                                        <?php $sinal = (int)$at['numpercentualconcluido'] == 100 ? '#cccccc' : $sinal; ?>
                                        <td style="text-align: right; padding-right:5px;"
                                            bgcolor="<?php echo $sinal; ?>"> <?php echo $at['prazo'] ?> dias
                                        </td>
                                    </tr>
                                <?php endforeach;
                            endif; ?>
                            <?php endforeach;
                        endif; ?>
                        <?php endforeach; endif; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="9"><?php echo $this->projeto['contGrupo'] ?>
                            grupo(s), <?php echo $this->projeto['contEntrega'] ?> entrega(s)
                            e <?php echo $this->projeto['contAtividade'] ?> atividade(s)
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;width: 800px;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>

        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>3. PLANO DE RECURSOS HUMANOS</h5>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>3.1 EQUIPE DO PROJETO</h5>
            </td>
        </tr>
        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table style="width: 100%;border-collapse: collapse;" border="1" cellpadding="1" cellspacing="1">
                    <colgroup>
                        <col style="width: 30%">
                        <col style="width: 15%">
                        <col style="width: 15%">
                        <col style="width: 15%">
                        <col style="width: 25%">
                    </colgroup>
                    <thead>
                    <tr class="" style="border:0.1mm solid #220044; background-clip: border-box;">
                        <td><b>NOME</b></td>
                        <td><b>FUN&Ccedil;&Atilde;O NO PROJETO</b></td>
                        <td><b>TELEFONE</b></td>
                        <td><b>E-MAIL</b></td>
                        <td><b>OBSERVA&Ccedil;&Atilde;O</b></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($this->projetos->partes->getIterator() as $parte):
                        if (empty($parte['idparteinteressada']) == false):
                            ?>
                            <tr valign="top">
                                <td style="width: 30%"><?php echo $parte['nomparteinteressada']; ?></td>
                                <td style="width: 15%"><?php echo $parte['nomfuncao']; ?></td>
                                <td style="width: 15%"><?php echo $parte['destelefone']; ?></td>
                                <td style="width: 15%"><?php echo $parte['desemail']; ?></td>
                                <td style="width: 25%"><?php echo $parte['observacao'] ?></td>
                            </tr>
                        <?php else: ?>
                            <tr>
                                <td colspan="5">Nenhum registro encontrado.</td>
                            </tr>
                        <?php
                        endif;
                    endforeach;
                    ?>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;width: 800px;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>

        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>4. PLANO DE COMUNICA&Ccedil;&Otilde;ES</h5>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>4.1 MATRIZ DE COMUNICA&Ccedil;&Atilde;O </h5>
            </td>
        </tr>
        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table style="width: 100%;border-collapse: collapse;" border="1" cellpadding="1" cellspacing="1">
                    <colgroup>
                        <col style="width: 2px">
                        <col style="width: 35px">
                        <col style="width: 100px">
                        <col style="width: 100px">
                        <col style="width: 50px">
                    </colgroup>
                    <thead>
                    <tr class="" style="width: 100%; border:0.1mm solid #220044; background-clip: border-box;">
                        <td><b>O QUE SER&Aacute; INFORMADO</b></td>
                        <td><b>QUEM SER&Aacute; INFORMADO</b></td>
                        <td><b>QUAL A ORIGEM</b></td>
                        <td><b>QUAL A FREQU&Ecirc;NCIA</b></td>
                        <td><b>COMO SER&Aacute; TRANSMITIDA</b></td>
                        <td><b>ONDE SER&Aacute; ARMAZENADA</b></td>
                        <td><b>QUEM SER&Aacute; O RESPONS&Aacute;VEL</b></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($this->comunica as $comunicacao):

                        if (empty($comunicacao['idcomunicacao']) == false): ?>
                            <tr valign="top">
                                <td><?php echo $comunicacao['desinformacao']; ?></td>
                                <td><?php echo $comunicacao['desinformado']; ?></td>
                                <td><?php echo $comunicacao['desorigem']; ?></td>
                                <td><?php echo $comunicacao['desfrequencia']; ?></td>
                                <td><?php echo $comunicacao['destransmissao']; ?></td>
                                <td><?php echo $comunicacao['desarmazenamento']; ?></td>
                                <td><?php echo $comunicacao['nomresponsavel']; ?></td>
                            </tr>
                        <?php
                        endif;
                    endforeach;
                    if (empty($comunicacao['idcomunicacao']) == true):
                        ?>
                        <tr>
                            <td colspan="7">Nenhum registro encontrado.</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>5. PLANO DE RISCOS</h5>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;padding-bottom: 20px;">
                <h5>5.1 MATRIZ DE RISCOS </h5>
            </td>
        </tr>
        <tr align="center" style="padding-bottom: 20px;">
            <td style="padding-left: 20px;">
                <table style="width: 100%;border-collapse: collapse;" border="1" cellpadding="1" cellspacing="1">
                    <colgroup>
                        <col style="width: 2px">
                        <col style="width: 35px">
                        <col style="width: 100px">
                        <col style="width: 100px">
                        <col style="width: 50px">
                    </colgroup>
                    <thead>
                    <tr class="" style="width: 100%; border:0.1mm solid #220044; background-clip: border-box;">
                        <td><b>RISCO</b></td>
                        <td><b>DESCRI&Ccedil;&Atilde;O DO RISCO</b></td>
                        <td><b>CONSEQU&Ecirc;NCIA DO RISCO</b></td>
                        <td><b>PxI</b></td>
                        <td><b>TIPO CONTRAMEDIDA</b></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($this->risco as $riscos):
                        $risco = $riscos['domcorrisco'];
                        switch ($risco) {
                            case  1:
                                $risco = "<b>" . 'Alto' . "</b>";
                                break;
                            case  2:
                                $risco = "<b>" . 'M&eacute;dio' . "</b>";
                                break;
                            case 3:
                                $risco = "<b>" . 'Baixo' . "</b>";
                                break;
                        };
                        if (empty($riscos['idrisco']) == false): ?>
                            <tr valign="top">
                                <td><?php echo $riscos['norisco']; ?></td>
                                <td><?php echo $riscos['desrisco']; ?></td>
                                <td><?php echo $riscos['desconsequencia']; ?></td>
                                <td><?php echo $risco; ?></td>
                                <td><?php echo $riscos['notipocontramedida']; ?></td>
                            </tr>
                        <?php
                        endif;
                    endforeach;
                    if (empty($riscos['idrisco']) == true):
                        ?>
                        <tr>
                            <td colspan="5">Nenhum registro encontrado.</td>
                        </tr>
                    <?php
                    endif;
                    ?>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr align="left">
            <td style="text-align:left;width: 800px;">
                <div style="page-break-before: always;">&nbsp;</div>
            </td>
        </tr>

        <div align="left" class="span6" style="page-break-before: always; margin-top: 60px; margin-bottom: 20px">
            <h5>6. APROVA&Ccedil;&Atilde;O DO PATROCINADOR</h5>
        </div>
        <div align="left" style="margin-top: 10px">
            <table class="span10" border="1" WIDTH='90%'>
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->projetos->nompatrocinador; ?></td>
                    <td>____________________________________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Patrocinador</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span6" style="margin-top: 60px; margin-bottom: 20px">
            <h5>7. CI&Ecirc;NCIA DO GERENTE DE PROJETO</h5>
        </div>
        <div align="left" style="margin-top: 10px">
            <table class="span10" border="1" WIDTH='90%'>
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->projetos->nomgerenteprojeto; ?></td>
                    <td>____________________________________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Gerente de Projeto</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
                </tbody>

                <tbody style="text-align: center;">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->projetos->nomgerenteadjunto; ?></td>
                    <td>____________________________________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Gerente Adjunto</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
                </tbody>
            </table>
        </div>
    </table>
</div>
