<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <?php echo $this->headTitle('Chopp Dobrado'); ?>
    <?php
    // Framework CSS
    $this->headLink()
        ->prependStylesheet($this->baseUrl('/css/blueprint/ie.css'), 'screen, projection', 'IE lt 8')
        ->prependStylesheet($this->baseUrl('/css/blueprint/screen.css'))
        ->appendStylesheet($this->baseUrl('/css/choppdobrado.css'))
        ->appendStylesheet($this->baseUrl('/css/form.css'))
        ->appendStylesheet($this->baseUrl('/css/layout_login.css'));

    ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->inlineScript(); ?>
</head>
<body>
<div id="header">
    <div id="topo" class="container">
        <div class="span-5 first">
            <h1>Chopp dobrado</h1>
        </div>
        <div id="menu" class="span-6 last">
        </div><!--menu-->
    </div>
</div>
<div id="geral">
    <div id="conteudo" class="container">
        <div class="span-14">
            <h2>Avisos</h2>
            <p>
                fjsd flsdkjf ;lasdkjf alsdkjf lasdkjf ;alsdjf;jf dsjflaskd jflaksdjf ;alsdkjf; asldkfjsadl;kfja;sld fj;a
                fjsd flsdkjf ;lasdkjf alsdkjf lasdkjf ;alsdjf;jf dsjflaskd jflaksdjf ;alsdkjf; asldkfjsadl;kfja;sld fj;a
                fjsd flsdkjf ;lasdkjf alsdkjf lasdkjf ;alsdjf;jf dsjflaskd jflaksdjf ;alsdkjf; asldkfjsadl;kfja;sld fj;a
                fjsd flsdkjf ;lasdkjf alsdkjf lasdkjf ;alsdjf;jf dsjflaskd jflaksdjf ;alsdkjf; asldkfjsadl;kfja;sld fj;a
                fjsd flsdkjf ;lasdkjf alsdkjf lasdkjf ;alsdjf;jf dsjflaskd jflaksdjf ;alsdkjf; asldkfjsadl;kfja;sld fj;a
                fjsd flsdkjf ;lasdkjf alsdkjf lasdkjf ;alsdjf;jf dsjflaskd jflaksdjf ;alsdkjf; asldkfjsadl;kfja;sld fj;a
            </p>
        </div>
        <div id="conteudoLogin" class="span-8">
            <h3><?php echo $this->escape($this->title); ?></h3>
            <?php echo $this->flashMessages(); ?>
            <?php echo $this->layout()->content; ?>
        </div>
    </div><!--conteudo-->
</div><!--container-->
</div><!-- geral -->
<div id="rodape">
    <div id="rodape_info">
        <div class="rodape_content">
            algumas informaçoes
        </div>
    </div>
    <div id="rodape_copy">
        <div class="rodape_content">
            <p>Copyright 2012 - <?php echo date('Y'); ?> Chopp Dobrado. Todos os direitos reservados.</p>
        </div>
    </div>
</div><!--rodape-->
</body>
</html>