<ul class="nav pull-right">
    <li><a href="#">Link</a></li>
    <li class="divider-vertical"></li>
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Wilton Barbosa <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <!--
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            -->
            <li><a href="#">Sair</a></li>
        </ul>
    </li>
</ul>