<div class="region-center">
    <div class="portlet portlet-cinza">
        <div class="content">
            <div class="row-fluid">
                <div class="portlet portlet-cinza span">
                    <div class="title">Resposta</div>
                    <div class="content"><?php echo $this->resposta['desresposta']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="portlet portlet-cinza span4">
                    <div class="title">Ordem</div>
                    <div class="content"><?php echo $this->resposta['numordem']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="portlet portlet-cinza span3">
                    <div class="title">Situa&ccedil;&atilde;o</div>
                    <div class="content"><?php echo $this->resposta['flaativo']; ?>&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</div>
