<?php $frmAttrPergunta = $this->form->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <form id="<?php echo $frmAttrPergunta['id']; ?>"
              name="<?php echo $frmAttrPergunta['id']; ?>"
              action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $frmAttrPergunta['method']; ?>">    
            <?php echo $this->form->idresposta ?>
            <div class="row-fluid">                
                <div class="span">
                    <label for="desfrase">Pergunta</label>
                    <div id="desfrase" style=" padding: 5px; border-radius: 5px; font-size: 12px" class="input-selecionado">
                        <?php echo $this->desfrase ?>
                    </div>
                    <br/>
                </div>
            </div>
            <div class="row-fluid">                                                                       
                <div class="span">
                    <?php echo $this->form->desresposta ?>
                </div>
            </div>
            <div class="row-fluid"> 
                <div class="span3">
                    <?php echo $this->form->numordem ?>
                </div>
            </div>
            <div class="row-fluid"> 
                <div class="span2">
                    <?php echo $this->form->flaativo ?>                
                </div>
            </div>
        </form>
    </div>
</div>