<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$resultados = $this->resultados;
$totalPesquisas = $this->totalPesquisas['total'];
$enunciado = $this->enuciado;
?>
<?php if ($totalPesquisas > 0): ?>
    <div class="region-center">
        <h4 class="pagination-centered">Relat&oacute;rio Tabelado da Pesquisa</h4>
        <br/>
        <div class="content" style="font-size: 12px;">
            <div class="row-fluid">
                <div class="span2">
                    <div id="nomquestionario" style=" padding: 5px; border-radius: 5px; font-size: 12px;"
                         class="input-selecionado">
                        <strong>Pesquisas respondidas: </strong> <?php echo $this->totalPesquisas['total']; ?>
                    </div>
                </div>
                <div class="span10">
                    <div id="nomquestionario" style=" padding: 5px; border-radius: 5px; font-size: 12px;"
                         class="input-selecionado">
                        <strong>Pesquisa: </strong> <?php echo $resultados[0]['nomquestionario'] ?>
                    </div>
                </div>
            </div>
            <br/>
            <div class="row-fluid">
                <div class="span">
                    <table class="table table-bordered table-hover table-striped">
                        <thead style="background-color: #c7c7c7;">
                        <th>&numero;</th>
                        <th style="max-width: 200px;">Nome</th>
                        <?php foreach ($enunciado as $questao) : ?>
                            <th style="max-width: 150px;"><?php echo $questao['desfrase'] ?></th>
                        <?php endforeach; ?>
                        </thead>
                        <tbody>
                        <?php
                        $idresultado = '';
                        $numResultado = 1;
                        $primeiraLinha = true;
                        foreach ($resultados

                        as $resposta): ?>

                        <?php
                        //se for a primeira linha abre a <tr>
                        if ($primeiraLinha == true):
                        ?>
                        <tr>
                            <td><?php echo $numResultado; ?></td>
                            <td><?php echo $resposta['nome'] ?: 'An&ocirc;nimo' ?></td>
                            <td><?php echo $resposta['resposta']; ?></td>
                            <?php $numResultado++; ?>

                            <?php
                            //se for um novo resultado, ou seja, resposta de outro participante, fecha a linha anterior e abre uma nova
                            elseif ($resposta['idresultado'] != $idresultado && $primeiraLinha == false):
                            ?>
                        </tr>
                        <tr>
                            <td><?php echo $numResultado; ?></td>
                            <td><?php echo $resposta['nome'] ?: 'An&ocirc;nimo' ?></td>
                            <td><?php echo $resposta['resposta']; ?></td>
                            <?php $numResultado++; ?>

                            <?php
                            //se for o mesmo idresultado entao e outra resposta
                            else: ?>
                                <td><?php echo $resposta['resposta']; ?></td>
                            <?php endif; ?>

                            <?php $primeiraLinha = false; ?>
                            <?php $idresultado = $resposta['idresultado']; ?>
                            <?php endforeach; ?>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span">
                    <div style=" padding: 5px; border-radius: 5px; font-size: 12px;" class="input-selecionado">
                        <b>DPF - Departamento de Polícia Federal</b> - Gerado em: <?php echo date('d/m/Y - H:i:s') ?>
                    </div>
                    <br/>
                    <div style="text-align: right; margin-right: 20px;">
                        <a title="Imprimir relatório de pesquisa" btn btn-imprimir-cronograma
                           href="<?php echo $this->baseUrl('pesquisa/relatorio/imprimir-tabelado/idpesquisa/') . $resposta['idpesquisa']; ?>"
                           target="blank">
                            <i class="icon-print" style="border: #ccc 10px solid;"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php else : ?>
    <div class="region-center">
        <h4 class="pagination-centered">Relat&oacute;rio Tabelado da Pesquisa</h4>
        <br/>
        <div class="row-fluid">
            <div class="span alert alert-info" style="font-size: 12px;">
                Esta pesquisa ainda n&atilde;o foi respondida.
            </div>
        </div>
    </div>
<?php endif; ?>