<div class="region-center">
    <div class="portlet portlet-cinza">
        <div class="content">
            <input type="hidden" id="idata" name="idata" value="<?php echo $this->ata->idata; ?>">
            <div class="row">
                <div class="portlet portlet-cinza span5">
                    <div class="title">Assunto</div>
                    <div class="content"><?php echo $this->ata->desassunto; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span2">
                    <div class="title">Data Ata</div>
                    <div class="content"><?php echo $this->ata->datata; ?></div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Hora</div>
                    <div class="content"><?php echo $this->ata->hrreuniao; ?></div>
                </div>
                <div class="portlet portlet-cinza span5">
                    <div class="title">Local</div>
                    <div class="content"><?php echo $this->ata->deslocal; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Participantes</div>
                    <div class="content"><?php echo $this->ata->desparticipante; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Ponto Discutido</div>
                    <div class="content"><?php echo $this->ata->despontodiscutido; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Decis&atilde;o</div>
                    <div class="content"><?php echo $this->ata->desdecisao; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Ponto de Aten&ccedil;&atilde;o</div>
                    <div class="content"><?php echo $this->ata->despontoatencao; ?></div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Pr&oacute;ximo Passo</div>
                    <div class="content"><?php echo $this->ata->desproximopasso; ?></div>
                </div>
            </div>
        </div>
    </div>
</div>
