<?php
$frmAttr = $this->form->getAttribs();
?>
<form id="<?php echo $frmAttr['id']; ?>"
      name="<?php echo $frmAttr['id']; ?>"
      enctype="<?php echo $frmAttr['enctype']; ?>"
      action="<?php echo $this->form->getAction(); ?>"
      method="<?php echo $frmAttr['method']; ?>">
    <div class="row">
        <div class="span8">

            <div class="row">
                <div class="span6">
                    <?php echo $this->form->nomdocumento; ?>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8">

            <div class="row">
                <div class="span4">
                    <?php echo $this->form->idtipodocumento; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->datdocumento; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->flaativo; ?>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8">

            <label>Arquivo</label>
            <div class="btn-toolbar">
                <div class="btn-group">
                    <a class="btn btn_editar" title="Editar" href="<?php echo $this->url(array(
                        'action' => 'editar-arquivo',
                        'iddocumento' => $this->documento->iddocumento
                    )); ?>">
                        <i class="icon-upload"></i> Editar
                    </a>
                    <a class="btn" title="Clique para abrir" href="<?php echo $this->url(array(
                        'action' => 'abrir',
                        'iddocumento' => $this->documento->iddocumento
                    )); ?>">
                        <i class="icon-eye-open"></i> <?php echo $this->documento->nomdocumento; ?>
                    </a>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <?php echo $this->form->desobs; ?>
            <?php echo $this->form->iddocumento; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
            (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
        </div>
    </div>
</form>


