<script>
    
    $(function(){
        $.pnotify.defaults.history = false;
    
        $('.mask-date').datepicker({
                format: 'dd/mm/yyyy',
                language: 'pt-BR',
                changeMonth: true,
                changeYear: true
        });
    });
    
    function resetFormAta()
    {
        $("input, select, textarea").not('input#idprojeto, #form-diario-pesquisar :input').val('');
    }
   
</script>

<?php $frmAttr = $this->form->getAttribs(); ?>

<div class="region-center">
    <div class="portlet portlet-marron">
        <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                        name="<?php echo $frmAttr['id']; ?>"
                        action="<?php echo $this->form->getAction(); ?>"
                        method="<?php echo $frmAttr['method']; ?>">    
                    <div class="row">                                                                       
                        <?php echo $this->form->idprojeto ?>
                        <div class="span3">
                            <?php echo $this->form->domreferencia ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->datdiariobordo ?>                
                        </div>
                        <div class="span2">
                            <?php echo $this->form->domsemafaro ?>
                        </div>
                        <div class="span3">
                            <label for="no-usuario">Usuário</label>
                            <div id="no-usuario" style=" padding: 5px; border-radius: 5px;" class="input-selecionado">
                                <?php echo Zend_Auth::getInstance()->getIdentity()->nome; ?>
                            </div>
                        </div>               
                    </div>
                    <div class="row">
                        <div class="span5">
                            <?php echo $this->form->desdiariobordo ?>
                        </div>
                    </div>                    
                </form>
        </div>
    </div>
</div>