<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));
$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/linhatempo/index.js'), 'text/javascript');

$frmAttr = $this->formPesquisar->getAttribs();
?>
<?php if ($this->msgimpressao): ?>
    <script type="text/javascript">
        $(function () {
            $.pnotify({
                text: '<?php echo $this->msgimpressao; ?>',
                type: 'error',
                hide: false
            });
        });
    </script>
<?php endif; ?>

<div class="region-west">
    <?php echo $this->partial('_partials/menu-projeto.phtml',
        array('ativo' => 'linhatempo', 'idprojeto' => $this->idprojeto)) ?>
</div>

<div class="region-center">
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
        </div>
    </div>

    <table id="list-grid-linhatempo"></table>
    <div id="toolbar-grid-linhatempo"></div>
    <div id="pager-grid-linhatempo"></div>
</div>

<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Linha do Tempo - Pesquisar</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->formPesquisar->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <?php echo $this->formPesquisar->idprojeto ?>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->nompessoa ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->dsfuncaoprojeto ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="span4">
                            <?php echo $this->formPesquisar->descricao ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="span3" style="height: 95px !important;">
                            <div class="span2"
                                 style="width: 120px !important; height: 65px !important;margin-left:0px !important;">
                                <?php echo $this->formPesquisar->dtacaoinicial; ?>
                            </div>
                            <div class="span2"
                                 style="width: 100px !important; height: 65px !important;margin-left:5px !important;">
                                <?php echo $this->formPesquisar->dtacaofinal; ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formPesquisar->btnpesquisar ?>
                                <?php echo $this->formPesquisar->reset ?>
                                <?php echo $this->formPesquisar->close ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="dialog-detalhar" style="display: none"></div>