<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/processo/pacao/add.js'), 'text/javascript');
$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <div class="row">
        <div class="portlet portlet-marron span13">
            <div class="title">Cadastrar Ação de Projeto</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">

                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->idprojetoprocesso; ?>
                        </div>
                        <div class="span8">
                            <?php echo $this->form->nom_p_acao; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->datinicioprevisto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datinicioreal; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datterminoprevisto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datterminoreal; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nomresponsavel->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idresponsavel; ?>
                                    <?php echo $this->form->nomresponsavel->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idsetorresponsavel; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flacancelada; ?>
                        </div>
                    </div>
                    <div class="row grid-append" style="display: none;">

                    </div>
                    <div class="row">
                        <div class="span12">
                            <?php echo $this->form->des_p_acao; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span12">
                            <?php echo $this->form->id_p_acao; ?>
                            <?php echo $this->form->numseq; ?>
                            <?php echo $this->form->submit; ?>
                            <?php echo $this->form->reset; ?>
                        </div>
                    </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 10px;">
                    (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                    obrigatório
                </div>
            </div>
            </form>
        </div>
    </div>
</div>


