<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jqueryFileTree/jqueryFileTree.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.easing.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jqueryFileTree/jqueryFileTree.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.fileDownload.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/rud/index.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
$frmAttr2 = $this->formPasta->getAttribs();
?>

<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml',
        array('ativo' => 'rud', 'idprojeto' => $this->projeto->idprojeto));
    ?>
</div>
<div class="region-center">
    <?php echo $this->partial('_partials/projeto.phtml', array('projeto' => $this->projeto)); ?>
    <div class="portlet portlet-marron span12">
        <div class="title">Repositório Único de Documentos do Projeto</div>
        <div class="portlet portlet-marron span5" style="margin-top: 20px">
            <div class="title">Incluir Arquivo</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <input type="hidden" id="idprojeto" name="idprojeto"
                           value="<?php echo $this->projeto->idprojeto; ?>">
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->nompasta; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->arquivo1; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->arquivo2; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->arquivo3; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->arquivo4; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->arquivo5; ?>
                        </div>

                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->form->submit; ?>
                                <?php echo $this->form->reset; ?>
                                <?php //echo $this->form->close; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="portlet portlet-marron span6" style="margin-top: 20px; min-height: 378px; height: auto;">
            <div class="title">Arquivos e Pastas</div>
            <form id="<?php echo $frmAttr2['id']; ?>"
                  name="<?php echo $frmAttr2['id']; ?>"
                  action="<?php echo $this->formPasta->getAction(); ?>"
                  method="<?php echo $frmAttr2['method']; ?>">
                <input type="hidden" id="idprojeto" name="idprojeto" value="<?php echo $this->projeto->idprojeto; ?>">
                <div class="row">
                    <div class="span3" style="margin-left: 60px; margin-top: 12px;">
                        <?php echo $this->formPasta->pasta; ?>
                    </div>
                    <div class="btn-group" style="float: left; margin-top: 34px">
                        <?php echo $this->formPasta->submit; ?>
                        <?php echo $this->formPasta->reset; ?>
                        <?php //echo $this->form->close; ?>
                    </div>
                </div>
            </form>
            <div id="fileTree" class="span6" style="margin-bottom: 29px"></div>
            <div class="span6">
                <input type='button' id='excluir' name='excluir' value='Excluir'>
                <label id="msg" name="msg" style="display: none"></label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 20px;">
                (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
            </div>
        </div>
    </div>
</div>