<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/cadastro/perfil/associarperfil.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="region-west" id="perfil">
    <?php
    echo $this->partial('_partials/menu-lateral.phtml', array('id' => 'security'));
    ?>
</div>

<div class="region-center">
    <div class="row">
        <div class="portlet portlet-marron span10">
            <div class="title">Associar Perfil</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <div class="span3">
                            <div class="row container-pessoa">
                                <div class="span3">
                                    <div class="control-group">
                                        <?php echo $this->form->nompessoa->renderLabel(); ?>
                                        <div class="input-prepend ">
                                            <?php echo $this->form->pessoabutton; ?>
                                            <?php echo $this->form->nompessoa->renderViewHelper(); ?>
                                            <?php echo $this->form->idpessoa; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row grid-append" style="display: none;"></div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->idperfil ?>
                        </div>
                    </div>
                    <?php
                    // caso o usuário não for admin, não mostrar o perfil
                    $perfil = Zend_Auth::getInstance();
                    $identiti = $perfil->getIdentity()->perfilAtivo->idperfil;
                    if ($identiti == 1) { ?>
                        <div class="row">
                            <div class="span3"><?php echo $this->form->idescritorio; ?></div>
                        </div>
                    <?php } ?>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->idcadastrador; ?>
                            <?php echo $this->form->submit; ?>
                            <?php echo $this->form->reset; ?>
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 10px;">
                        (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                        obrigatório
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
