<?php if ($this->pageCount): ?>
    <div class="yui-skin-sam">
        <div class="pagination">
            <ul>
                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>"></a></li>
                <?php else: ?>
                    <li class="disabled"><span>Anterior</span></li>
                <?php endif; ?>

                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
                    <?php else: ?>
                        <li class="active"><span><?= $page; ?></span></li>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">Próximo &gt</a></li>
                <?php else: ?>
                    <li class="disabled"><span>Próximo</span></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>