<script>

    $(function() {
        $.pnotify.defaults.history = false;

        $('.mask-date').datepicker({
            format: 'dd/mm/yyyy',
            language: 'pt-BR',
            changeMonth: true,
            changeYear: true
        });

        $('.mask-date').mask('99/99/9999');

        $('#domcorimpacto, #domcorprobabilidade').change(function() {
            alteraRisco();
        });

    });

    function alteraRisco() {
        var probabilidade = $('#domcorprobabilidade').val();
        var impacto = $('#domcorimpacto').val();
        var opcao = null;

        if (impacto == '1' && probabilidade == '1') {
            opcao = '1';
        }
        else if (impacto == '3' || probabilidade == '3') {
            opcao = '3';
        } else {
            opcao = '2';
        }
        switch (opcao) {
            case '1':
                $('div#risco-badge.badge').attr('class', 'badge badge-important');
                break;
            case '2':
                $('div#risco-badge.badge').attr('class', 'badge badge-warning');
                break;
            case '3':
                $('div#risco-badge.badge').attr('class', 'badge badge-success');
                break;
            default:
                $('div#risco-badge.badge').attr('class', 'badge');
                break;
        }
        $('#domcorrisco').val(opcao);
        return;
    }

    function resetFormRisco()
    {
        $("input, select, textarea").not('input#idprojeto, #form-risco-pesquisar :input').val('');
    }

</script>


<?php $frmAttrRisco = $this->formRisco->getAttribs(); ?>

<div class="region-center">
    <div class="portlet">
        <form id="<?php echo $frmAttrRisco['id']; ?>"
              name="<?php echo $frmAttrRisco['id']; ?>"
              action="<?php echo $this->formRisco->getAction(); ?>"
              method="<?php echo $frmAttrRisco['method']; ?>">    
            <div class="row">                                                                       
                <?php echo $this->formRisco->idprojeto ?>
                <?php echo $this->formRisco->domcorrisco ?>
                <div class="span3">
                    <?php echo $this->formRisco->norisco ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->datdeteccao ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->idorigemrisco ?>                
                </div>
                <div class="span3">
                    <?php echo $this->formRisco->idetapa ?>
                </div>
            </div>
            <div class="row">
                <div class="span3">
                    <?php echo $this->formRisco->idtiporisco ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->domcorprobabilidade ?>
                </div>               
                <div class="span2">
                    <?php echo $this->formRisco->domcorimpacto ?>
                </div>
                <div class="span1">
                    <div class="control-group">
                        <label class="control-label">&nbsp</label>
                        <div id="risco-badge" class="badge" >Risco</div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="span10">
                    <?php echo $this->formRisco->desrisco ?>
                </div>
            </div>
            <div class="row">
                <div class="span5">
                    <?php echo $this->formRisco->descausa ?>
                </div>
                <div class="span5">
                    <?php echo $this->formRisco->desconsequencia ?>
                </div>
            </div>
            <div class="row">
                <div class="span">
                    <?php echo $this->formRisco->domtratamento ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->flariscoativo ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->datencerramentorisco ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->flaaprovado ?>
                </div>
                <div class="span2">
                    <?php echo $this->formRisco->datinatividade ?>
                </div>
            </div>
        </form>
    </div>
</div>