<div class="region-center">
    <div class="portlet portlet-cinza">
        <div class="content">
            <div class="row">
                <input type="hidden" name="idrisco" value="<?php echo $this->risco['idrisco'] ?>">
                <div class="portlet portlet-cinza span3">
                    <div class="title">Título Risco</div>
                    <div class="content"><?php echo $this->risco['norisco']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Detec&ccedil;&atilde;o</div>
                    <div class="content"><?php echo $this->risco['datdeteccao']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Origem</div>
                    <div class="content"><?php echo $this->risco['desorigemrisco']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Etapa</div>
                    <div class="content"><?php echo $this->risco['dsetapa']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span3">
                    <div class="title">Tipo</div>
                    <div class="content"><?php echo $this->risco['dstiporisco']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Probabilidade</div>
                    <div class="content"><?php echo $this->risco['domcorprobabilidade']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Impacto</div>
                    <div class="content"><?php echo $this->risco['domcorimpacto']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span2">
                    <div class="title">Risco</div>
                    <div class="content"><?php echo $this->risco['domcorrisco']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Descri&ccedil;&atilde;o</div>
                    <div class="content"><?php echo $this->risco['desrisco']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Causa</div>
                    <div class="content"><?php echo $this->risco['descausa']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span9">
                    <div class="title">Consequ&ecirc;ncia</div>
                    <div class="content"><?php echo $this->risco['desconsequencia']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span3">
                    <div class="title">Tratamento</div>
                    <div class="content"><?php echo $this->risco['domtratamento']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span3">
                    <div class="title">Ativo?</div>
                    <div class="content"><?php echo $this->risco['flariscoativo']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span3">
                    <div class="title">Data encerramento</div>
                    <div class="content"><?php echo $this->risco['datencerramentorisco']; ?>&nbsp;</div>
                </div>
            </div>
            <div class="row">
                <div class="portlet portlet-cinza span3">
                    <div class="title">Risco aprovado pelo GP?</div>
                    <div class="content"><?php echo $this->risco['flaaprovado']; ?>&nbsp;</div>
                </div>
                <div class="portlet portlet-cinza span3">
                    <div class="title">Data Inatividade</div>
                    <div class="content"><?php echo $this->risco['datinatividade']; ?>&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</div>
