<?php
header("Expires: Tue, 03 Jul 2001 06:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Connection: close");
?><!doctype html>
<html xmlns:ng="http://angularjs.org" ng-app>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headTitle('Coger Doc'); ?>
    <?php
    // Framework CSS
    $this->headLink()
        ->appendStylesheet($this->baseUrl('/js/library/angular/ui/build/angular-ui.css'), 'screen, projection', 'IE 7');
    $this->headScript()
        //->appendFile($this->baseUrl('/js/library/angular/ui/angular-ui-ieshiv.min.js'))
        ->appendFile($this->baseUrl('/js/library/angular/angular.min.js'))
        //->appendFile($this->baseUrl('/js/library/angular/ui/build/angular-ui.min.js'))
        //->appendFile($this->baseUrl('/js/library/angular/ui/common/module.js'))
        ->appendFile($this->baseUrl('/js/app/main.js'));
    ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->inlineScript(); ?>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">

            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <!-- Be sure to leave the brand out there if you want it shown -->
            <a class="brand" href="#">Coger doc</a>

            <!-- Everything you want hidden at 940px or less, place within here -->
            <div class="nav-collapse collapse">
                <!-- .nav, .navbar-search, .navbar-form, etc -->
                <?= $this->navigation()->menu()->setPartial('navigation_twitter.phtml')->render(); ?>
                <!--
                        <ul class="nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
                                    Documentos<b class='caret'></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url(array(
                    'module' => 'default',
                    'controller' => 'documento',
                    'action' => 'add'
                )); ?>">Cadastrar</a></li>
                                    <li><a href="<?php echo $this->url(array(
                    'module' => 'default',
                    'controller' => 'documento',
                    'action' => 'pesquisar'
                )); ?>">Pesquisar</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
                                    Administra&ccedil;&atilde;o<b class='caret'></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/articles">List all articles</a></li>
                                    <li><a href="/articles/new">New article</a></li>
                                </ul>
                            </li>
                        </ul>
                        -->

                <?php echo $this->usuario(); ?>
            </div>
        </div>
    </div>
</div>
<!--
<div class="container-fluid">
    <div class="row-fluid">

    </div>
</div>
<div id="header">
</div>
-->
<div id="geral">
    <div id="conteudo" class="container">
        <div class="span12">
            <div class="row">
                <?= $this->navigation()
                    ->breadcrumbs()
                    ->setRenderInvisible(true)
                    //->setMinDepth(0)
                    //->setMaxDepth(10)
                    ->setPartial('navigation_twitter_bread.phtml');
                ?>
            </div>
            <h2><?php echo $this->escape($this->title); ?></h2>
            <?php echo $this->flashMessages(); ?>
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div><!-- geral -->
<div id="rodape">
    <div id="rodape_info">
        <div class="rodape_content">
            algumas informaçoes
        </div>
    </div>
    <div id="rodape_copy">
        <div class="rodape_content">
            <!--<p>Copyright 2012 - <?php echo date('Y'); ?> Chopp Dobrado. Todos os direitos reservados.</p>-->
        </div>
    </div>
</div><!--rodape-->
</body>
</html>