<?php
header("Expires: Tue, 03 Jul 2001 06:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Connection: close");
?><!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headTitle('GEPNET 2'); ?>
    <script type="text/javascript">
        var base_url = "<?php echo $this->baseUrl(); ?>";
    </script>
    <?php
    // Framework CSS
    $this->headLink()
        ->prependStylesheet($this->baseUrl('/js/library/bootstrap/css/bootstrap-responsive.min.css'),
            'screen, projection')
        ->prependStylesheet($this->baseUrl('/js/library/bootstrap/css/bootstrap.min.css'), 'screen, projection')
        ->appendStylesheet($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/css/custom-theme/jquery-ui-1.8.24.custom.css',
            'screen, projection'))
        ->appendStylesheet($this->baseUrl('/js/library/jquery.layout-default.css'))
        ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.default.css'))
        ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/icons/jquery.pnotify.default.icons.css'))
        ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
        ->appendStylesheet($this->baseUrl('/js/library/kendoui.web/styles/kendo.common.min.css'))
        ->appendStylesheet($this->baseUrl('/js/library/kendoui.web/styles/kendo.bootstrap.min.css'))
        ->appendStylesheet($this->baseUrl('/css/layout.css'), 'screen, projection');
    // Library JS
    $this->headScript()
        ->prependFile($this->baseUrl('/js/layout.js'))
        ->prependFile($this->baseUrl('/js/library/jquery.layout.min.js'))
        ->prependFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/js/jquery-ui-1.8.24.custom.min.js'))
        //->prependFile($this->baseUrl('/js/library/jquery-migrate-1.1.0.js'))
        // ->prependFile($this->baseUrl('/js/library/kendoui.web/js/jquery.min.js'))
        ->prependFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/js/jquery-1.8.2.min.js'))
        ->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
        ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
        //->appendFile($this->baseUrl('/js/library/bootstrap/js/bootstrap.min.js'))
        ->appendFile($this->baseUrl('/js/library/kendoui.web/js/kendo.core.min.js'))
        ->appendFile($this->baseUrl('/js/library/kendoui.web/js/kendo.popup.min.js'))
        ->appendFile($this->baseUrl('/js/library/kendoui.web/js/kendo.menu.min.js'));
    ?>
    <?php echo $this->headLink(); ?>
    <?php //echo $this->jquery(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->inlineScript(); ?>
</head>
<body>
<div class="ui-layout-north" style="overflow:visible;">
    <div id="portal-header">
        <?php echo $this->header(); ?>
        <?php echo $this->usuario(); ?>
    </div>
    <div class="navbar" style="overflow:visible;">
        <?php echo $this->navigation()->menu(); ?>
    </div>
    <?php echo $this->navigation()
        ->breadcrumbs()->setRenderInvisible(true)
        ->setPartial('navigation_twitter_bread.phtml')->render();

    //->setMinDepth(0)
    //->setMaxDepth(10)
    ?>
</div>

<div class="ui-layout-center" style="overflow:visible;">
    <h2><?php echo $this->escape($this->title); ?></h2>
    <?php echo $this->layout()->content; ?>

    <?php
    //echo $this->partial('_partials/novos-recursos.phtml', array('dados' => $this->dados));
    ?>
</div>


<?php echo $this->footer(); ?>
<div id="dialog-perfil">
    <?php
    echo $this->action('mudar-perfil', 'index', 'default');
    ?>
</div>
<!-- jquery layout -->
</body>
</html>