<?php
header("Expires: Tue, 03 Jul 2001 06:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Connection: close");
?><!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headTitle('GEPNET 2'); ?>
    <script type="text/javascript">
        var base_url = "<?php echo $this->baseUrl(); ?>";
    </script>
    <?php
    // Framework CSS
    $this->headLink()
        ->prependStylesheet($this->baseUrl('/css/index.css'), 'screen, projection')
        ->prependStylesheet($this->baseUrl('/css/layout.css'), 'screen, projection')
        ->prependStylesheet($this->baseUrl('/js/library/bootstrap/css/bootstrap-responsive.min.css'),
            'screen, projection')
        ->prependStylesheet($this->baseUrl('/js/library/bootstrap/css/bootstrap.min.css'), 'screen, projection')
        ->appendStylesheet($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/css/custom-theme/jquery-ui-1.8.24.custom.css',
            'screen, projection'))
        ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.default.css'))
        ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/icons/jquery.pnotify.default.icons.css'));
    // Library JS
    $this->headScript()
        ->prependFile($this->baseUrl('/js/login.js'))
        ->prependFile($this->baseUrl('/js/index.js'))
        ->prependFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/js/jquery-ui-1.8.24.custom.min.js'))
        ->prependFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/js/jquery-1.8.2.min.js'))
        ->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript');
    ?>
    <?php echo $this->headLink(); ?>
    <?php //echo $this->jquery(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->inlineScript(); ?>
</head>
<body>
<div id="portal-header">
    <?php echo $this->header(); ?>
    <?php echo $this->usuario(); ?>
</div>
<div id="geral">
    <div id="conteudo" class="container-fluid ">
        <h2><?php echo $this->escape($this->title); ?></h2>
        <?php echo $this->flashMessages(); ?>

        <div class="content-body">
            <?php echo $this->layout()->content; ?>
        </div>

    </div>
</div><!-- geral -->
<?php echo $this->footer(); ?>
</body>
</html>