<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));
//->appendStylesheet($this->baseUrl('/css/app/projeto/termoaceite/add.css')) /*SAPS 110567*/
//;

$this->headScript()->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'),
    'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/projeto/licao/index.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/licao/add.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>

<script>
    $(document).ready(function () {

        $('#associada').hide();
        $('#idassociada').change(function () {
            if ($('#idassociada').val() == '1') {
                $('#associada').show();
            } else {
                $('#associada').hide();
            }
        });

    });
</script>
<div class="region-center">
    <div class="ui-dialog-content ui-widget-content">
        <form id="<?php echo $frmAttr['id']; ?>"
              name="<?php echo $frmAttr['id']; ?>"
              action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $frmAttr['method']; ?>">
            <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto; ?>"/>

            <div class="row" style="padding: 10px 0;">
                <div class="span8"><strong> Objeto: </strong>
                    <p> <?php echo $this->dadosProjeto->desprojeto ?></p></div>
                <div class="span8"><strong> Objetivo: </strong>
                    <p> <?php echo $this->dadosProjeto->desobjetivo ?></p></div>
            </div>
            <div class="row">
                <div class="span4">
                    <?php echo $this->form->idassociada ?>
                </div>
                <div class="span8" id="associada">
                    <?php echo $this->form->identrega ?>
                </div>
                <div class="span8">
                    <?php echo $this->form->desresultadosobtidos ?>
                </div>
                <div class="span8">
                    <?php echo $this->form->despontosfortes ?>
                </div>
                <div class="span8">
                    <?php echo $this->form->despontosfracos ?>
                </div>
                <div class="span8">
                    <?php echo $this->form->dessugestoes ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 20px;">
                    (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                    obrigatório
                </div>
            </div>
        </form>
    </div>
</div>


