<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
;

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    /*->appendFile($this->baseUrl('/js/library/handlebars.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/template.js'), 'text/javascript')*/
    ->appendFile($this->baseUrl('/js/app/projeto/licao/add.js'), 'text/javascript')
;

$frmAttr = $this->form->getAttribs();

?>
<div class="region-west">
    <?php echo $this->partial('_partials/menu-projeto.phtml', array('ativo' => 'licao', 'idprojeto' => $this->idprojeto));  ?>
</div>

<div class="region-center">

    <div class="row">
        <div class="portlet portlet-marron span-18">
            <div class="title">Cadastrar Lições Aprendidas </div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action=""
                      method="<?php echo $frmAttr['method']; ?>">
                    <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ;?>" />
                    <div class="row" style="padding: 10px 0;">
                        <div class="span8"> <strong> Objeto: </strong> <p> <?php echo $this->dadosProjeto->desprojeto ?></p></div>
                        <div class="span8"> <strong> Objetivo: </strong> <p> <?php echo $this->dadosProjeto->desobjetivo ?></p></div>
                    </div>
                    <div class="row">
                        <div class="span8">
                            <?php echo $this->form->identrega?>
                        </div>
                        <div class="span8">
                            <?php echo $this->form->desresultadosobtidos?>
                        </div>
                        <div class="span8">
                            <?php echo $this->form->despontosfortes?>
                        </div>
                        <div class="span8">
                            <?php echo $this->form->despontosfracos?>
                        </div>
                        <div class="span8">
                            <?php echo $this->form->dessugestoes?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span5">
                            <?php echo $this->form->submit ?>
                            <?php echo $this->form->reset ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

