<script>
    $(document).ready(function () {
        $('#idassociada').change(function () {
            if ($('#idassociada option:selected').val() == '2' || $('#idassociada option:selected').val() == null) {
                $('#associada').hide();
            } else {
                $('#associada').show();
            }
        });
    });
</script>
<div class="content">
    <form id="form-licao-editar"
          name="form-licao-editar"
          action="<?php echo $this->form->getAction(); ?>"
          method="post">
        <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
        <?php echo $this->form->idlicao; ?>
        <div class="row" style="padding: 10px 0;">
            <div class="span8"><strong> Objeto: </strong> <?php echo $this->dados->desprojeto ?></div>
            <div class="span8"><strong> Objetivo: </strong> <?php echo $this->dados->desobjetivo ?></div>
        </div>
        <div class="row">
            <div class="span4">
                <?php echo $this->form->idassociada ?>
            </div>
            <?php
            if (trim($this->tipoassociada) == (int)1): ?>
                <div class="span6" id="associada">
                    <?php echo $this->form->identrega; ?>
                </div>
            <?php else: ?>
                <div class="span6" id="associada" style="display:none">
                    <?php echo $this->form->identrega; ?>
                </div>
            <?php endif; ?>
            <div class="span8">
                <?php echo $this->form->desresultadosobtidos ?>
            </div>
            <div class="span8">
                <?php echo $this->form->despontosfortes ?>
            </div>
            <div class="span8">
                <?php echo $this->form->despontosfracos ?>
            </div>
            <div class="span8">
                <?php echo $this->form->dessugestoes ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 20px;">
                (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
            </div>
        </div>
    </form>
</div>