
<div class="content">
    <form id="form-licao-editar"
          name="form-licao-editar"
          action="<?php echo $this->form->getAction(); ?>"
          method="post">
        <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
        <?php echo $this->form->idlicao; ?>
        <div class="row" style="padding: 10px 0;">
            <div class="span8"> <strong> Objeto: </strong>  <?php echo $this->dados->desprojeto ?></div>
            <div class="span8"> <strong> Objetivo: </strong>  <?php echo $this->dados->desobjetivo ?></div>
        </div>
        <div class="row">
            <div class="span6">
                <?php echo $this->form->identrega; ?>
            </div>
            <div class="span8">
                <?php echo $this->form->desresultadosobtidos?>
            </div>
            <div class="span8">
                <?php echo $this->form->despontosfortes?>
            </div>
            <div class="span8">
                <?php echo $this->form->despontosfracos?>
            </div>
            <div class="span8">
                <?php echo $this->form->dessugestoes?>
            </div>
        </div>
    </form>
</div>