<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/handlebars.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/template.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/licao/index.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/licao/add.js'), 'text/javascript');
$linkImprimirTudo = '/projeto/licao/imprimir/idprojeto/' . $this->idprojeto . '/print/all';
?>
<div class="region-west">
    <?php echo $this->partial('_partials/menu-projeto.phtml',
        array('ativo' => 'licoes', 'idprojeto' => $this->idprojeto)); ?>
</div>

<div class="region-center">

    <div id="dados-projeto"></div>

    <div class="form-actions form-actions-mini">
        <a data-target="#dialog-cadastrar" class="btn cadastrar" title="Cadastrar" href="<?php echo $this->url(array(
            'module' => 'projeto',
            'controller' => 'licao',
            'action' => 'cadastrar'
        )); ?>" title="Cadastrar Li&ccedil;&atilde;o">
            Cadastrar
        </a>
        <div class="btn-group">
            <a href="<?php echo $this->baseUrl($linkImprimirTudo) ?>" class="btn print" title="Imprimir tudo"
               style="float: right;" target="blank"><i class="icon-print"></i> &nbsp;Imprimir Todas</a>
        </div>
    </div>
    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>
</div>

<div class="region-east">

    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar</div>
            <div class="content">
                <form id="form-licao-pesquisar"
                      name="form-licao-pesquisar"
                      action=""
                      method="post">
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->identrega ?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->form->submit; ?>
                                <?php echo $this->form->reset; ?>
                                <?php echo $this->form->close; ?>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->idprojeto; ?>"/>
                </form>
            </div>
        </div>
    </div>
</div>


<div id="dialog-cadastrar" style="display: none"></div>
<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>



