<?php

$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");

$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.default.css'))
    ->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/icons/jquery.pnotify.default.icons.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/versaoSistema/versao.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/versaoSistema/jQuery-QuickSearch.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/statusreport/index.js?' . time()), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/versaoSistema/versao.js?' . time()), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <!--            <a class="btn" href="<?php //echo $this->url(array('module' => 'projeto', 'controller' => 'tap', 'action' => 'add')); ?>">Incluir Termo de Abertura (TAP)</a>
            <a class="btn" href="<?php //echo $this->url(array('module' => 'projeto', 'controller' => 'statusreport', 'action' => 'index')); ?>">Status Report</a>-->
        </div>
    </div>

    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>

    <?php if (count($this->versaoHTML) > 0) { ?>
        <!-- Modal -->
        <div id="modalNotaVersao" class="modal hide fade portlet portlet-marron" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header nopadding">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;&nbsp;&nbsp;
                </button>
                <h3 id="myModalLabel">Vers&atilde;o Atual:&nbsp;<?php echo $this->versaoHTML->versao; ?> </h3>
            </div>
            <div class="modal-body">
                <?php echo $this->versaoHTML->corpoHTML; ?>
            </div>
        </div>
    <?php } ?>
</div>
<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4" style="padding: 5px 0px 0px 10px;">
            <div class="title">Consulta</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->form->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <input type="hidden" name="codobjetivo" id="codobjetivo" value="<?php echo $this->codobjetivo; ?>"/>
                    <input type="hidden" name="codacao" id="codacao" value="<?php echo $this->codacao; ?>"/>
                    <div class="row">
                        <div class="span">
                            <?php echo $this->form; ?>
                        </div>

                    </div>
            </div>
            </form>
        </div>
    </div>
</div>
</div>
<?php
/**
 *
 * @todo remover este link (abaixo) após a criação do menu
 */
?>
<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>