<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.3.2/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/planejamento/portfolio.css'));
$frmAttr = $this->form->getAttribs();
$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    //->appendFile($this->baseUrl('/js/app/planejamento/portfolio/index.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/planejamento/portfolio/portfolioestrategico.js'), 'text/javascript');
?>

<div class="region-center">
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a class="btn" href="<?php echo $this->url(array(
                'module' => 'planejamento',
                'controller' => 'portfolio',
                'action' => 'portfolioestrategico',
                array()
            )); ?>">Voltar</a>
        </div>
    </div>

    <table id="list2"></table>
    <div id="toolbar2"></div>
    <div id="pager2"></div>
</div>


<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar Projeto</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['name']; ?>"
                      method="<?php echo $frmAttr['method']; ?>"
                      action="">
                    <div class="row">
                        <div class="span2">
                            <?php echo $this->form->idescritorio; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idprograma; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->domstatusprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->nomprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idobjetivo; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idacao; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->cronogramadesatualizado; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->idnatureza; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->idsetor; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->flacopa; ?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->form->submit; ?>
                                <?php echo $this->form->reset; ?>
                                <?php echo $this->form->close; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

