<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/css/bootstrap.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.3.2/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/planejamento/portfolio.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/planejamento/portfolio/portfolioestrategico.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/knockout-2.2.1.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/globalize.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/dx.chartjs.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/planejamento/portfolio/portfolio-charts.js'), 'text/javascript');

?>
<div class="region-east">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar Escrit&oacute;rio</div>
            <div class="content">
                <form id="formPesquisar"
                      name="formPesquisar"
                      method="post"
                      action="<?php echo $this->baseUrl() ?>/planejamento/portfolio/portfolioestrategico">
                    <div class="row">
                        <div class="span">
                            <label>Escritório</label>
                            <select name="idescritorio">
                                <option value="">Todos</option>
                                <?php foreach ($this->selectEscritorio as $selectEscritorio) { ?>
                                    <option value="<?php echo $selectEscritorio['idescritorio']; ?>"><?php echo $selectEscritorio['nomescritorio']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="span3">
                            <?php echo $this->formPesquisar->nomprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php //escho $this->formPesquisar->idprograma; ?>
                        </div>
                        <div class="span3">
                            <?php //echo $this->formPesquisar->domstatusprojeto; ?>
                        </div>
                        <div class="span2">
                            <?php //echo $this->form->fladesatualizado; ?>
                        </div>

                        <div class="span2">
                            <?php echo $this->formPesquisar->idobjetivo; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->formPesquisar->idacao; ?>
                        </div>
                        <div class="span">
                            <?php echo $this->formPesquisar->idnatureza; ?>
                        </div>
                        <div class="span">
                            <?php //echo $this->form->flacopa; ?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formPesquisar->submit; ?>
                                <?php echo $this->formPesquisar->reset; ?>
                                <?php echo $this->formPesquisar->close; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="region-center">
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <!--            <a class="btn" href="<?php //echo $this->url(array('module' => 'projeto', 'controller' => 'tap', 'action' => 'add')); ?>">Incluir Termo de Abertura (TAP)</a>
            <a class="btn" href="<?php //echo $this->url(array('module' => 'projeto', 'controller' => 'statusreport', 'action' => 'index')); ?>">Status Report</a>-->
        </div>
    </div>
    <h5> PORTF&Oacute;LIO ESTRAT&Eacute;GICO DA ORGANIZA&Ccedil;&Atilde;O - <?php echo $this->escritorio->sigla; ?></h5>
    <div class="container-objetivos row" style="margin-left: 5px;">
        <?php $contAcao = 0;
        foreach ($this->portfolio as $obj): ?>
            <div class="span2 box-objetivo" id="<?php echo $obj['idobjetivo'] ?>">
                <div class="box-nome-objetivo">
                    <span style="margin: 0; padding-top: 5px;"><?php echo $obj['nomobjetivo'] ?></span> <br/>
                    <span style="font-weight: bold;"> (<?php echo $obj['totalProjetos'] ?>) </span>
                </div>

                <div class="box-acao">
                    <ul>
                        <?php if (count($obj['acoes']) > 1):
                            foreach ($obj['acoes'] as $acao): ?>
                                <li class="content item-acao" id="<?php echo $acao['idacao'] ?>">
                                    <span> <?php echo $acao['nomacao'] ?> </span> <br/>
                                    <span style="font-weight: bold;"> (<?php echo $acao['totalProjetos'] ?>)</span>
                                </li>
                                <?php $contAcao++;
                            endforeach;
                        endif; ?>
                    </ul>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="row" style="">
        <div class="portlet portlet-cinza span12">
            <div class="title">
                Total de Objetivos: <?php echo count($this->portfolio); ?> <br/>
                Total de A&ccedil;&otilde;es: <?php echo $contAcao; ?>
            </div>
        </div>
    </div>
    <?php
    if (isset($this->idprograma) && $this->idprograma != '') {
        foreach ($this->idprograma as $idprograma) {
            $grafico = $idprograma['idprograma'];
        }
    } else {
        $grafico = '';
    }

    ?>
    <div id="container-graficos">
        <input type="hidden" name="idprograma" id="idescritorio" value="<?php echo $grafico; ?>"/>
        <div class="row">
            <div class="portlet portlet-cinza span12">
                <div class="title"><?php echo $this->nomescritorio ?> </div>
                <div class="content">
                    <div id="chartContainer-orcamentario" style="min-width: 580px; min-height: 300px;"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="portlet portlet-cinza span8">
                <div class="title"><?php echo $this->nomescritorio ?> </div>
                <div class="content">
                    <div id="chartContainer-projetos-programa" style="min-width: 580px; min-height: 300px;"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="portlet portlet-cinza span8">
                <div class="title"><?php echo $this->nomescritorio ?> </div>
                <div class="content">
                    <div id="chartContainer-projetos-natureza" style="min-width: 580px; min-height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>

</div>