<?php echo $this->partial('_partials/relatorio-cabecalho.phtml'); ?>
<div id="content">
    <div align="left" class="span4" style="margin-top: 60px">
        <h5>1. ATA DE REUNI&Atilde;O</h5>
    </div>
    <div align="left" class="span4">
        <h5>1.1 PROJETO</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td>C&Oacute;DIGO DO PROJETO</td>
                <td><?php echo $this->projeto->nomcodigo; ?></td>
            </tr>
            <tr>
                <td>T&Iacute;TULO DO PROJETO</td>
                <td><?php echo $this->projeto->nomprojeto; ?></td>
            </tr>
            <tr>
                <td>GERENTE DE PROJETO</td>
                <td><?php echo $this->projeto->nomgerenteprojeto; ?></td>
            </tr>
            <tr>
                <td>GERENTE ADJUNTO</td>
                <td><?php echo $this->projeto->nomgerenteadjunto; ?></td>
            </tr>
            <tr>
                <td>PATROCINADOR</td>
                <td><?php echo $this->projeto->nompatrocinador; ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span4">
        <h5>1.2 PARTICIPANTES</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td><?php echo $this->projeto->ata->desparticipante; ?></td>
            </tr>
            <tr>
                <td><B>ASSINATURA:</B>_____________________________<br><br></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span4">
        <h5>1.3 ATA</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td>DATA DA REUNI&Atilde;O</td>
                <td><?php echo $this->projeto->ata->datata; ?></td>
            </tr>
            <tr>
                <td>LOCAL</td>
                <td><?php echo $this->projeto->ata->deslocal; ?></td>
            </tr>
            <tr>
                <td>ASSUNTO</td>
                <td><?php echo $this->projeto->ata->desassunto; ?></td>
            </tr>
            <tr>
                <td>PONTOS DISCUTIDOS</td>
                <td><?php echo $this->projeto->ata->despontodiscutido; ?></td>
            </tr>
            <tr>
                <td>DECIS&Otilde;ES</td>
                <td><?php echo $this->projeto->ata->desdecisao; ?></td>
            </tr>
            <tr>
                <td>OBSERVA&Ccedil;&Otilde;ES</td>
                <td><?php echo $this->projeto->ata->despontoatencao; ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span4">
        <h5>1.4 PR&Oacute;XIMOS PASSOS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 100%">
            </colgroup>
            <tbody>
            <tr>
                <td><?php
                    if ($this->projeto->ata->desproximopasso) {
                        echo $this->projeto->ata->desproximopasso;
                    } else {
                        echo "Nenhum registro encontrado.";
                    }
                    ?></td>
            </tr>
            </tbody>
        </table>
    </div>

</div>