<div class="row atividade" id="ativ<?php echo $this->atividade->idatividadecronograma; ?>"
     data-date="<?php echo $this->atividade->datiniciobaseline->toString('Ymd'); ?>">
    <div class="span1" style="width: 30px !important">
        <input type="radio" name="item_cronograma" class="item-cronograma" data-group=".btn-group-atividade"
               value="<?php echo $this->atividade->idatividadecronograma; ?>">
    </div>
    <div class="span4" style="margin-left: 0">
        <div class="container-entrega" style="padding-left: 40px;">
            <i class="icon-list-alt"></i> <?php echo $this->atividade->nomatividadecronograma; ?>
        </div>
    </div>
    <div class="span2">
        <?php echo $this->atividade->datiniciobaseline->toString('d/m/Y'); ?> à
        <?php echo $this->atividade->datfimbaseline->toString('d/m/Y'); ?>
    </div>
    <div class="span1">
        <?php echo $this->atividade->vlratividade; ?>
    </div>
    <div class="span1">
        <?php echo $this->atividade->datinicio->toString('d/m/Y'); ?>
    </div>
    <div class="span1">
        <?php echo $this->atividade->datfim->toString('d/m/Y'); ?>
    </div>
    <div class="span1">
        <?php echo $this->atividade->numpercentualconcluido; ?>%
    </div>
    <div class="span2">
        wilton.wbsj
    </div>
    <div class="span1">
        <span class="badge badge-<?php echo (int)$this->atividade->numpercentualconcluido == 100 ? "" : $this->atividade->retornaDescricaoPrazo($this->projeto->numcriteriofarol); ?>"
              title="<?php echo $this->atividade->retornaPrazoEmDias(); ?>">R</span>
    </div>
</div>