<div class="row entrega" id="entr<?php echo $this->entrega->idatividadecronograma; ?>">
    <div class="span1" style="width: 30px !important">
        <input type="radio" name="item_cronograma" class="item-cronograma" data-group=".btn-group-entrega"
               value="<?php echo($this->entrega->idatividadecronograma); ?>">
    </div>
    <div class="span4" style="margin-left: 0">
        <div class="container-entrega" style="padding-left: 20px;">
            <i class="icon-tag"></i> <?php echo($this->entrega->nomatividadecronograma); ?>
        </div>
    </div>
    <div class="span2">
        <?php echo $this->entrega->retornaDataInicioBaseLineEntrega(); ?> à
        <?php echo $this->entrega->retornaDataFimBaseLineEntrega(); ?>
    </div>
    <div class="span2">
        <?php echo $this->entrega->getCustoEntrega(); ?>
    </div>
</div>