<tr class="endereco">
    <td><a class="del-endereco" data-id="<?php echo $this->endereco['end_id']; ?>" href="<?php echo $this->baseUrl('/admin/estabelecimento/delendereco') ?>">Remover</a></td>
    <td>
        <div class="complemento"><?php echo $this->endereco['end_desc_complemento']; ?></div>
        <div class="end"><?php echo $this->endereco['bai_desc'], ', ', $this->endereco['cid_desc'], ', ', $this->endereco['uf_nm'], ', ', $this->endereco['uf_id'], ', ', $this->endereco['end_nr_cep']; ?></div>
        <div class="telefone"><strong>Tel: <?php echo $this->endereco['est_nr_fone']; ?></strong></div>
    </td>
</tr>