<?php
/**
 * @var Projeto_Model_Gerencia $this ->projeto
 */
?>
<div id="content">
    <div class="region-center">
        <div align="center">
            <div style="display: inline-block;text-align: center;"><img
                        src="data:image/png;base64,<?php echo $this->graficoGantt; ?>"
                        style="display: inline-block; width: auto; max-width: 373px;margin-right: 5px;"/>
            </div>
        </div>
    </div>
</div>