<?php
$infoIni = ($this->dados == 'informacoesiniciais') ? 'active' : "";
$infoTec = ($this->dados == 'informacoestecnicas') ? 'active' : "";
$resumo = ($this->dados == 'resumodoprojeto') ? 'active' : "";
?>
<div id="menutap" class="portlet span12">
    <ul class="nav nav-pills">
        <li class="<?php echo $infoIni ?>"><a class="link"
                                              href="<?php echo $this->url(array('action' => 'informacoesiniciais')) ?>">Informações
                Iniciais</a></li>
        <li class="<?php echo $infoTec ?>"><a class="link"
                                              href="<?php echo $this->url(array('action' => 'informacoestecnicas')) ?>">Informações
                Técnicas</a></li>
        <li class="<?php echo $resumo ?>"><a class="link"
                                             href="<?php echo $this->url(array('action' => 'resumodoprojeto')) ?>">Resumo
                do Projeto</a></li>
    </ul>
</div>