<?php
header("Cache-Control: no-cache, must-revalidate");
?>

<style type="text/css">

    /* .table td {
         width: 100%;
         border:0.1mm solid #220044 !important;
         background-clip: border-box;
     }

     ol{
          border:0.1mm solid #220044 !important;
         background-clip: border-box;
 }*/
</style>

<div align="center" style="margin-top: 170px">
    PLANO DE GERENCIAMENTO DO PROJETO
</div>
<div align="center" style="margin-top: 40px">
    <?php echo $this->projeto['nomcodigo']; ?>
</div>
<div align="center" style="margin-top: 40px">
    <?php echo $this->projeto['nomprojeto']; ?>
</div>
<div align="center" style="margin-top: 40px">
    <?php echo $this->projeto['desprojeto']; ?>
</div>
<div align="left" style="page-break-before: always; margin-top: 60px"></div>