<style type="text/css">

    .container-grupo {
        width: 1500px;
        border: 1px solid red;
    }

    .titulo-tabela {
        font-weight: bold;
    }

    .box-grupo {
        padding-top: 5px;
        float: left;
        margin-bottom: 20px;
    }

    .box-nome-grupo {
        font-size: 10px;
        font-weight: bold;
        padding: 2px;
        text-align: center;
        border: 2px solid #555;
        background: #aaa;
        min-height: 60px;
        height: 60px;
        max-height: 80px;
    }

    .box-entrega {
        margin: 8px 0;
    }

    .box-item-entrega {
        font-size: 10px;
        border: 1px solid #fff;
        margin: 5px 0;
        background: #ccc;
        padding: 3px;
    }


</style>

<div align="left" class="span4" style="margin-top: 60px">
    <h5>1. DECLARA&Ccedil;&Atilde;O DO ESCOPO/QUALIDADE</h5>
</div>
<div align="left" class="span4">
    <h5>1.1 ESTRUTURA ANAL&Iacute;TICA DO PROJETO - EAP </h5>
</div>
<div class="grupos-eap" style="width: 1270px; ">
    <?php if (isset($this->projetosEap['grupos']) && count($this->projetosEap['grupos']) > 0):
        foreach ($this->projetosEap['grupos'] as $gr):
            if (!empty($gr['idatividadecronograma'])) : ?>
                <div class="span2 box-grupo">
                    <div class="box-nome-grupo">
                        <span style="margin: 0; padding-top: 5px;"><?php echo $gr['nomatividadecronograma'] ?></span>
                    </div>
                    <?php if (isset($gr['entregas']) && count($gr['entregas']) > 0): ?>
                        <div class="box-entrega">
                            <?php foreach ($gr['entregas'] as $en):
                                if (!empty($en['idatividadecronograma'])) :?>
                                    <div class="span2 box-item-entrega ">
                                        <?php $prazo = (!empty($en['numpercentualconcluido'])) ? $en['numpercentualconcluido'] : 0; ?>
                                        <span class="badge badge-<?php echo (int)$prazo == 100 ? "" : $en['domcoratraso'] ?>"
                                              title=""><?php echo isset($en['atraso']) ? $en['atraso'] . ' dias' : "" ?></span>
                                        <?php echo $prazo; ?>% <?php echo $en['nomatividadecronograma']; ?>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endforeach;
    endif; ?>
</div>

<div style="width: 1270px; ">
    <a class="dicionario-eap" href="#"><h5>1.2 DICION&Aacute;RIO DA EAP E CRIT&Eacute;RIO DE ACEITA&Ccedil;&Atilde;O
            (QUALIDADE) </h5></a>
    <div class="quadro-dicionario-eap">
        <table class="table table-hover table-striped table-condensed" style="height: 100%; border-collapse: collapse;">
            <tr style="background-color: #ccc;">
                <td class="titulo-tabela">Identifica&ccedil;&atilde;o EAP</td>
                <td class="titulo-tabela">Descri&ccedil;&atilde;o</td>
                <td class="titulo-tabela">Crit&eacute;rio de Aceita&ccedil;&atilde;o/Desvio Aceit&aacute;vel
                    (Qualidade)
                </td>
                <td class="titulo-tabela">Respons&aacute;vel Pela Entrega</td>
                <td class="titulo-tabela">Respons&aacute;vel Pela Aceita&ccedil;&atilde;o</td>
            </tr>
            <tbody>
            <?php if (isset($this->projetosEap['grupos']) && count($this->projetosEap['grupos']) > 0):
                foreach ($this->projetosEap['grupos'] as $gr):
                    if (!empty($gr['idatividadecronograma'])) : ?>
                        <tr>
                            <td colspan="5" style="font-weight: bold;"><?php echo $gr['nomatividadecronograma'] ?></td>
                        </tr>
                        <?php if (isset($gr['entregas']) && count($gr['entregas']) > 0):
                            foreach ($gr['entregas'] as $en):
                                if (!empty($en['idatividadecronograma'])) :?>?>
                                    <tr>
                                        <td> <?php echo $en['nomatividadecronograma'] ?> </td>
                                        <td> <?php echo $en['desobs'] ?> </td>
                                        <td> <?php echo $en['descriterioaceitacao'] ?> </td>
                                        <td> <?php echo $en['nomparteinteressada'] ?> </td>
                                        <td> <?php echo $en['nomeresponsavelaceitacao'] ?> </td>
                                    </tr>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<div align="left" class="span4" style="margin-top: 60px">
    <h5>1.3 N&Atilde;O ESCOPO (O QUE N&Atilde;O SER&Aacute; FEITO)</h5>
</div>
<div align="left">
    <?php
    if (isset($this->projetos->desnaoescopo) && is_object($this->projetos)) {
        echo nl2br($this->projetos->desnaoescopo);
    } else {
        if (isset($this->projetos['desnaoescopo'])) {
            echo nl2br($this->projetos['desnaoescopo']);
        }
    } ?>
</div>

