<style type="text/css">

    table tr td {
        border: 0.1mm solid #220044;
        background-clip: border-box;
    }
</style>

<div align="left" class="span4" style="margin-top: 60px">
    <h5>1.2 DICION&Aacute;RIO DA EAP E CRIT&Eacute;RIO DE ACEITA&Ccedil;&Atilde;O (QUALIDADE)</h5>
</div>
<div align="center" style="margin-top: 20px">
    <table class="" style="width: 100%; border:0.1mm solid #220044;  background-clip: border-box;">
        <colgroup>
            <col style="width: 2px">
            <col style="width: 35px">
            <col style="width: 100px">
            <col style="width: 100px">
            <col style="width: 50px">
        </colgroup>
        <thead>
        <tr class="" style="width: 100%; border:0.1mm solid #220044; background-clip: border-box;">
            <td>ID</td>
            <td>IDENTIFICA&Ccedil;&Atilde;O EAP</td>
            <td>DESCRI&Ccedil;&Atilde;O</td>
            <td>CRIT&Eacute;RIO DE ACEITA&Ccedil;&Atilde;O/DESVIO ACEIT&Aacute;VEL (QUALIDADE)</td>
            <td>RESPONS&Aacute;VEL</td>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($this->cronograma as $entrega):
            ?>
            <tr>
                <td><?php echo $entrega['numseq']; ?></td>
                <td><?php echo $entrega['nomatividadecronograma']; ?></td>
                <td><?php echo (!empty($entrega['desobs'])) ? $entrega['desobs'] : ""; ?></td>
                <td><?php echo (!empty($entrega['descriterioaceitacao'])) ? $entrega['descriterioaceitacao'] : ""; ?></td>
                <td><?php echo (!empty($entrega['nomparteinteressada'])) ? $entrega['nomparteinteressada'] : "" ?></td>
            </tr>
        <?php
        endforeach;
        ?>
        </tbody>
    </table>
</div>

<div align="left" class="span4" style="margin-top: 60px">
    <h5>1.3 N&Atilde;O ESCOPO (O QUE N&Atilde;O SER&Aacute; FEITO)</h5>
</div>
<div align="left">
    <?php
    if (is_object($this->projetos) && (!empty($$this->projetos->desnaoescopo))) :
        echo nl2br($this->projetos->desnaoescopo);
    endif;
    ?>
</div>