<?php
$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");
?>
<div class="accordion" id="accordion2">
    <div class="accordion-heading title">
        <span style="font-weight: bold; color: #0088CC"><?php echo $this->projeto['nomcodigo'] ?> - <?php echo $this->projeto['nomprojeto'] ?></a> </span>
    </div>
    <div class="accordion-group">
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
                <strong>Resumo do projeto</strong>
                <table class="table table-striped table-bordered table-price" style="font-size: 8px !important;">
                    <colgroup>
                        <col style="width: 50px;">
                        <col style="width: 300px;">
                        <col style="width: 50px;">
                        <col style="width: 200px;">
                        <col style="width: 50px;">
                        <col style="width: 50px;">
                        <col style="width: 100px;">
                        <col style="width: 50px;">
                        <col style="width: 50px;">
                    </colgroup>
                    <tr>
                        <th>Patroci.:</th>
                        <td><?php echo $this->projeto['patrocinador']['nompessoa'] ?></td>
                        <th>Meta:</th>
                        <td><?php echo $this->projeto['datinicio'] ?>
                            a <?php echo $this->projeto['datfim'] . ' - ' . $this->projeto['metaEmDias'] . ' dias' ?></td>
                        <th>% concluído planejado:</th>
                        <td><?php echo $this->projeto['numpercentualprevisto'] ?>%</td>
                        <th>&Uacute;ltimo Relat&oacute;rio:</th>
                        <td><?php echo $this->projeto['ultimoStatusReport']['datacompanhamento'] ?></td>
                        <th>Atraso:</th>
                        <td>
                            <span class="badge badge-<?php echo (int)$this->projeto['numpercentualconcluido'] == 100 ? "" : $this->projeto['descricaoPrazo'] ?>"><?php echo $this->projeto['prazoEmDias'] ?> dias </span>
                        </td>
                    </tr>
                    <tr>
                        <th>Gerente:</th>
                        <td><?php echo $this->projeto['gerenteprojeto']['nompessoa'] ?></td>
                        <th>Tend&ecirc;ncia:</th>
                        <td><?php echo $this->projeto['datinicio'] . ' a ' . @mb_substr($this->projeto['ultimoStatusReport']['datfimprojetotendencia']->toString('d/m/Y'),
                                    0, 10) . ' - ' . $this->projeto['tendenciaEmDias'] . ' dias' ?></td>
                        <th>% concluído realizado:</th>
                        <td><?php echo $this->projeto['numpercentualconcluido'] ?>%</td>
                        <th>Status:</th>
                        <td><?php echo $this->projeto['ultimoStatusReport']['nomdomstatusprojeto'] ?></td>
                        <th>Risco:</th>
                        <td>
                            <span class="badge badge-<?php echo $this->projeto['descricaoRisco'] ?>"><?php echo $this->projeto['ultimoStatusReport']['nomdomcorrisco']; ?></span>
                        </td>
                    </tr>
                    <tr>
                        <th>Adjunto:</th>
                        <td><?php echo $this->projeto['gerenteadjunto']['nompessoa'] ?></td>
                        <th>Alinhamento Estrat&eacute;gico:</th>
                        <td colspan=""><?php echo $this->projeto['objetivo']['nomobjetivo'] ?>
                            <br/> <?php echo $this->projeto['acao']['nomacao'] ?></td>
                        <th>% de Marcos Concluído do Projeto:</th>
                        <td colspan=""><?php echo $this->projeto['percentualConcluidoMarco'] . "%"; ?></td>
                        <th>Nº do Processo:</th>
                        <td colspan=""><?php echo (!empty($this->projeto['numprocessosei'])) ? $this->projeto['numprocessosei'] : ""; ?></td>
                        <th>Natureza:</th>
                        <td><?php echo $this->projeto['natureza']['nomnatureza']; ?></td>
                        <!--<th>Natureza:</th>-->
                        <?php //if($this->projeto['flacopa'] == "S"): ?>
                        <!--                                <td colspan="2"><?php //echo $this->projeto['natureza']['nomnatureza'] ?></td>
                                <td><span class="label label-info">Projeto da Copa de 2014</span></td>-->
                        <?php //else: ?>
                        <!--<td colspan="3"><?php //echo $this->projeto['natureza']['nomnatureza'] ?></td>-->
                        <?php //endif; ?>
                    </tr>
                    <tr>
                        <th>Ativ. não iniciadas:</th>
                        <td>
                            <?php
                            echo $this->projeto["qtdeatividadeiniciada"]['qtdeatividadenaoiniciada'] . ' atividade(s)';
                            echo ' (' . $this->projeto["qtdeatividadeiniciada"]['numpercentualnaoiniciado'] . '%)';
                            ?>
                        </td>
                        <th>Atividades iniciadas:</th>
                        <td>
                            <?php
                            echo $this->projeto["qtdeatividadeiniciada"]['qtdeatividadeiniciada'] . ' atividade(s)';
                            echo ' (' . $this->projeto["qtdeatividadeiniciada"]['numpercentualiniciado'] . '%)';
                            ?>
                        </td>
                        <th>Atividades concluídas:</th>
                        <td>
                            <?php
                            echo $this->projeto["qtdeatividadeiniciada"]['qtdeatividadeconcluida'] . ' atividade(s)';
                            echo ' (' . $this->projeto["qtdeatividadeiniciada"]['numpercentualatividadeconcluido'] . '%)';
                            ?>
                        </td>
                        <th></th>
                        <td></td>
                        <th></th>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
