<div class="accordion" id="accordion2">
        <div class="accordion-heading title">
            <span style="font-weight: bold; color: #0088CC"><?php echo $this->projeto['nomcodigo'] ?> - <?php echo $this->projeto['nomprojeto'] ?></a> </span>
        </div>
        <div class="accordion-group">
            <div id="collapseOne" class="accordion-body collapse">
                <div class="accordion-inner">
                    <table class="table table-striped table-bordered table-price" style="font-size: 8px !important;">
                        <colgroup>
                            <col style="width: 50px;">
                            <col style="width: 300px;">
                            <col style="width: 50px;">
                            <col style="width: 200px;">
                            <col style="width: 50px;">
                            <col style="width: 50px;">
                            <col style="width: 100px;">
                            <col style="width: 50px;">
                            <col style="width: 50px;">
                        </colgroup>
                        <tr>
                            <th>Patroci.:</th>
                            <td><?php echo $this->projeto['patrocinador']['nompessoa'] ?></td>
                            <th>Meta:</th>
                            <td>(<?php echo $this->projeto['metaEmDias'] ?>.d) <?php echo $this->projeto['datinicio'] ?> &agrave; <?php echo $this->projeto['datfim'] ?></td>
                            <th>Previsto:</th>
                            <td><?php echo $this->projeto['ultimoStatusReport']['numpercentualprevisto'] ?>%</td>
                            <th>Ult.Foto:</th>
                            <td><?php echo $this->projeto['ultimoStatusReport']['datacompanhamento'] ?></td>
                            <th>Prazo:</th>
                            <td><?php echo $this->projeto['prazoEmDias'] ?> dias </td>
                        </tr>
                        <tr>
                            <th>Gerente:</th>
                            <td><?php echo $this->projeto['gerenteprojeto']['nompessoa'] ?></td>
                            <th>Tend&ecirc;ncia:</th>
                            <td><?php echo $this->projeto['ultimoStatusReport']['datfimprojetotendencia'] ?> (<?php echo $this->projeto['tendenciaEmDias'] ?>.d)</td>
                            <th>Conclu&iacute;do:</th>
                            <td><?php echo $this->projeto['ultimoStatusReport']['numpercentualconcluido'] ?>%</td>
                            <th>Status:</th>
                            <td><?php echo $this->projeto['ultimoStatusReport']['domstatusprojeto'] ?></td>
                            <th>Risco:</th>
                            <td><span class="badge badge-<?php echo $this->projeto['descricaoRisco'] ?>">Risco</span></td>
                        </tr>
                        <tr>
                            <th>Adjunto:</th>
                            <td><?php echo $this->projeto['gerenteadjunto']['nompessoa'] ?></td>
                            <th>Alinhamento Estrat&eacute;gico:</th>
                            <td colspan="3"><?php echo $this->projeto['objetivo']['nomobjetivo'] ?> <br /> <?php echo $this->projeto['acao']['nomacao'] ?></td>
                            <th>Natureza:</th>
                            <?php if($this->projeto['flacopa'] == "S"): ?>
                                <td colspan="2"><?php echo $this->projeto['natureza']['nomnatureza'] ?></td>
                                <td><span class="label label-info">Projeto dos Grandes Eventos</span></td>
                            <?php else: ?>
                                <td colspan="3"><?php echo $this->projeto['natureza']['nomnatureza'] ?></td>
                            <?php endif; ?>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
