<div id="cabecalho">
    <div class="span9">
        <div align='left' style="float:left;">
            <img src="<?= $this->baseUrl('/img/brasao_fundobranco.png'); ?>" style="float:left;" />
            <br>INSIRA AQUI O NOME DE SUA ORGANIZACAO
            <br>INSIRA AQUI O NOME DE SEU SETOR OU DIVISAO
            <HR>
        </div>
        <div class="span6" style="float: left; margin-top: 10px">
        </div>
    </div> 
</div>