<?php
//
//$this->headScript()
//    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/knockout-2.2.1.js'), 'text/javascript')
//    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/globalize.min.js'), 'text/javascript')
//    ->appendFile($this->baseUrl('/js/library/chartjs/Lib/js/dx.chartjs.js'), 'text/javascript');
////    ->appendFile($this->baseUrl('/js/app/projeto/statusreport/acompanhamento-chart.js?'), 'text/javascript');

$dataAtual = Date('d/m/Y');
?>
<div class="span">
    <div class="row"><span class="relspan">Cronograma Atualizado em <?php echo $dataAtual; ?></span></div>
    <div class="row">
        <div class="portlet portlet-azul span12">
            <h3>9.Entregas e Marcos do Projeto </h3>

            <div class="content">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <th>Nome</th>
                    <th>Base Line</th>
                    <th>Início</th>
                    <th>Fim</th>
                    <th>%</th>
                    <th>Responsável</th>
                    <th>Farol</th>
                    </thead>
                    <tbody>
                    <?php if (count($this->entregasMarcos) > 0) : ?>
                        <?php foreach ($this->entregasMarcos as $data): ?>
                            <tr>
                                <td><?php echo (isset($data['domtipoatividade']) && $data['domtipoatividade'] == 4) ? "&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"icon-flag\"></i>&nbsp;&nbsp;" : "<i class=\"icon-tag\"></i>&nbsp;&nbsp;";
                                    echo $data['nomatividadecronograma']; ?></td>
                                <td><?php echo (isset($data['datiniciobaseline'])) ? $data['datiniciobaseline'] : "-"; ?>
                                    a <?php echo (isset($data['datfimbaseline'])) ? $data['datfimbaseline'] : "-"; ?></td>
                                <td><?php echo (isset($data['datinicio'])) ? $data['datinicio'] : "-"; ?></td>
                                <td><?php echo (isset($data['datfim'])) ? $data['datfim'] : "-"; ?></td>
                                <td><?php echo (isset($data['numpercentualconcluido'])) ? $data['numpercentualconcluido'] . "%" : "-"; ?></td>
                                <td><?php echo (isset($data['nomparteinteressada'])) ? $data['nomparteinteressada'] : "-"; ?></td>
                                <td><span
                                            class="badge badge-<?php echo (isset($data['numpercentualconcluido']) && ((int)$data['numpercentualconcluido'] == 100)) ? "default" : $data['domcoratraso']; ?>"><?php echo $data['atraso'];; ?>
                                        dias</span></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6">Nenhum registro encontrado.</td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>