<?php
$offset = 60 * 15;
@header("Expires: " . gmdate("D, d M Y H:i:s", time() + $offset) . " GMT");
@header("Cache-Control: max-age=$offset, must-revalidate");

/**
 * @var Projeto_Model_Gerencia $this ->projeto
 */

$posServer = strpos($_SERVER['SERVER_NAME'], "localhost");
if ($posServer === false) {
    $icontag = $this->baseUrl('/img/icon-tag.png');
    $iconflag = $this->baseUrl('/img/icon-flag.png');
} else {
    $icontag = 'img/icon-tag.png';
    $iconflag = 'img/icon-flag.png';
}


?>
<div class="btn-group" style="display: none;">
    <input type="hidden" id="risco" value="<?php echo $this->acompanhamento->domcorrisco; ?>">
    <input type="hidden" id="cf" value="<?php echo $this->projeto->numcriteriofarol; ?>">
    <input type="hidden" id="dm" value="<?php echo $this->diasmarco; ?>">
    <input type="hidden" id="uPrazo" value="<?php echo $this->ultimoPrazo; ?>">
</div>
<div id="content">
    <div class="region-center">
        <?php
        $alvos = array("<a class=\"accordion-toggle", "href=\"#collapseOne\"");
        $subst = array("<div style=\"font-weight: bold; color: #0088CC\" class=\"accordion-toggle", "");
        echo str_replace($alvos, $subst, $this->partial('_partials/projeto.phtml', array('projeto' => $this->projeto)));
        ?>
        <div align="center">
            <div style="display: inline-block;text-align: center;"><img
                        src="data:image/png;base64,<?php echo $this->graficoLinhaPlanejadoRealizado; ?>"
                        style="display: inline-block; width: auto; max-width: 373px;margin-right: 5px;"/>
                <img
                        src="data:image/png;base64,<?php echo $this->graficoLinhaEvolucaoAtraso; ?>"
                        style="display: inline-block; width: auto; max-width: 373px;"/>
            </div>
        </div>
        <!-- <div align="center" style="margin-top: 20px;">
            <table class="table table-bordered table-hover table-striped span10"
                   style="border-style: none;border-color: transparent;border: 0px solid transparent;background: #fff;"
                   border="0">
                <tr style="border: 0;">
                    <td style="text-align: center;border: 0;font-size: 14px;font-weight: bold;">Prazo</td>
                    <td style="text-align: center;border: 0;font-size: 14px;font-weight: bold;">Risco</td>
                    <td style="text-align: center;border: 0;font-size: 14px;font-weight: bold;">Marco</td>
                </tr>
                <tr style="border: 0;">
                    <td style="border: 0;"><img src="data:image/png;base64,<?php //$this->graficoGaugePrazo; ?>"
                            style="display: inline-block;"/></td>
                    <td style="border: 0;"><img
                            src="data:image/png;base64,<?php //$this->graficoGaugeRisco; ?>"
                            style="display: inline-block;"/></td>
                    <td style="border: 0;"><img
                            src="data:image/png;base64,<?php //$this->graficoGaugeMarco; ?>"
                            style="display: inline-block;"/></td>
                </tr>
            </table>
        </div> -->
        <?php if ($this->acompanhamento): ?>
        <div class="span10" style="display: inline;margin-left: 15px;page-break-before: always;margin-top: 60px;">
            <div style="float: left;margin-left: 6px; width: 350px;">
                <table class="table table-striped table-bordered table-price" border="1">
                    <tr style="background: #ece5e5;">
                        <td colspan="2"><h5>1. Projeto</h5></td>
                    </tr>
                    <tr>
                        <td width="1px"><b>Data do Relatório:<b></td>
                        <td><?php echo $this->dateBr($this->acompanhamento->datacompanhamento); ?></td>
                    </tr>
                    <tr>
                        <td width="1px"><b>Status&nbsp;do&nbsp;Projeto:<b></td>
                        <td><?php echo $this->acompanhamento->nomdomstatusprojeto; ?></td>
                    </tr>
                    <tr>
                        <td><b>% Concluído Planejado:</b></td>
                        <td>
                            <?php
                            $planejado = $this->acompanhamento->numpercentualprevisto;
                            if ($planejado == "0.00") {
                                echo '0';
                            } else {
                                echo $planejado . "%";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td><b>% Concluído Realizado:</b></td>
                        <td>
                            <?php
                            $realizado = $this->acompanhamento->numpercentualconcluido;
                            if ($realizado == "0.00") {
                                echo '0';
                            } else {
                                echo $realizado . "%";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Tendência Término:</b></td>
                        <td><?php echo $this->dateBr($this->acompanhamento->datfimprojetotendencia); ?></td>
                    </tr>
                    <tr>
                        <td><b>Cronograma:</b></td>
                        <td><?php echo($this->acompanhamento->getFile(array(
                                'idprojeto' => $this->acompanhamento->idprojeto,
                                'idstatusreport' => $this->acompanhamento->idstatusreport
                            )) ?
                                $this->acompanhamento->getFile(array(
                                    'idprojeto' => $this->acompanhamento->idprojeto,
                                    'idstatusreport' => $this->acompanhamento->idstatusreport
                                )) :
                                "Não existe cronograma disponível para esta data."); ?></td>
                    </tr>
                    <tr>
                        <td><b>TAP assinado?</b></td>
                        <td>
                            <?php
                            if ($this->acompanhamento->flaaprovado == 2) {
                                echo 'Não';
                            } else {
                                echo 'Sim';
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td><b>PGP assinado?</b></td>
                        <td>
                            <?php
                            if ($this->acompanhamento->pgpassinado == 'N') {
                                echo 'Não';
                            } else {
                                echo 'Sim';
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td><b>TEP assinado?</b></td>
                        <td>
                            <?php
                            if ($this->acompanhamento->tepassinado == 'N') {
                                echo 'Não';
                            } else {
                                echo 'Sim';
                            }
                            ?>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="width: 350px;">
                <table class="table table-striped table-bordered table-price" border="1" style="margin-left: 7px;">
                    <tr style="background: #ece5e5;">
                        <td colspan="2"><h5>2. Próximo Marco</h5></td>
                    </tr>
                    <tr>
                        <td width="1px"><b>Próximo Marco:</b></td>
                        <td><?php echo $this->esc($this->proximoMarco->nomatividadecronograma); ?></td>
                    </tr>
                    <tr>
                        <td><b>Planejado:</b></td>
                        <td><?php echo $this->dateBr($this->proximoMarco->datfimbaseline, ''); ?></td>
                    </tr>
                    <tr>
                        <td><b>Previsão:</b></td>
                        <td><?php echo $this->dateBr($this->proximoMarco->datfim); ?></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="span10" style="display: inline;margin-left: 15px;border: 0;">
            <div style="float: left;margin-left: 6px; width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1">
                    <tr style="background: #ece5e5;">
                        <td><h5>3. Considerações gerais sobre o andamento do projeto</h5></td>
                    </tr>
                    <tr>
                        <td>
                            <?php
                            if ($this->acompanhamento->desandamentoprojeto != null) {
                                echo preg_replace("/\r\n|\r|\n/", '<br/>', $this->acompanhamento->desandamentoprojeto);
                            } else {
                                echo 'Não há considerações.';
                            }
                            ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="span10" style="display: inline;margin-left: 15px;border: 0;">
            <div style="float: left;margin-left: 6px; width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1">
                    <tr style="background: #ece5e5;">
                        <td><h5>4. Atividades Concluídas no Período</h5></td>
                    </tr>
                    <tr>
                        <td><?php echo preg_replace("/\r\n|\r|\n/", '<br/>',
                                $this->acompanhamento->desatividadeconcluida) ?></td>
                    </tr>
                </table>
            </div>
            <div style="width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1"
                       style="margin-left: 7px;border: 0;">
                    <tr style="background: #ece5e5;">
                        <td><h5>5. Atividades em Andamento no Período</h5></td>
                    </tr>
                    <tr>
                        <td><?php echo @preg_replace("/\r\n|\r|\n/", '<br/>',
                                $this->acompanhamento->desatividadeandamento) ?></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="span10" style="display: inline;margin-left: 15px;border: 0;">
            <div style="float: left;margin-left: 6px; width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1">
                    <tr style="background: #ece5e5;">
                        <td><h5>6. Motivo do Atraso</h5></td>
                    </tr>
                    <tr>
                        <td><?php echo @preg_replace("/\r\n|\r|\n/", '<br/>',
                                $this->acompanhamento->desmotivoatraso) ?></td>
                    </tr>
                </table>
            </div>
            <div style="width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1" style="margin-left: 7px;">
                    <tr>
                        <td><h5>7. Contramedida (R3G)</h5></td>
                    </tr>
                    <tr>
                        <td><?php echo @preg_replace("/\r\n|\r|\n/", '<br/>',
                                $this->acompanhamento->descontramedida) ?></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="span10" style="display: inline;margin-left: 15px;border: 0;">
            <div style="float: left;margin-left: 6px; width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1">
                    <tr style="background: #ece5e5;">
                        <td><h5>8. Irregularidades&nbsp;(Atividades em Atraso)</h5></td>
                    </tr>
                    <tr>
                        <td><?php echo @preg_replace("/\r\n|\r|\n/", '<br/>',
                                $this->acompanhamento->desirregularidade) ?></td>
                    </tr>
                </table>
            </div>
            <div style="width: 350px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1"
                       style="margin-left: 7px;border: 0;">
                    <tr style="background: #ece5e5;">
                        <td><h5>9. Riscos</h5></td>
                    </tr>
                    <tr>
                        <td><?php echo @preg_replace("/\r\n|\r|\n/", '<br/>', $this->acompanhamento->desrisco) ?></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="span10"
             style="display: inline;margin-left: 15px;border: 0;page-break-before: always;margin-top: 60px;">
            <div style="float: left;margin-left: 6px; width: 700px;border: 0;">
                <table class="table table-striped table-bordered table-price" border="1">
                    <tr style="background: #ece5e5;">
                        <td nowrap="true" colspan="7"><h5>10. Entregas e Marcos do Projeto </h5></td>
                    </tr>
                    <tr style="background: #ece5e5;">
                        <td><b>Nome</b></td>
                        <td><b>Base Line</b></td>
                        <td><b>Início</b></td>
                        <td><b>Fim</b></td>
                        <td><b>%</b></td>
                        <td><b>Responsável</b></td>
                        <td><b>Farol</b></td>
                    </tr>
                    <tbody>
                    <?php if (count($this->entregasMarcos) > 0) : ?>
                        <?php foreach ($this->entregasMarcos as $data): ?>
                            <tr>
                                <td><?php echo (isset($data['domtipoatividade']) && $data['domtipoatividade'] == 4) ? "&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"" . $iconflag . "\" style=\"float:left;\" />&nbsp;&nbsp;" : "<img src=\"" . $icontag . "\" style=\"float:left;\" />&nbsp;&nbsp;";
                                    echo $data['nomatividadecronograma']; ?></td>
                                <td><?php echo (isset($data['datiniciobaseline'])) ? $data['datiniciobaseline'] : "-"; ?>
                                    a <?php echo (isset($data['datfimbaseline'])) ? $data['datfimbaseline'] : "-"; ?></td>
                                <td><?php echo (isset($data['datinicio'])) ? $data['datinicio'] : "-"; ?></td>
                                <td><?php echo (isset($data['datfim'])) ? $data['datfim'] : "-"; ?></td>
                                <td><?php echo (isset($data['numpercentualconcluido'])) ? $data['numpercentualconcluido'] . "%" : "-"; ?></td>
                                <td><?php echo (isset($data['nomparteinteressada'])) ? $data['nomparteinteressada'] : "-"; ?></td>
                                <td><span
                                            class="badge badge-<?php echo (isset($data['numpercentualconcluido']) && ((int)$data['numpercentualconcluido'] == 100)) ? "default" : $data['domcoratraso']; ?>"><?php echo $data['atraso'];; ?>
                                        dias</span></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6">Nenhum registro encontrado.</td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <?php endif; ?>
</div>
</div>