<?php
$infoIni = ($this->dados == 'informacoesiniciais') ? 'active' : "";
$infoTec = ($this->dados == 'informacoestecnicas') ? 'active' : "";
$resumo = ($this->dados == 'resumodoprojeto') ? 'active' : "";
$assintaura = ($this->dados == 'assinadocumento') ? 'active' : "";
?>
<ul class="nav nav-pills">
    <li class="<?php echo $infoIni ?>"><a class="link" href="#" onclick="visualizar('ii')">Informações Iniciais</a></li>
    <li class="<?php echo $infoTec ?>"><a class="link" href="#" onclick="visualizar('it')">Informações Técnicas</a></li>
    <li class="<?php echo $resumo ?>"><a class="link" href="#" onclick="visualizar('rp')">Resumo do Projeto</a></li>    
</ul>