<div id="content">
    <div align="center" style="margin-top: 170px">
        TERMO DE ABERTURA
    </div>
    <div align="center" style="margin-top: 40px">
        <?php echo $this->processo->nomcodigo; ?>
    </div>
    <div align="center" style="margin-top: 40px">
        <?php echo $this->processo->nomprojeto; ?>
    </div>
    <div align="center" style="margin-top: 40px">
        <?php echo $this->processo->desprojeto; ?>
    </div>
    <div align="left" class="span4" style="page-break-before: always;margin-top: 60px">
        <h5>1.1 INFORMA&Ccedil;&Otilde;ES INICIAIS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10" border="1">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td>C&Oacute;DIGO DO PROJETO</td>
                <td><?php echo $this->processo->nomcodigo; ?></td>
            </tr>
            <tr>
                <td>T&Iacute;TULO DO PROJETO</td>
                <td><?php echo $this->processo->nomprojeto; ?></td>
            </tr>
            <tr>
                <td>PROGRAMA</td>
                <td><?php echo $this->processo->programa["nomprograma"]; ?></td>
            </tr>
            <tr>
                <td>OBJETIVO INSTITUCIONAL</td>
                <td><?php echo $this->processo->objetivo["nomobjetivo"]; ?></td>
            </tr>
            <tr>
                <td>AÇÃO ESTRATÉGICA</td>
                <td><?php echo $this->acao; ?></td>
            </tr>
            <tr>
                <td>NATUREZA</td>
                <td><?php echo $this->processo->natureza["nomnatureza"]; ?></td>
            </tr>
            <tr>
                <td>&Aacute;REA EXECUTORA</td>
                <td><?php echo $this->processo->setor["nomsetor"]; ?></td>
            </tr>
            <tr>
                <td>PATROCINADOR</td>
                <td><?php echo $this->processo->nompatrocinador; ?></td>
            </tr>
            <tr>
                <td>DEMANDANTE</td>
                <td><?php echo $this->nomdemandante; ?></td>
            </tr>
            <tr>
                <td>ESCRITÓRIO RESPONSÁVEL</td>
                <td><?php echo $this->processo->escritorio->sigla; ?></td>
            </tr>
            <tr>
                <td>GERENTE DE PROJETO</td>
                <td><?php echo $this->processo->nomgerenteprojeto; ?></td>
            </tr>
            <tr>
                <td>GERENTE ADJUNTO</td>
                <td><?php echo $this->processo->nomgerenteadjunto; ?></td>
            </tr>
            <tr>
                <td>ORÇAMENTO PREVISTO</td>
                <td>R$<?php echo $this->valor; ?></td>
            </tr>
            <tr>
                <td>PRAZO PREVISTO PARA PROJETO</td>
                <td>
                    De: <?php echo @mb_substr($this->processo->datinicio, 0, 10) ?>
                    Até: <?php echo @mb_substr($this->processo->datfim, 0, 10) ?>
                </td>
            </tr>
            <tr>
                <td>PRAZO PREVISTO PARA PLANO DO PROJETO</td>
                <td>
                    De: <?php echo @mb_substr($this->processo->datinicioplano, 0, 10) ?>
                    Até: <?php echo @mb_substr($this->processo->datfimplano, 0, 10) ?>
                </td>
            </tr>
            <tr valign="top">
                <td>Nº DO PROCESSO</td>
                <td>
                    <?php echo $this->processo->maskSei($this->processo->numprocessosei, '#####.######/####-##'); ?>
                </td>
            </tr>
            </tbody>
        </table>

        <div align="left" class="span5" style="margin-top: 20px">
            <h5>1.2 INFORMA&Ccedil;&Otilde;ES T&Eacute;CNICAS</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                <tr>
                    <td>JUSTIFICATIVA DO PROJETO</td>
                    <td><?php echo nl2br($this->processo->desjustificativa); ?></td>
                </tr>
                <tr>
                    <td>OBJETO DO PROJETO (O QUE SER&Aacute; FEITO?)</td>
                    <td><?php echo nl2br($this->processo->desprojeto); ?></td>
                </tr>
                <tr>
                    <td>OBJETIVO DO PROJETO (PARA QUE SER&Aacute; FEITO?)</td>
                    <td><?php echo nl2br($this->processo->desobjetivo); ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 20px">
            <h5>1.3 RESUMO DO PROJETO</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                <tr>
                    <td>ESCOPO RESUMIDO (PRINCIPAIS ENTREGAS)</td>
                    <td><?php echo nl2br($this->processo->desescopo); ?></td>
                </tr>
                <tr>
                    <td>N&Atilde;O ESCOPO (O QUE N&Atilde;O SER&Aacute; FEITO?)</td>
                    <td><?php echo nl2br($this->processo->desnaoescopo); ?></td>
                </tr>
                <tr>
                    <td>PREMISSAS</td>
                    <td><?php echo nl2br($this->processo->despremissa); ?></td>
                </tr>
                <tr>
                    <td>RESTRI&Ccedil;&Otilde;ES</td>
                    <td><?php echo nl2br($this->processo->desrestricao); ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 20px">
            <h5>1.4 PARTES INTERESSADAS</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 35px">
                    <col style="width: 25px">
                    <col style="width: 40px">
                    <col style="width: 15px">
                </colgroup>
                <tr>
                    <td>Nome</td>
                    <td>Função</td>
                    <td>Telefone</td>
                    <td>Email</td>
                    <td>Nível Influência</td>
                </tr>
                <tbody>
                <?php if (count($this->processo->partes) > 0): ?>
                    <?php foreach ($this->processo->partes->getIterator() as $parte): ?>
                        <tr>
                            <td><?php echo $parte['nomparteinteressada']; ?></td>
                            <td><?php echo $parte['nomfuncao']; ?></td>
                            <td><?php echo $parte['destelefone']; ?></td>
                            <td><?php echo $parte['desemail']; ?></td>
                            <td><?php echo $parte['domnivelinfluencia']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5">Partes Interessadas n&atilde;o cadastradas no sistema.</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 20px">
            <h5>1.5 DEMAIS INFORMA&Ccedil;&Otilde;ES</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                <tr>
                    <td>PORTFÓLIO DO PROJETO</td>
                    <td><?php echo $this->noPortfolio; ?></td>
                </tr>
                <tr>
                    <td>TIPO DE PROJETO</td>
                    <td><?php echo $this->processo->domtipoprojeto; ?></td>
                </tr>
                <tr>
                    <td>GRANDES EVENTOS</td>
                    <td><?php echo $this->grandesEventos; ?></td>
                </tr>
                <tr>
                    <td>PERIODICIDADE DE ATUALIZA&Ccedil;&Atilde;O (DIAS)</td>
                    <td><?php echo $this->processo->numperiodicidadeatualizacao; ?></td>
                </tr>
                <tr>
                    <td>CRIT&Eacute;RIO DO FAROL (DIAS)</td>
                    <td><?php echo $this->processo->numcriteriofarol; ?></td>
                </tr>
                <tr>
                    <td>PUBLICAR NA TELA MESTRA</td>
                    <td><?php echo $this->telaMestra; ?></td>
                </tr>
                <!--<tr>
                        <td>PROJETO DO PORTIFÓLIO PF</td>
                        <td><?php // echo $this->processo->desrestricao; ?></td>
                    </tr>-->
                <tr>
                    <td>APROVADO</td>
                    <td><?php echo $this->aprovado; ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="page-break-before: always;margin-top: 60px;margin-bottom: 40px">
            <h5>1.6 APROVA&Ccedil;&Atilde;O DO PATROCINADOR</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="span10">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->processo->nompatrocinador; ?></td>
                    <td>____________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Patrocinador</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px;margin-bottom: 40px">
            <h5>1.7 CI&Ecirc;NCIA DO GERENTE DE PROJETO</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="span10">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->processo->nomgerenteprojeto; ?></td>
                    <td>____________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Gerente do Projeto</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
                </tbody>
                <br/><br/><br/><br/>
                <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?php echo $this->processo->nomgerenteadjunto; ?></td>
                    <td>____________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>

                <tr style="vertical-align: top;">
                    <td><b>Gerente Adjunto</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php if (count($this->assinaturas) > 0): ?>
            <div align="left" class="span10" style="margin-top: 60px;margin-bottom: 20px">
                <h5>1.8 ASSINATURA ELETR&Ocirc;NICA</h5><span style="font-size: 10px;">(Para validar a assinatura eletr&ocirc;nica acesse o endere&ccedil;o: <?php echo $this->url; ?>)</span>
            </div>
            <div align="center" style="margin-top: 20px">
                <table border="1" class="span10" cellspacing="1" cellpadding="1">
                    <colgroup>
                        <col style="width: 150px">
                        <col style="width: 15px">
                        <col style="width: 150px">
                    </colgroup>
                    <tbody style="text-align: center">
                    <?php foreach ($this->assinaturas as $assinatura) : ?>
                        <tr style="vertical-align: bottom">
                            <td><?php echo $assinatura['nomparteinteressada']; ?></td>
                            <td><?php echo $assinatura['assinado']; ?></td>
                            <td><?php echo $assinatura['hashdoc']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

        <?php endif; ?>
    </div>

</div>
