<?php echo $this->partial('_partials/relatorio-cabecalho.phtml');?> 
<div id="content">
    <div align="center" style="margin-top: 170px">
        TERMO DE ABERTURA
    </div>
    <div align="center" style="margin-top: 40px">
        <?= $this->processo->nomcodigo; ?>
    </div>
    <div align="center" style="margin-top: 40px">
        <?= $this->processo->nomprojeto; ?>
    </div>
    <div align="center" style="margin-top: 40px">
        <?= $this->processo->desprojeto; ?>
    </div>
    <div align="left" class="span4" style="page-break-before: always;margin-top: 60px">
        <h5>1.1 INFORMA&Ccedil;&Otilde;ES INICIAIS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10" border="1">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
                <tr>
                    <td>C&Oacute;DIGO DO PROJETO</td>
                    <td><?= $this->processo->nomcodigo; ?></td>
                </tr>
                <tr>
                    <td>T&Iacute;TULO DO PROJETO</td>
                    <td><?= $this->processo->nomprojeto; ?></td>
                </tr>
                <tr>
                    <td>PROGRAMA</td>
                    <td><?= $this->processo->programa["nomprograma"]; ?></td>
                </tr>
                <tr>
                    <td>OBJETIVO INSTITUCIONAL</td>
                    <td><?= $this->processo->objetivo["nomobjetivo"]; ?></td>
                </tr>
                <tr>
                    <td>AÇÃO ESTRATÉGICA</td>
                    <td><?php echo $this->acao; ?></td>
                </tr>
                <tr>
                    <td>NATUREZA</td>
                    <td><?= $this->processo->natureza["nomnatureza"]; ?></td>
                </tr>
                <tr>
                    <td>&Aacute;REA EXECUTORA</td>
                    <td><?= $this->processo->setor["nomsetor"]; ?></td>
                </tr>
                <tr>
                    <td>PATROCINADOR</td>
                    <td><?= $this->processo->nompatrocinador; ?></td>
                </tr>
                <tr>
                    <td>DEMANDANTE</td>
                    <td><?= $this->nomdemandante; ?></td>
                </tr>
                <tr>
                    <td>ESCRITÓRIO RESPONSÁVEL</td>
                    <td><?= $this->processo->escritorio->sigla; ?></td>
                </tr>
                <tr>
                    <td>GERENTE DE PROJETO</td>
                    <td><?= $this->processo->nomgerenteprojeto; ?></td>
                </tr>
                <tr>
                    <td>GERENTE ADJUNTO</td>
                    <td><?= $this->processo->nomgerenteadjunto; ?></td>
                </tr>
                <tr>
                    <td>ORÇAMENTO PREVISTO</td>
                    <td><?= number_format($this->processo->vlrorcamentodisponivel, 2,',', '.'); ?></td>
                </tr>
                <tr>
                    <td>PRAZO PREVISTO PARA PROJETO</td>
                    <td>
                        De: <?= $this->processo->datinicio ?> Até: <?= $this->processo->datfim ?>
                    </td>
                </tr>
                <tr>
                    <td>PRAZO PREVISTO PARA PLANO DO PROJETO</td>
                    <td>
                        De: <?= $this->processo->datinicioplano ?> Até: <?= $this->processo->datfimplano ?>
                    </td>
                </tr>
            </tbody>
        </table>

        <div align="left" class="span5" style="margin-top: 60px">
            <h5>1.2 INFORMA&Ccedil;&Otilde;ES T&Eacute;CNICAS</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                    <tr>
                        <td>JUSTIFICATIVA DO PROJETO</td>
                        <td><?= $this->processo->desjustificativa; ?></td>
                    </tr>
                    <tr>
                        <td>OBJETO DO PROJETO (O QUE SER&Aacute; FEITO?)</td>
                        <td><?= $this->processo->desprojeto; ?></td>
                    </tr>
                    <tr>
                        <td>OBJETIVO DO PROJETO (PARA QUE SER&Aacute; FEITO?)</td>
                        <td><?= $this->processo->desobjetivo; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px">
            <h5>1.3 RESUMO DO PROJETO</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                    <tr>
                        <td>ESCOPO RESUMIDO (PRINCIPAIS ENTREGAS)</td>
                        <td><?= $this->processo->desescopo; ?></td>
                    </tr>
                    <tr>
                        <td>N&Atilde;O ESCOPO (O QUE N&Atilde;O SER&Aacute; FEITO?)</td>
                        <td><?= $this->processo->desnaoescopo; ?></td>
                    </tr>
                    <tr>
                        <td>PREMISSAS</td>
                        <td><?= $this->processo->despremissa; ?></td>
                    </tr>
                    <tr>
                        <td>RESTRI&Ccedil;&Otilde;ES</td>
                        <td><?= $this->processo->desrestricao; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px">
            <h5>1.4 PARTES INTERESSADAS</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 35px">
                    <col style="width: 25px">
                    <col style="width: 40px">
                    <col style="width: 15px">
                </colgroup>
                <tr>
                    <td>Nome</td>
                    <td>Função</td>
                    <td>Telefone</td>
                    <td>Email</td>
                    <td>Nível Influência</td>
                </tr>
                <tbody>
                    <?php if (count($this->processo->partes) > 0): ?>
                        <?php foreach ($this->processo->partes->getIterator() as $parte): ?>
                            <tr>
                                <td><?= $parte['nomparteinteressada']; ?></td>
                                <td><?= $parte['nomfuncao']; ?></td>
                                <td><?= $parte['desemail']; ?></td>
                                <td><?= $parte['destelefone']; ?></td>
                                <td><?= $parte['domnivelinfluencia']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                            <tr>
                                <td colspan="5">Partes Interessadas n&atilde;o cadastradas no sistema.</td>
                            </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <div align="left" class="span5" style="margin-top: 60px">
            <h5>1.5 DEMAIS INFORMA&Ccedil;&Otilde;ES</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="table table-bordered table-hover table-striped span10" border="1">
                <colgroup>
                    <col style="width: 50px">
                    <col style="width: 100px">
                </colgroup>
                <tbody>
                    <tr>
                        <td>PORTFÓLIO DO PROJETO</td>
                        <td><?= $this->noPortfolio; ?></td>
                    </tr>
                    <tr>
                        <td>TIPO DE PROJETO</td>
                        <td><?= $this->processo->domtipoprojeto; ?></td>
                    </tr>
                    <tr>
                        <td>GRANDES EVENTOS</td>
                        <td><?php echo $this->grandesEventos; ?></td>
                    </tr>
                    <tr>
                        <td>PERIODICIDADE DE ATUALIZA&Ccedil;&Atilde;O (DIAS)</td>
                        <td><?= $this->processo->numperiodicidadeatualizacao; ?></td>
                    </tr>
                    <tr>
                        <td>CRIT&Eacute;RIO DO FAROL (DIAS)</td>
                        <td><?= $this->processo->numcriteriofarol; ?></td>
                    </tr>
                    <tr>
                        <td>PUBLICAR NA TELA MESTRA</td>
                        <td><?= $this->telaMestra; ?></td>
                    </tr>
                    <!--<tr>
                        <td>PROJETO DO PORTIFÓLIO PF</td>
                        <td><?php // echo $this->processo->desrestricao; ?></td>
                    </tr>-->
                    <tr>
                        <td>APROVADO</td>
                        <td><?= $this->aprovado; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div align="left" class="span5" style="page-break-before: auto;margin-top: 60px;margin-bottom: 40px">
            <h5>1.6 APROVA&Ccedil;&Atilde;O DO PATROCINADOR</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="span10">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                    <tr style="vertical-align: bottom">
                        <td><?= $this->processo->nompatrocinador; ?></td>
                        <td>____________________________________________</td>
                        <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td><b>Patrocinador</b></td>
                        <td><b>Assinatura</b></td>
                        <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div align="left" class="span5" style="margin-top: 60px;margin-bottom: 40px">
            <h5>1.7 CI&Ecirc;NCIA DO GERENTE DE PROJETO</h5>
        </div>
        <div align="center" style="margin-top: 20px">
            <table class="span10">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 15px">
                </colgroup>
                <tbody style="text-align: center">
                    <tr style="vertical-align: bottom">
                        <td><?= $this->processo->nomgerenteprojeto; ?></td>
                        <td>____________________________________________</td>
                        <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                    </tr>
                    <tr style="vertical-align: top">
                        <td><b>Gerente do Projeto</b></td>
                        <td><b>Assinatura</b></td>
                        <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                    </tr>
                </tbody>
                <br /><br /><br /><br />
                <tbody style="text-align: center">
                    <tr style="vertical-align: bottom">
                        <td><?= $this->processo->nomgerenteadjunto; ?></td>
                        <td>____________________________________________</td>
                        <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                    </tr>
                    
                    <tr style="vertical-align: top;">
                        <td><b>Gerente Adjunto</b></td>
                        <td><b>Assinatura</b></td>
                        <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>


