<?php echo $this->partial('_partials/relatorio-cabecalho.phtml'); ?>

<div id="content">
    <div align="left" class="span4" style="margin-top: 60px">
        <h5>1. TERMO DE ENCERRAMENTO</h5>
    </div>
    <div align="left" class="span4">
        <h5>1.1 PROJETO</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10" border="1">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
                <tr>
                    <td>C&Oacute;DIGO DO PROJETO</td>
                    <td><?= $this->projeto->nomcodigo; ?></td>
                </tr>
                <tr>
                    <td>T&Iacute;TULO DO PROJETO</td>
                    <td><?= $this->projeto->nomprojeto; ?></td>
                </tr>
                <tr>
                    <td>PATROCINADOR</td>
                    <td><?= $this->projeto->nompatrocinador; ?></td>
                </tr> 
                <tr>
                    <td>GERENTE DO PROJETO</td>
                    <td><?= $this->projeto->nomgerenteprojeto; ?></td>
                </tr>
                <tr>
                    <td>GERENTE ADJUNTO</td>
                    <td><?= $this->projeto->nomgerenteadjunto; ?></td>
                </tr>
                <tr>
                    <td>OBJETIVO</td>
                    <td><?= $this->projeto->desobjetivo; ?></td>
                </tr>
                <tr>
                    <td>OBJETO</td>
                    <td><?= $this->projeto->desprojeto; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div align="left" class="span4">
        <h5>1.2 LIÇÕES APRENDIDAS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10" border="1">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
                <tr>
                    <td>Entrega</td>
                    <td>RESULTADOS OBTIDOS</td>
                    <td>PONTOS FORTES</td>
                    <td>PONTOS FRACOS / DIFICULTADES ENCONTRADAS</td>
                    <td>SUGEST&Otilde;ES PARA UM PROJETO SEMELHANTE</td>
                </tr>
                 <?php foreach ($this->licao as $licao): ?>
                <tr>
                    <td><?= $licao['nomatividadecronograma']; ?></td>
                    <td><?= $licao['desresultadosobtidos']; ?></td>
                    <td><?= $licao['despontosfortes']; ?></td>
                    <td><?= $licao['despontosfracos']; ?></td>
                    <td><?= $licao['dessugestoes']; ?></td>
                    <?php endforeach;?>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div align="left" class="span4">
        <h5>1.3 CONSIDERA&Ccedil;&Otilde;ES FINAIS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 100px">
            </colgroup>
            <tbody>
                <tr>
                    <td><?= $this->projeto->desconsideracaofinal; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div align="left" class="span6" style="page-break-before: always;margin-top: 60px;margin-bottom: 40px">
        <h5>2 APROVA&Ccedil;&Atilde;O DO PATROCINADOR</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="span10">
            <colgroup>
                <col style="width: 150px">
                <col style="width: 15px">
                <col style="width: 15px">
            </colgroup>
            <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?= $this->projeto->nompatrocinador; ?></td>
                    <td>____________________________________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Patrocinador</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span6" style="margin-top: 60px;margin-bottom: 40px">
        <h5>3 CI&Ecirc;NCIA DO GERENTE DE PROJETO</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="span10">
            <colgroup>
                <col style="width: 150px">
                <col style="width: 15px">
                <col style="width: 15px">
            </colgroup>
            <tbody style="text-align: center">
                <tr style="vertical-align: bottom">
                    <td><?= $this->projeto->nomgerenteprojeto; ?></td>
                    <td>____________________________________________________________________</td>
                    <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
                </tr>
                <tr style="vertical-align: top">
                    <td><b>Gerente de Projeto</b></td>
                    <td><b>Assinatura</b></td>
                    <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
                </tr>
            </tbody>
        </table>
    </div>
    
</div>