<?php echo $this->partial('_partials/relatorio-cabecalho.phtml'); ?>

<div id="content">
    <div align="left" class="span4" style="margin-top: 60px">
        <h5>1. TERMO DE ENCERRAMENTO</h5>
    </div>
    <div align="left" class="span4">
        <h5>1.1 PROJETO</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10" border="1">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td>C&Oacute;DIGO DO PROJETO</td>
                <td><?php echo $this->projeto->nomcodigo; ?></td>
            </tr>
            <tr>
                <td>T&Iacute;TULO DO PROJETO</td>
                <td><?php echo $this->projeto->nomprojeto; ?></td>
            </tr>
            <tr>
                <td>PATROCINADOR</td>
                <td><?php echo $this->projeto->nompatrocinador; ?></td>
            </tr>
            <tr>
                <td>GERENTE DO PROJETO</td>
                <td><?php echo $this->projeto->nomgerenteprojeto; ?></td>
            </tr>
            <tr>
                <td>GERENTE ADJUNTO</td>
                <td><?php echo $this->projeto->nomgerenteadjunto; ?></td>
            </tr>
            <tr>
                <td>OBJETIVO</td>
                <td><?php echo $this->projeto->desobjetivo; ?></td>
            </tr>
            <tr>
                <td>OBJETO</td>
                <td><?php echo $this->projeto->desprojeto; ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span4">
        <h5>1.2 LIÇÕES APRENDIDAS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10" border="1">
            <colgroup>
                <col style="width: 50px">
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td>Entrega</td>
                <td>RESULTADOS OBTIDOS</td>
                <td>PONTOS FORTES</td>
                <td>PONTOS FRACOS / DIFICULTADES ENCONTRADAS</td>
                <td>SUGEST&Otilde;ES PARA UM PROJETO SEMELHANTE</td>
            </tr>
            <?php foreach ($this->licao as $licao): ?>
            <tr>
                <td><?php echo $licao['nomatividadecronograma']; ?></td>
                <td><?php echo $licao['desresultadosobtidos']; ?></td>
                <td><?php echo $licao['despontosfortes']; ?></td>
                <td><?php echo $licao['despontosfracos']; ?></td>
                <td><?php echo $licao['dessugestoes']; ?></td>
                <?php endforeach; ?>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span4">
        <h5>1.3 CONSIDERA&Ccedil;&Otilde;ES FINAIS</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="table table-bordered table-hover table-striped span10">
            <colgroup>
                <col style="width: 100px">
            </colgroup>
            <tbody>
            <tr>
                <td><?php echo $this->projeto->desconsideracaofinal; ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span6" style="page-break-before: always;margin-top: 60px;margin-bottom: 40px">
        <h5>2 APROVA&Ccedil;&Atilde;O DO PATROCINADOR</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="span10">
            <colgroup>
                <col style="width: 150px">
                <col style="width: 15px">
                <col style="width: 15px">
            </colgroup>
            <tbody style="text-align: center">
            <tr style="vertical-align: bottom">
                <td><?php echo $this->projeto->nompatrocinador; ?></td>
                <td>____________________________________________________________________</td>
                <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
            </tr>
            <tr style="vertical-align: top">
                <td><b>Patrocinador</b></td>
                <td><b>Assinatura</b></td>
                <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div align="left" class="span6" style="margin-top: 60px;margin-bottom: 40px">
        <h5>3 CI&Ecirc;NCIA DO GERENTE DE PROJETO</h5>
    </div>
    <div align="center" style="margin-top: 20px">
        <table class="span10">
            <colgroup>
                <col style="width: 150px">
                <col style="width: 15px">
                <col style="width: 15px">
            </colgroup>
            <tbody style="text-align: center">
            <tr style="vertical-align: bottom">
                <td><?php echo $this->projeto->nomgerenteprojeto; ?></td>
                <td>____________________________________________________________________</td>
                <td>/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/</td>
            </tr>
            <tr style="vertical-align: top">
                <td><b>Gerente de Projeto</b></td>
                <td><b>Assinatura</b></td>
                <td><b>Data da Aprova&ccedil;&atilde;o</b></td>
            </tr>
            </tbody>
        </table>
    </div>
    <?php if (count($this->assinaturas) > 0): ?>
        <div align="left" class="span10" style="margin-top: 60px;margin-bottom: 20px">
            <h5>4 ASSINATURA ELETR&Ocirc;NICA</h5><span style="font-size: 10px;">(Para validar a assinatura eletr&ocirc;nica acesse o endere&ccedil;o: <?php echo $this->url; ?> )</span>
        </div>
        <div align="center" style="margin-top: 20px">
            <table border="1" class="span10" cellspacing="1" cellpadding="1">
                <colgroup>
                    <col style="width: 150px">
                    <col style="width: 15px">
                    <col style="width: 150px">
                </colgroup>
                <tbody style="text-align: center">
                <?php foreach ($this->assinaturas as $assinatura) : ?>
                    <tr style="vertical-align: bottom">
                        <td><?php echo $assinatura['nomparteinteressada']; ?></td>
                        <td><?php echo $assinatura['assinado']; ?></td>
                        <td><?php echo $assinatura['hashdoc']; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    <?php endif; ?>
</div>

</div>