<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'));

$frmAttr = $this->form->getAttribs();
$class = "";

?>
<div class="region-center">
    <h4 class="pagination-centered"><?php echo $this->form->getLegend(); ?></h4>
    <form id="<?php echo $frmAttr['id']; ?>"
          name="<?php echo $frmAttr['id']; ?>"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">
        <?php foreach ($this->form->getElements() as $element): ?>
            <?php
            // se for botao (salvar|limpar) pula para montar fora do loop
            if ($element instanceof Twitter_Bootstrap_Form_Element_Button) {
                continue;
            }

            //seta a class diferente para nao quebrar o layout
            (
                $element instanceof Twitter_Bootstrap_Form_Element_MultiCheckbox ||
                $element instanceof Twitter_Bootstrap_Form_Element_Radio
            ) ? $class = 'row' : $class = 'row-fluid';
            ?>
            <div class="<?php echo $class ?>">
                <div class="span">
                    <?php $element->setAttrib('disabled', true);
                    echo $element;
                    ?>
                </div>
            </div>
        <?php endforeach; ?>
    </form>
</div>