<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/pesquisa/pesquisa/gerenciar-pesquisas.js'), 'text/javascript');

$frmAttr = $this->formPesquisar->getAttribs();

?>

<div class="region-center">
    <h4 class="pagination-centered">Gerência de Pesquisa Publicadas</h4>
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a class="btn" title="Voltar" href="<?php
            echo $this->url(array(
                'module' => 'pesquisa',
                'controller' => 'pesquisa',
                'action' => 'listar'
            ))
            ?>">
                Voltar
            </a>
        </div>
    </div>
    <div class="row-fluid">
        <div>
            <table id="list-grid-pesquisa"></table>
            <div id="toolbar-grid-pesquisa"></div>
            <div id="pager-grid-pesquisa"></div>
        </div>
    </div>
</div>

<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisa - filtrar</div>
            <div class="content">
                <form id="<?php echo $frmAttr['id']; ?>"
                      name="<?php echo $frmAttr['id']; ?>"
                      action="<?php echo $this->formPesquisar->getAction(); ?>"
                      method="<?php echo $frmAttr['method']; ?>">
                    <div class="row">
                        <div class="span">
                            <?php echo $this->formPesquisar->nomquestionario ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->tipoquestionario ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->situacao ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span">
                            <?php echo $this->formPesquisar->datcadastroinicio ?>
                        </div>
                        <div class="span">
                            <div class="control-group">
                                <label for="labeldate" class="control-label optional">&nbsp;</label>
                                <span id="labeldate">a</span>
                            </div>
                        </div>
                        <div class="span">
                            <label for="labeldate" class="control-label optional">&nbsp;</label>
                            <?php echo $this->formPesquisar->datcadastrofim ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formPesquisar->btnpesquisar ?>
                                <?php echo $this->formPesquisar->reset ?>
                                <?php echo $this->formPesquisar->close ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="dialog-detalhar" class="hide"></div>
<div id="dialog-republicar" class="hide">
    <p>Esta opera&ccedil;&atilde;o ir&aacute; republicar uma pesquisa já encerrada e tornar dispon&iacute;vel para
        resposta. Deseja realmente republicar esta pesquisa?</p>
</div>
<div id="dialog-encerrar" class="hide">
    <p>Esta opera&ccedil;&atilde;o ir&aacute; encerrar a pesquisa e tornar idispon&iacute;vel para resposta. Deseja
        realmente encerrar esta pesquisa?</p></div>
</div>
<input type="hidden" id="pesquisa" name="pesquisa" value=""/>