<script>

    $(function () {
        $.pnotify.defaults.history = false;

        $('.mask-date').datepicker({
            format: 'dd/mm/yyyy',
            language: 'pt-BR',
            changeMonth: true,
            changeYear: true
        });

        $('.mask-date').mask('99/99/9999');

        $('#flacontramedidaefetiva').change(function () {
            verificaRiscoAtivo();
        });
    });

    function verificaRiscoAtivo() {
        var flariscoativo = '<?php echo $this->risco['flariscoativo']?>';
        if ($('#flacontramedidaefetiva').val() == '1' && flariscoativo == '1') {
            $('#flacontramedidaefetiva').val('');
            $("#dialog-message").html('<p>A contramedida não pode ser efetiva se o risco ainda estiver ativo!</p>');
            $("#dialog-message").dialog({
                modal: true,
                buttons: {
                    Ok: function () {
                        $(this).dialog("close");
                    }
                }
            });
            $('#flacontramedidaefetiva').focus();
            return false;
        }
        return true;
    }

    function resetFormContramedida() {
        $("input, select, textarea").not('input#idrisco, #form-contramedida-pesquisar :input').val('');
    }


</script>

<?php $frmAttrContramedida = $this->formContramedida->getAttribs(); ?>

<div id="dialog-message" title="Erro" style="display: none;"></div>

<div class="region-center">
    <div class="portlet">
        <form id="<?php echo $frmAttrContramedida['id']; ?>"
              name="<?php echo $frmAttrContramedida['id']; ?>"
              action="<?php echo $this->formContramedida->getAction(); ?>"
              method="<?php echo $frmAttrContramedida['method']; ?>">

            <?php echo $this->formContramedida->idrisco ?>
            <div class="row">
                <div class="span5">
                    <?php echo $this->formContramedida->nocontramedida ?>
                </div>
            </div>
            <div class="row">
                <div class="span9">
                    <?php echo $this->formContramedida->descontramedida ?>
                </div>
            </div>
            <div class="row">
                <div class="span2">
                    <?php echo $this->formContramedida->datprazocontramedida ?>
                </div>
                <div class="span2">
                    <?php echo $this->formContramedida->datprazocontramedidaatraso ?>
                </div>
                <div class="span3">
                    <?php echo $this->formContramedida->idtipocontramedida ?>
                </div>
                <div class="span3">
                    <?php echo $this->formContramedida->domstatuscontramedida ?>
                </div>
            </div>
            <div class="row">
                <div class="span2">
                    <?php echo $this->formContramedida->flacontramedidaefetiva ?>
                </div>
                <div class="span3">
                    <?php echo $this->formContramedida->desresponsavel ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 75px;">
                    (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                    obrigatório
                </div>
            </div>
        </form>
    </div>
</div>