<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'));

$frmAttr = $this->form->getAttribs();
?>
<div class="content">
    <form id="form-evento-editar"
          name="form-evento-editar"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">
        <div class="row">
            <div class="span10">
                <?php echo $this->form->nomevento; ?>
            </div>
        </div>

        <div class="row">
            <div class="span2_5">
                <?php echo $this->form->datinicio; ?>
            </div>
            <div class="span2_5">
                <?php echo $this->form->datfim; ?>
            </div>
            <div class="span2">
                <?php echo $this->form->uf; ?>
            </div>

            <div class="row container-pessoa">
                <div class="span3">
                    <div class="control-group">
                        <?php echo $this->form->nomresponsavel->renderLabel(); ?>
                        <div class="input-prepend ">
                            <?php echo $this->form->pessoabutton; ?>
                            <?php echo $this->form->nomresponsavel->renderViewHelper(); ?>
                            <?php echo $this->form->idresponsavel; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row grid-append" style="display: none;">
        </div>


        <div class="row">
            <div class="span6">
                <?php echo $this->form->desevento; ?>
            </div>
        </div>
        <div class="row">
            <div class="span6">
                <?php echo $this->form->desobs; ?>
            </div>
        </div>

        <?php echo $this->form->idevento; ?>
        <div class="row">
            <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
            </div>
        </div>
    </form>
</div>