<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/cadastro/pessoa/add.js'), 'text/javascript');


$frmAttr = $this->form->getAttribs();
?>

<div class="region-east">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Importar Pessoas</div>
            <div class="content">
                <form id="importar-pessoa" name="importar-pessoa" method="post" action="">
                    <!--
                    <div class="row">
                        <div class="span3">
                            <div class="alert alert-message">
                                Usu&aacute;rios cadastrados n&atilde;o ser&atilde;o listados.
                            </div>
                        </div>
                    </div>
                    -->
                    <div class="row">
                        <div class="span3">
                            <label class="radio inline">
                                <input type="radio" class="importar" name="origem-importacao" id="origem-servidor"
                                       value="0" checked>
                                Servidor
                            </label>
                            <label class="radio inline">
                                <input type="radio" class="importar" name="origem-importacao" id="origem-colaborador"
                                       value="1">
                                Colaborador
                            </label>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Nome</label>
                        <input type="text" class="span3" value="" placeholder="Nome" id="gridpessoa" name="gridpessoa">
                    </div>
                    <div class="btn-group">
                        <button id="btn-grid-pessoa" class="btn" type="submit" title="Pesquisar"><i
                                    class="icon-filter"></i> Pesquisar
                        </button>
                        <button id="limpar" class="btn" type="reset" title="Limpar"><i class="icon-th"></i> Limpar
                        </button>
                        <button id="btn-close-grid-pessoa" class="btn toggle-region" type="button" data-region="east"
                                title="Fechar"><i class="icon-arrow-right"></i> Fechar
                        </button>
                    </div>
                </form>
                <div class="row formulario">
                    <div class="span3">
                        <div class="alert alert-info">
                            Clique duas vezes para importar
                        </div>
                    </div>
                </div>
                <table id="list-grid-pessoa"></table>
                <div id="toolbar-grid-pessoa"></div>
                <div id="pager-grid-pessoa"></div>
            </div>
        </div>
    </div>
</div>
<div class="region-center">
    <div class="row">
        <div class="portlet portlet-marron span10">
            <div class="title"><span class="title" name="Cadastrar Pessoas">Cadastrar Pessoas</span></div>
            <div class="content">
                <div class="form-actions form-actions-mini">
                    <div class="btn-group">
                        <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Importar</a>
                        <a id="btn-p" href="#" class="btn">Cadastrar Manualmente</a>
                    </div>
                </div>
                <div class="content" id="divForumario">
                    <form id="<?php echo $frmAttr['id']; ?>"
                          name="<?php echo $frmAttr['id']; ?>"
                          action="<?php echo $this->form->getAction(); ?>"
                          method="<?php echo $frmAttr['method']; ?>">
                        <div class="row">
                            <div class="span8">
                                <div id="alert-import" class="alert alert-info"
                                     style="display:none; margin-top: 10px;"></div>
                            </div>
                        </div>
                        <div class="row hidden formulario">
                            <div class="span8">
                                <fieldset>
                                    <legend>Dados Pessoais</legend>
                                    <div class="row">
                                        <div class="span6">
                                            <?php echo $this->form->nompessoa; ?>
                                        </div>
                                        <div class="span2">
                                            <?php echo $this->form->numcpf; ?>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <div class="row hidden formulario">
                            <div class="span8">
                                <fieldset>
                                    <legend>Dados Funcionais</legend>
                                    <div class="row">
                                        <div class="span2">
                                            <?php echo $this->form->nummatricula; ?>
                                        </div>
                                        <div class="span2">
                                            <?php echo $this->form->desfuncao; ?>
                                        </div>
                                        <div class="span2">
                                            <?php echo $this->form->domcargo; ?>
                                        </div>
                                        <div class="span2">
                                            <?php echo $this->form->id_unidade; ?>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <div class="row hidden formulario">
                            <div class="span8">
                                <fieldset>
                                    <legend>Contatos</legend>
                                    <div class="row">
                                        <div class="span2">
                                            <?php echo $this->form->numfone; ?>
                                        </div>
                                        <div class="span2">
                                            <?php echo $this->form->numcelular; ?>
                                        </div>
                                        <div class="span2">
                                            <?php echo $this->form->desemail; ?>
                                        </div>
										<div class="span2">
					                        <?php echo $this->form->token; ?>
					                    </div>
                                        <div class="span2">
                                            <?php echo $this->form->flaagenda; ?>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>

                        <div class="row hidden formulario">
                            <div class="span8">
                                <?php echo $this->form->desobs; ?>
                            </div>
                        </div>
                        <div class="row hidden formulario">
                            <div class="span4">
                                <?php echo $this->form->id_servidor; ?>
                                <?php echo $this->form->idpessoa; ?>
                                <?php echo $this->form->idcadastrador; ?>
                                <?php echo $this->form->submit; ?>
                                <?php echo $this->form->reset; ?>
                            </div>
                        </div>
                        <div class="row hidden formulario">
                            <div class="span9" style="text-align: right;">
                                <span>(<img src="<?= $this->baseUrl('/img/required.gif'); ?>"
                                            title="Campo Obrigat&oacute;rio"/>)&nbsp;&nbsp;Campo Obrigatório</span>
                            </div>
                        </div>
                        <div id="dialog-confirm" style="display: none">
                            <p>Prezado Usu&aacute;rio,</p>
                            <p>Utilize esta fun&ccedil;&atilde;o somente ap&oacute;s ter certeza de que n&atilde;o
                                &eacute; poss&iacute;vel cadastrar a pessoa por meio da fun&ccedil;&atilde;o
                                "Importar."</p>
                        </div>

                    </form>

                </div>

            </div>
        </div>
    </div>
</div>