<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'));
$frmAttr = $this->form->getAttribs();
?>

<form id="<?php echo $frmAttr['id']; ?>"
      name="<?php echo $frmAttr['id']; ?>"
      action="<?php echo $this->form->getAction(); ?>"
      method="<?php echo $frmAttr['method']; ?>">
    <div class="row formulario">
        <div class="span8">
            <fieldset>
                <legend>Dados Pessoais</legend>
                <div class="row">
                    <div class="span6">
                        <?php echo $this->form->nompessoa; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->numcpf; ?>
                    </div>
                    <?php
                    $auth = Zend_Auth::getInstance();
                    $user = $auth->getIdentity()->perfilAtivo->idperfil;
                    if ($user == 1): ?>
                        <div class="span2">
                            <?php echo $this->form->editarSenha; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->token; ?>
                        </div>
                    <?php endif;?>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row formulario">
        <div class="span8">
            <fieldset>
                <legend>Dados Funcionais</legend>
                <div class="row">
                    <div class="span2">
                        <?php echo $this->form->nummatricula; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->desfuncao; ?>
                    </div>
                    <div class="span1">
                        <?php echo $this->form->domcargo; ?>
                    </div>
                    <div class="span3">
                        <?php echo $this->form->id_unidade; ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row formulario">
        <div class="span8">
            <fieldset>
                <legend>Contatos</legend>
                <div class="row">
                    <div class="span2">
                        <?php echo $this->form->numfone; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->numcelular; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->desemail; ?>
                    </div>
                    <div class="span2">
                        <?php echo $this->form->flaagenda; ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row formulario">
        <div class="span8">
            <?php echo $this->form->desobs; ?>
            <?php echo $this->form->id_servidor; ?>
            <?php echo $this->form->idpessoa; ?>
        </div>
    </div>
    <!--
    <div class="row form-actions">
        <div class="span4">
            <?php echo $this->form->submit; ?>
            <?php echo $this->form->reset; ?>
        </div>
    </div>
    -->
    <div class="row formulario">
        <div class="span8" style="text-align: right;">
            <span>(<img src="<?= $this->baseUrl('/img/required.gif'); ?>" title="Campo Obrigat&oacute;rio"/>)&nbsp;&nbsp;Campo Obrigatório</span>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function () {
        $("#editarSenha").change(function () {
            $("#token").val('').attr('disabled', $(this).val() == 'N');
        });
    });
</script>
