<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.formatCurrency.js'))
    ->appendFile($this->baseUrl('/js/app/diagnostico/secao/edit.js'), 'text/javascript');
$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <?php echo $this->partial('_partials/questionario-menu.phtml', array('dados' => 'secoes-add')); ?>
    <div class="portlet portlet-marron span12" style="width:90%">
        <h3>Seções</h3>

        <div class="content" style="width:90%">
            <form id="form-itemsecao-edit"
                  name="form-itemsecao-edit"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <fieldset>
                    <legend>Questionário: <?php echo $this->questionario->nomquestionario; ?></legend>
                    <div class="row">
                        <div class="span4" title="Use o Ctrl ou Shift para múltipla seleção">
                            <?php echo $this->form->ds_item; ?>
                        </div>
                        <div class="span1_5" style="margin-top: 27px;">
                            <a class="btn btn-ds_item-move" id="ds_item-in" title="Selecionar Itens" href="#"><i
                                        class="icon-chevron-right"></i></a><br/>
                            <a class="btn btn-ds_item-move" id="ds_item-out" title="Voltar Itens" href="#"><i
                                        class="icon-chevron-left"></i></a>
                        </div>
                        <div class="span4" title="Use o Ctrl ou Shift para múltipla seleção">
                            <?php echo $this->form->id_secao; ?>
                            <div id="quest-editar"
                                 style="font-size: 10px; color: red; margin-top: -15px; display: none;">
                                <span>Este campo é requerido.</span>
                            </div>
                            <input type="hidden" id="secao" name="secao" value="">
                            <input type="hidden" id="secaoTexto" name="secaoTexto" value="">
                            <input type="hidden" id="idquestionariodiagnostico" name="idquestionariodiagnostico"
                                   value="<?php echo $this->questionario->idquestionariodiagnostico; ?>">
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <div class="row">
                        <div class="span5">
                            <?php echo $this->form->id_item; ?>
                            <?php echo $this->form->tpquestionario; ?>
                            <?php echo $this->form->submit; ?>
                            <?php echo $this->form->reset; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                            (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                            obrigatório
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
