<?php //var_dump($this->escritorio);?>
<div class="row">
    <div class="portlet portlet-azul span4">
        <h3>Nome do Escritório Projeto</h3>
        <div class="content">
            <?= $this->escritorio->nome; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span">
        <h3>Sigla</h3>
        <div class="content">
            <?= $this->escritorio->sigla; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span">
        <h3>Mapa</h3>
        <div class="content">
            <?= $this->escritorio->mapa; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span">
        <h3>Ativo?</h3>
        <div class="content">
            <?= $this->escritorio->getDescricaoFlaativo(); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span7">
        <h3>Responsável-1</h3>
        <div class="content">
            <?= $this->escritorio->responsavel1->nompessoa; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span7">
        <h3>Responsável-2</h3>
        <div class="content">
            <?= $this->escritorio->responsavel2->nompessoa; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="portlet portlet-cinza span4">
        <h3>Email</h3>
        <div class="content">
            <?= $this->escritorio->desemail; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span3">
        <h3>Telefone</h3>
        <div class="content">
            <?= $this->escritorio->numfone; ?>
        </div>
    </div>

</div>