<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));

$this->headScript()->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'),
    'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/projeto/mudanca/add.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <div class="ui-dialog-content ui-widget-content">
        <form id="<?php echo $frmAttr['id']; ?>"
              name="<?php echo $frmAttr['id']; ?>"
              action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $frmAttr['method']; ?>">
            <?php ?>
            <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
            <div class="row">
                <div class="span2_5">
                    <?php echo $this->form->idtipomudanca; ?>
                </div>
                <div class="span3">
                    <?php echo $this->form->nomsolicitante; ?>
                </div>
            </div>
            <div class="row">
                <div class="span2">
                    <?php echo $this->form->datdecisao; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->datsolicitacao; ?>
                </div>
                <div class="span2">
                    <?php echo $this->form->flaaprovada; ?>
                </div>

            </div>
            <div class="row">
                <div class="span5">
                    <?php echo $this->form->desmudanca; ?>
                </div>
                <div class="span4">
                    <?php echo $this->form->desjustificativa; ?>
                </div>
            </div>
            <div class="row">
                <div class="span5">
                    <?php echo $this->form->despareceregp; ?>
                </div>
                <div class="span4">
                    <?php echo $this->form->despareceraprovadores; ?>
                </div>
            </div>
            <div class="row">
                <div class="span5">
                    <?php echo $this->form->idcadastrador; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 40px;">
                    (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                    obrigatório
                </div>
            </div>
        </form>
    </div>
</div>