<div class="content">
    <form id="form-mudanca-editar"
          name="form-mudanca-editar"
          action="<?php echo $this->form->getAction(); ?>"
          method="post">
        <?php ?>
        <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
        <?php echo $this->form->idmudanca; ?>
        <div class="row">
            <div class="span2_5">
                <?php echo $this->form->idtipomudanca; ?>
            </div>
            <div class="span3">
                <?php echo $this->form->nomsolicitante; ?>
            </div>
        </div>
        <div class="row">
            <div class="span2">
                <?php echo $this->form->datdecisao; ?>
            </div>
            <div class="span2">
                <?php echo $this->form->datsolicitacao; ?>
            </div>
            <div class="span2">
                <?php echo $this->form->flaaprovada; ?>
            </div>
        </div>
        <div class="row">
            <div class="span5">
                <?php echo $this->form->desmudanca; ?>
            </div>
            <div class="span4">
                <?php echo $this->form->desjustificativa; ?>
            </div>
        </div>
        <div class="row">
            <div class="span5">
                <?php echo $this->form->despareceregp; ?>
            </div>
            <div class="span4">
                <?php echo $this->form->despareceraprovadores; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 30px;">
                (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
            </div>
        </div>
    </form>
</div>