<form id="form-mudanca-excluir"
      name="form-mudanca-excluir"
      action="<?php echo $this->baseUrl(); ?>/projeto/solicitacaomudanca/excluir/format/json"
      method="post">
    <?php ?>
    <input type="hidden" name="idprojeto" value="<?php echo $this->idprojeto ?>"/>
    <input type="hidden" name="idmudanca" value="<?php echo $this->mudanca->idmudanca ?>"/>
    <div class="alert alert-block" style="font-size: 14px !important;">
        <h4>Aviso!</h4>
        Deseja realmente excluir o registro?
    </div>
</form>