<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript');
$frmAttr = $this->form->getAttribs();
$i = 0;
?>
<div class="region-center">
    <div class="ui-dialog-content ui-widget-content">
        <input type="hidden" name="parte" id="parte" value="<?php echo $this->parte->idparteinteressada; ?>">
        <input type="hidden" name="tppermissao" id="tppermissao" value="<?php echo $this->parte->tppermissao; ?>">
        <form id="<?php echo $frmAttr['id']; ?>"
              name="<?php echo $frmAttr['id']; ?>"
              action="<?php echo $this->form->getAction(); ?>"
              method="<?php echo $frmAttr['method']; ?>">
            <div class="row">
                <div class="span7">
                    <span class="dsatividade"><?php echo $this->atividade->nomatividadecronograma; ?></span>
                    <hr>
                </div>
            </div>
            <?php if (count($this->comentarios) > 0) : ?>
                <div class="row">
                    <div class="span7 caixacomentario">

                        <?php foreach ($this->comentarios as $comentario) :
                            $i++;
                            ?>
                            <article>
                                <header>
                                    <span class="userComentario"><? echo $comentario['nompessoa'] ?></span>
                                    <?php if ((null != $this->parte->idparteinteressada) && $this->parte->tppermissao == 1) : ?>
                                        <i class="icon-trash comments"
                                           data-text="<?php echo $comentario['idcomentario']; ?>"></i>
                                    <?php endif; ?>
                                    <p class="pubdate">Publicado em:
                                        <time pubdate="pubdate"><?php echo $comentario['dtcomentario']; ?></time>
                                    </p>
                                </header>
                                <p class="comentarios"><?php echo $comentario['dscomentario'] ?></p>

                            </article>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="row">
                <div class="span7">
                    <span class="contar"><?php echo $i; ?>&nbsp;&nbsp; Coment&aacute;rios.</span>
                    <hr>
                </div>
            </div>
            <?php if ((null != $this->parte->idparteinteressada) && $this->parte->tppermissao == 1) : ?>
                <div class="row">
                    <div class="span7">
                        <?php echo $this->form->dscomentario; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="span7">
                        <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->idprojeto; ?>">
                        <input type="hidden" name="idatividadecronograma" id="idatividadecronograma"
                               value="<?php echo $this->idatividadecronograma; ?>">
                        <input type="hidden" name="idpessoa" id="idpessoa"
                               value="<?php echo $this->parte->idpessoainterna; ?>">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-offset-9 col-sm-span1" style="float: right;  padding-top: 10px;">
                        (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                        obrigatório
                    </div>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>