<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));
?>
<form id="copiar-cronograma"
      name="copiar-cronograma"
      action="<?php echo $this->baseUrl(); ?>/projeto/cronograma/copiar-cronograma/format/json"
      method="post">
    <div class="alert alert-block" style="font-size: 14px !important;">
        <h4>Aviso!</h4>
        Confirma a cópia do cronograma do Projeto selecionado?
    </div>

    <div class="row">
        <div class="span5">
            <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->params['idprojeto']; ?>"/>
            <input type="hidden" name="idprojetoorigem" id="idprojetoorigem"
                   value="<?php echo $this->params['idprojetoorigem']; ?>"/>
        </div>
    </div>
</form>