<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/css/dpf-bootstrap.css'));
?>

<div>

    <?php if (isset($this->projeto['grupos'])): ?>
        <table class="table table-striped table-hover table-condensed">
            <thead>
            <th>Grupo/Evento/Atividade</th>
            <th>(P)</th>
            <th>Base Line</th>
            <th>Qtde dias</th>
            <th>Custo</th>
            <th>In&iacute;cio/Fim</th>
            <th>%</th>
            <th>Respons&aacute;vel</th>
            <th>Farol</th>
            </thead>
            <tbody>
            <?php foreach ($this->projeto['grupos'] as $gr): ?>
                <tr>
                    <td><i class="icon-folder-open"></i> <?php echo $gr['nomatividadecronograma'] ?></td>
                    <td></td>
                    <td><?php echo $gr['datiniciobaseline'] ?> &agrave; <?php echo $gr['datfimbaseline'] ?></td>
                    <td><?php echo $gr['diasbaseline'] ?></td>
                    <td><?php echo $gr['vlratividade'] ?></td>
                    <td><?php echo $gr['datinicio'] ?> &agrave; <?php echo $gr['datfim'] ?></td>
                    <td><?php echo $gr['numpercentualconcluido'] ?>%</td>
                    <td></td>
                    <td></td>
                </tr>
                <?php if (isset($gr['entregas'])):
                    foreach ($gr['entregas'] as $en): ?>
                        <tr>
                            <td style="padding-left: 15px;"><i
                                        class="icon-tag"></i> <?php echo $en['nomatividadecronograma'] ?></td>
                            <td></td>
                            <td><?php echo $en['datiniciobaseline'] ?> &agrave; <?php echo $en['datfimbaseline'] ?></td>
                            <td><?php echo $en['diasbaseline'] ?></td>
                            <td><?php echo $en['vlratividade'] ?></td>
                            <td><?php echo $en['datinicio'] ?> &agrave; <?php echo $en['datfim'] ?></td>
                            <td><?php echo $en['numpercentualconcluido'] ?>%</td>
                            <td><?php echo $en['desemail'] ?></td>
                            <td><span class="badge badge-"> <?php echo $en['prazo'] ?> </span></td>
                        </tr>
                        <?php if (isset($en['atividades'])):
                            foreach ($en['atividades'] as $at): ?>
                                <tr>
                                    <td style="padding-left: 30px;"><i
                                                class="icon-list-alt"></i> <?php echo $at['nomatividadecronograma'] ?>
                                    </td>
                                    <td></td>
                                    <td><?php echo $at['datiniciobaseline'] ?>
                                        &agrave; <?php echo $at['datfimbaseline'] ?></td>
                                    <td><?php echo $at['diasbaseline'] ?></td>
                                    <td><?php echo $at['vlratividade'] ?></td>
                                    <td><?php echo $at['datinicio'] ?> &agrave; <?php echo $at['datfim'] ?></td>
                                    <td><?php echo $at['numpercentualconcluido'] ?>%</td>
                                    <td><?php echo $at['desemail'] ?></td>
                                    <td>
                                        <span class="badge badge-<?php echo $at['descricaoprazo'] ?>"><?php echo $at['prazo'] ?></span>
                                    </td>
                                </tr>
                            <?php endforeach;
                        endif; ?>
                    <?php endforeach;
                endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="row span6"> Ainda não há cronograma para esse Projeto</div>
    <?php endif; ?>
</div>


