<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/cronograma/index.css'))
;

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/handlebars.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/date.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.formatCurrency.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/intervalo.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/index.js'), 'text/javascript')
;
?>
<div class="region-center">
    
    <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->projeto->idprojeto; ?>">
    <?php /* var_dump($this->projeto); *///echo $this->partial('_partials/projeto.phtml', array('projeto' => $this->projeto)); ?>
    <div class="row" data-spy="affix" data-offset-top="200">
        <div class="span12">
            <div class="btn-toolbar">
                <!--
                <div class="btn-group btn-group-ferramentas" data-toggle="buttons-radio">
                    <button type="button" id="btn-fullscreen" class="btn" title="Tela cheia"><i class="icon-fullscreen"></i></button>
                    <button type="button" id="btn-restaurar" class="btn" title="Restaurar tela"><i class="icon-resize-small"></i></button>
                </div>
                -->
                <a class="btn btn-cadastrar-grupo" title="Novo Grupo" href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-grupo/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-folder-open"></i></a>
                <div class="btn-group btn-group-atividade" style="display: none;">
                    <a class="btn btn-editar-atividade" title="Editar" href="<?php echo $this->baseUrl('/projeto/cronograma/editar-atividade/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-excluir-atividade" title="Excluir" href="<?php echo $this->baseUrl('/projeto/cronograma/excluir-atividade/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-trash"></i></a>
                    <a class="btn btn-cadastrar-marco" title="Novo Marco" href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-marco/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-flag"></i></a>
                    <a class="btn btn-cadastrar-marco" title="Atualizar Base Line" href="<?php echo $this->baseUrl('/projeto/cronograma/atualizar-base-line/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-calendar"></i></a>
                </div>
                <div class="btn-group btn-group-entrega" style="display: none;">
                    <a class="btn btn-editar-entrega" title="Editar" href="<?php echo $this->baseUrl('/projeto/cronograma/editar-entrega/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-excluir-entrega" title="Excluir" href="<?php echo $this->baseUrl('/projeto/cronograma/excluir-entrega/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-trash"></i></a>
                    <a class="btn btn-cadastrar-atividade" title="Nova Atividade" href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-atividade/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-list-alt"></i></a>
                    <a class="btn btn-cadastrar-marco" title="Novo Marco" href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-marco/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-flag"></i></a>
                </div>
                <div class="btn-group btn-group-grupo" style="display: none;">
                    <a class="btn btn-editar-grupo" title="Editar" href="<?php echo $this->baseUrl('/projeto/cronograma/editar-grupo/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-pencil"></i></a>
                    <a class="btn btn-excluir-grupo" title="Excluir" href="<?php echo $this->baseUrl('/projeto/cronograma/excluir-grupo/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-trash"></i></a>
                    <a class="btn btn-cadastrar-entrega" title="Nova Entrega" href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-entrega/idprojeto/' . $this->projeto->idprojeto); ?>"><i class="icon-tag"></i></a>
                </div>
            </div>
        </div>
    </div>
    <table id="cronograma-titulos" class="table table-hover table-striped table-condensed">
        <tr>
            <td>
                <div class="row">
                    <div class="span1" style="width: 30px !important">#</div>
                    <div class="span4" style="margin-left: 0">Grupo/Entrega/Atividade</div>
                    <div class="span2">(P) Base Line</div>
                    <div class="span1">Custo</div>
                    <div class="span1">Início</div>
                    <div class="span1">Fim</div>
                    <div class="span1">%</div>
                    <div class="span1">Responsável</div>
                </div>
            </td>
        </tr>
    </table>
    <div class="container-grupo"  style="height: 100%; overflow-y: scroll;">
        <?php
        foreach ( $this->projeto->grupo as $grupo ): ?>
            <div class="row grupo" id="gr<?php echo $grupo->idatividadecronograma; ?>">
                <div class="item-cronograma" style="display: block; width: 100%; overflow: hidden;">
                    <div class="span1" style="width: 30px !important">
                        <input type="radio" name="item_cronograma" class="input-item-cronograma" data-group=".btn-group-grupo" value="<?php echo $grupo->idatividadecronograma; ?>">
                    </div>
                    <div class="span4 nome-grupo" style="margin-left: 0">
                        <i class="icon-folder-open"></i> <?php echo ($grupo->nomatividadecronograma); ?>
                    </div>
                    <div class="span2">
                        <?php echo $grupo->retornaDataInicioBaseLineGrupo(); ?> à
                        <?php echo $grupo->retornaDataFimBaseLineGrupo(); ?>
                    </div>
                    <div class="span2">
                        <?php echo $grupo->getCustoGrupo(); ?>
                    </div>
                </div>
                <div class="container-entrega ">
                    <?php
                    foreach ( $grupo->entrega as $entrega ):
                    ?>
                        <div class=" entrega" id="en<?php echo $entrega->idatividadecronograma; ?>">
                            <div class="item-cronograma" style="display: block; width: 100%; overflow: hidden;">
                                <div class="span1" style="width: 30px !important">
                                    <input type="radio" name="item_cronograma" class="input-item-cronograma" data-group=".btn-group-entrega" value="<?php echo ($entrega->idatividadecronograma); ?>">
                                </div>
                                <div class="span4 nome-entrega" style="margin-left: 0; padding-left: 20px; width: 350px !important;">
                                    <i class="icon-tag"></i> <?php echo ($entrega->nomatividadecronograma); ?>
                                </div>
                                <div class="span2">
                                    <?php echo $entrega->retornaDataInicioBaseLineEntrega(); ?> à
                                    <?php echo $entrega->retornaDataFimBaseLineEntrega(); ?>
                                </div>
                                <div class="span2">
                                    <?php echo $entrega->getCustoEntrega(); ?>
                                </div>
                            </div>
                            <div class="container-atividade" style="display: block; width: 100%; clear: both;">
                                <?php
                                foreach ( $entrega->atividade as $atividade ):
                                ?>
                                    <div class=" atividade" id="at<?php echo $atividade->idatividadecronograma; ?>" data-date="<?php echo $atividade->datiniciobaseline->toString('Ymd'); ?>">
                                        <div class="item-cronograma" style="display: block; width: 100%; overflow: hidden;">

                                            <div class="span1" style="width: 30px !important">
                                                <input type="radio" name="item_cronograma" class="input-item-cronograma" data-group=".btn-group-atividade" value="<?php echo $atividade->idatividadecronograma; ?>">
                                            </div>
                                            <div class="span4 nome-atividade" style="margin-left: 0; padding-left: 40px; width: 330px !important;">
                                                <i class="icon-list-alt"></i> <?php echo $atividade->nomatividadecronograma; ?>
                                            </div>
                                            <div class="span2">
                                                <?php echo $atividade->datiniciobaseline->toString('d/m/Y'); ?> à
                                                <?php echo $atividade->datfimbaseline->toString('d/m/Y'); ?>
                                            </div>
                                            <div class="span1">
                                                <?php echo $atividade->vlratividade; ?>
                                            </div>
                                            <div class="span1">
                                                <?php echo $atividade->datinicio->toString('d/m/Y'); ?>
                                            </div>
                                            <div class="span1">
                                                <?php echo $atividade->datfim->toString('d/m/Y'); ?>
                                            </div>
                                            <div class="span1">
                                                <?php echo $atividade->numpercentualconcluido; ?>%
                                            </div>
                                            <div class="span2">
                                                wilton.wbsj
                                            </div>
                                            <div class="span1">
                                                <span class="badge badge-<?php echo $atividade->retornaDescricaoPrazo($this->projeto->numcriteriofarol); ?>" title="<?php echo $atividade->retornaPrazoEmDias(); ?>">R</span>
                                            </div>
                                        </div>
                                    </div>
                                <?php
                                endforeach;
                                ?>
                            </div>
                        </div>
                    <?php
                    endforeach;
                    ?>
                </div>
            </div>
        <?php 
        endforeach;
        ?>
    </div>
    <!--
    <input type="hidden" name="idprojeto" id="idprojeto" value="<?php //echo $this->projeto->idprojeto;                                   ?>" />
    -->
    <?php //var_dump($this->projeto->grupo->nomatividadecronograma);  ?>
    <div id="dialog-grupo" style="display: none"></div>
    <div id="dialog-entrega" style="display: none"></div>
    <div id="dialog-atividade" style="display: none"></div>
    <div id="dialog-marco" style="display: none">
        <?php echo $this->partial('_partials/cron-form-atividade-marco.phtml', array('form' => $this->formMarco)); ?>
    </div>
</div>
<script id="tpl-atividade" type="text/x-handlebars-template">
    <div class=" atividade success" id="at{{idatividadecronograma}}" data-date="{{inverterData datiniciobaseline}}">
        <div class="item-cronograma" style="display: block; width: 100%; overflow: hidden;">
            <div class="span1" style="width: 30px !important">
                <input type="radio" name="item_cronograma" class="input-item-cronograma" data-group=".btn-group-atividade" value="{{idatividadecronograma}}">
            </div>
            <div class="span4 nome-atividade" style="margin-left: 0">
                <div class="container-atividade" style="padding-left: 40px;">
                    <i class="icon-list-alt"></i>{{nomatividadecronograma}}
                </div>
            </div>
            <div class="span2">
                {{datiniciobaseline}} à {{datfimbaseline}}
            </div>
            <div class="span1">
                {{vlratividade}}
            </div>
            <div class="span1">
                {{datinicio}}
            </div>
            <div class="span1">
                {{datfim}}
            </div>
            <div class="span1">
                {{numpercentualconcluido}}%
            </div>
            <div class="span2">
                wilton.wbsj
            </div>
            <div class="span1">
                <span class="badge badge-{{info}}" title="{{dias}}">P</span>
            </div>
        </div>
    </div>
</script>
<script id="tpl-grupo" type="text/x-handlebars-template">
    <div class="row grupo success" id="gr{{idatividadecronograma}}">
        <div class="item-cronograma" style="display: block; width: 100%; overflow: hidden;">
            <div class="span1" style="width: 30px !important">
                <input type="radio" name="item_cronograma" class="input-item-cronograma" data-group=".btn-group-grupo" value="{{idatividadecronograma}}">
            </div>
            <div class="span4 nome-grupo" style="margin-left: 0">
                <i class="icon-folder-open"></i> {{nomatividadecronograma}}
            </div>
            <div class="span2">
                {{datiniciobaseline}} à {{datfimbaseline}}
            </div>
            <div class="span1">
                {{vlratividade}}
            </div>
            <div class="span1">
                {{datinicio}}
            </div>
            <div class="span1">
                {{datfim}}
            </div>
            <div class="span1">
                {{numpercentualconcluido}}%
            </div>
            <div class="span2">
                wilton.wbsj
            </div>
            <div class="span1">
                <span class="badge badge-{{info}}" title="{{dias}}">P</span>
            </div>
        </div>
        <div class="container-entrega">
        </div>
    </div>
</script>
<script id="tpl-entrega" type="text/x-handlebars-template">
    <div class="entrega success" id="entrega{{idatividadecronograma}}">
        <div class="item-cronograma" style="display: block; width: 100%; overflow: hidden;">
            <div class="span1" style="width: 30px !important">
                <input type="radio" name="item_cronograma" class="input-item-cronograma" data-group=".btn-group-grupo" value="{{idatividadecronograma}}">
            </div>
            <div class="span4 nome-entrega" style="margin-left: 0; padding-left: 20px; width: 350px !important;">
                <i class="icon-tag"></i> {{nomatividadecronograma}}
            </div>
            <div class="span2">
                {{datiniciobaseline}} à {{datfimbaseline}}
            </div>
            <div class="span1">
                {{vlratividade}}
            </div>
            <div class="span1">
                {{datinicio}}
            </div>
            <div class="span1">
                {{datfim}}
            </div>
            <div class="span1">
                {{numpercentualconcluido}}%
            </div>
            <div class="span2">
                wilton.wbsj
            </div>
            <div class="span1">
                <span class="badge badge-{{info}}" title="{{dias}}">P</span>
            </div>
        </div>
        <div class="container-atividade" style="display: block; width: 100%; clear: both;">
        </div>
    </div>
</script>
<script id="tpl-predecessora" type="text/x-handlebars-template">
    <tr>
        <td>
            <a class="btn btn-mini remover-predecessora" href="#"><i class="icon-trash"></i></a>
            <input type="hidden" name="idpredecessora[]" value="{{idatividadecronograma}}">
        </td>
        <td>{{nomatividadecronograma}}</td>
    </tr>
    
    
    <tr>
        <td>
            <a class="btn btn-mini remover-predecessora" href="#"><i class="icon-trash"></i></a>
            <input type="hidden" class="idpredecessora" name="idpredecessora[]" value="<?php echo $p['idatividade']; ?>" data-idatividadepredecessora="<?php echo $p['idatividadepredecessora']; ?>">
        </td>
        <td><?php echo $p['datinicio']; ?> a <?php echo $p['datfim']; ?> - <?php echo $p['nomatividadecronograma']; ?></td>
    </tr>
    
</script>
<script id="tpl-predecessora-editar" type="text/x-handlebars-template">
    <tr>
        <td>
            <a class="btn btn-mini remover-predecessora" href="#"><i class="icon-trash"></i></a>
            <input type="hidden" class="idpredecessora" name="idpredecessora[]" value="{{idatividadecronograma}}">
        </td>
        <td>{{nomatividadecronograma}}</td>
    </tr>
</script>
<script id="tpl-projeto" type="text/x-handlebars-template">
    <div class="accordion" id="accordion2">
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                    {{nomcodigo}} - {{nomprojeto}}
                </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
                <div class="accordion-inner">
                    <table class="table table-striped table-bordered table-price">
                        <colgroup>
                            <col style="width: 50px;">
                            <col style="width: 300px;">
                            <col style="width: 50px;">
                            <col style="width: 200px;">
                            <col style="width: 50px;">
                            <col style="width: 50px;">
                            <col style="width: 100px;">
                            <col style="width: 50px;">
                            <col style="width: 50px;">
                        </colgroup>
                        <tr>
                            <th>Patroci.:</th>
                            <td>{{patrocinador.nompessoa}}</td>
                            <th>Meta:</th>
                            <td>({{metaEmDias}}.d) {{datinicio}} &agrave; {{datfim}}</td>
                            <th>Previsto:</th>
                            <td>{{ultimoStatusReport.numpercentualprevisto}}%</td>
                            <th>Ult.Foto:</th>
                            <td>{{ultimoStatusReport.datacompanhamento}}</td>
                            <th>Prazo:</th>
                            <td><span class="badge badge-{{descricaoPrazo}}">{{prazoEmDias}} dias</span></td>
                        </tr>
                        <tr>
                            <th>Gerente:</th>
                            <td>{{gerenteprojeto.nompessoa}}</td>
                            <th>Tendência:</th>
                            <td>{{ultimoStatusReport.datfimprojetotendencia}} ({{tendenciaEmDias}}.d)</td>
                            <th>Concluído:</th>
                            <td>{{ultimoStatusReport.numpercentualconcluido}}%</td>
                            <th>Status:</th>
                            <td>{{ultimoStatusReport.domstatusprojeto}}</td>
                            <th>Risco:</th>
                            <td><span class="badge badge-{{descricaoRisco}}">Risco</span></td>
                        </tr>
                        <tr>
                            <th>Adjunto:</th>
                            <td>{{gerenteadjunto.nompessoa}}</td>
                            <th>Alinhamento Estratégico:</th>
                            <td colspan="3">{{objetivo.nomobjetivo}} <br /> {{acao.nomacao}}</td>
                            <th>Natureza:</th>
                            <td colspan="<?php echo ($this->projeto->flacopa == 'S') ? 2 : 3; ?>"><?php echo $this->projeto->natureza->nomnatureza ; ?></td>
                            <?php if($this->projeto->flacopa == 'S'): ?>
                                <td><span class="label label-info">Projeto da Copa de 2014</span></td>
                            <?php endif; ?>
                        </tr>
                    </table>


                    <!--
                    : PF_06 - Implantação da Gestão por Competências
                    Patroci.:	LUIZ FERNANDO CORREA 	Meta:(500.d)	01/06/2009 à 14/10/2010 	Previsto:	100% 	Ult.Foto:	17/02/2011 	Prazo:	[207]
                    Gerente:	ANISIO SOARES VIEIRA 	Tendência:	09/05/2011 (707.d) 	Concluído:	92%
                    Em Andamento
                    Risco:
                    Adjunto:	JORGEVAL SILVA COSTA 	Alinhamento Estratégico:	02 - Valorizar o Servidor
                    - 01 - Gestão por Competência 	Natureza:	ESTRUTURAÇÃO ORGANIZACIONAL
                    -->
                </div>
            </div>
        </div>
    </div>
</script>