<?php
header("Expires: Tue, 03 Jul 2001 06:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
header("Connection: close");

$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/cronograma/index.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/cronograma/comentario.css'))
    ->appendStylesheet($this->baseUrl('/css/app/projeto/cronograma/tabela-cron.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/date.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.formatCurrency.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/intervalo.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/calcularTempo.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/index.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/cronograma.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/grupo.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/entrega.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/projeto/cronograma/atividade.js'), 'text/javascript');
$countGrupo = 0;
$countEntrega = 0;
$countAtividade = 0;

?>
<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml',
        array('ativo' => 'cronograma', 'idprojeto' => $this->idprojeto));
    ?>
</div>

<div class="region-center">
    <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->idprojeto; ?>">
    <input type="hidden" name="feriadosfixos" id="feriadosfixos" value="<?php echo @$this->feriadosfixos; ?>">
    <input type="hidden" name="numcriteriofarol" id="numcriteriofarol" value="">
    <input type="hidden" name="idparteireressada" id="idparteireressada"
           value="<?php echo (is_object($this->parteinteressada) && (!empty($this->parteinteressada->idparteinteressada))) ? $this->parteinteressada->idparteinteressada : ""; ?>">

    <div d="dados-projeto" class="row affix-top" style="top: 0px;">
        <?php
        echo $this->partial('_partials/projeto.phtml', array('projeto' => $this->conteudo['projeto']));
        ?></div>
    <div class="row" data-spy="affix" data-offset-top="200">
        <div class="toolbar-cronograma">
            <div class="btn-toolbar">
                <div class="btn-group btn-group-cronograma" style="display: inline-block;">
                    <a id="btn-buscar" class="btn btn-buscar toggle-region"
                       title="Pesquisar" data-region="east" href="#"><i class="icon-search"></i></a>
                    <a class="btn btn-cadastrar-grupo" title="Novo Grupo"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-grupo/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-folder-open"></i>
                    </a>
                </div>
                <div class="btn-group btn-group-atividade" style="display: none;">
                    <a class="btn btn-editar-atividade" title="Editar"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/editar-atividade/idprojeto/' . $this->idprojeto); ?>"><i
                                class="icon-pencil"></i></a>
                    <a class="btn btn-excluir-atividade" title="Excluir"><i class="icon-trash"></i></a>
                    <a id="<?php echo $this->display ?>" disabled="<?php echo $this->display ?>"
                       class="btn btn-atualizar-baseline-ativ"
                       title="Atualizar Base Line da Atividade"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/atualizar-baseline-atividade/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-calendar"></i>
                    </a>

                </div>
                <div class="btn-group btn-group-entrega" style="display: none;">
                    <a class="btn btn-editar-entrega" title="Editar"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/editar-entrega/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-pencil"></i>
                    </a>
                    <a class="btn btn-excluir-entrega" title="Excluir"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/excluir-entrega/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-trash"></i></a>
                    <a class="btn btn-cadastrar-atividade" title="Nova Atividade / Marco"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-atividade/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-list-alt"></i></a>
                    <a class="btn btn-clonar-entrega" title="Clonar Entrega" href="#"><i class="icon-tags"></i></a>
                    <a class="btn btn-ocultar-atividades" title="Alterar Visibilidade" href="#"><i
                                class="icon-eye-close"></i></a>
                </div>
                <div class="btn-group btn-group-grupo" style="display: none;">
                    <a class="btn btn-editar-grupo" title="Editar"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/editar-grupo/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-pencil"></i></a>
                    <a class="btn btn-excluir-grupo" title="Excluir"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/excluir-grupo/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-trash"></i></a>
                    <a class="btn btn-cadastrar-entrega" title="Nova Entrega"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/cadastrar-entrega/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-tag"></i></a>
                    <a class="btn btn-clonar-grupo" title="Clonar Grupo"
                       href="#"><i class="icon-random"></i></a>
                    <a class="btn btn-ocultar-entregas" title="Alterar Visibilidade" href="#">
                        <i class="icon-eye-close"></i>
                    </a>
                </div>
                <div class="btn-group btn-group-ferramentas  pull-right" data-toggle="buttons-radio">
                    <button type="button" id="btn-fullscreen" class="btn" title="Tela cheia">
                        <i class="icon-fullscreen"></i>
                    </button>
                    <button type="button" id="btn-restaurar" class="btn" title="Restaurar tela">
                        <i class="icon-resize-small"></i>
                    </button>
                </div>
                <div class="btn-group btn-group-cronograma pull-right">
                    <a id="<?php echo $this->display ?>" <?php echo $this->display ?>
                       class="btn btn-atualizar-baseline <?php echo $this->display ?>"
                       title="Atualizar Base Line"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/atualizar-baseline/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-th-list"></i>
                    </a>
                    <a class="btn btn-copiar-cronograma" title="Copiar Cronograma"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/pesquisar-projeto/idprojeto/' . $this->idprojeto); ?>">
                        <i class="icon-list-alt"></i>
                    </a>
                    <a class="btn btn-imprimir-cronograma" title="Visualizar Impressão"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/imprimir/idprojeto/' . $this->idprojeto); ?>"
                       target="_blank"><i class="icon-print"></i>
                    </a>
                    <a class="btn btn-imprimir-cronograma-pdf" title="Imprimir Cronograma PDF"
                       href="<?php echo $this->baseUrl('/projeto/cronograma/imprimir-pdf/idprojeto/' . $this->idprojeto); ?>"
                       target="_blank"><i class="icon-download-alt"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="TableCSS table-responsive">
        <table id="tabCron" border="0" class="table-striped table-hover table-condensed">
            <thead>
            <tr>
                <th rowspan="2" colspan="2" style="width: 4% !important;"><i class="icon-info-sign" title="Operações"/>
                </th>
                <th rowspan="2" style="width: 3% !important;">Seq.</th>
                <th rowspan="2" colspan="4" style="width: 22% !important;">Grupo/Entrega/Atividade</th>
                <th rowspan="2" style="width: 6% !important;">(<abbr title="Predecessoras">P</abbr>)</th>
                <th colspan="3" style="width: 13% !important;">Planejado</th>
                <th rowspan="2" style="width: 5% !important;">Custo</th>
                <th colspan="4" style="width: 16% !important;">Realizado</th>
                <th rowspan="2" style="width: 5% !important;">(<abbr title="Percentual de conclusão">%</abbr>)</th>
                <th rowspan="2" style="width: 15% !important;">Respons&aacute;vel</th>
                <th rowspan="2" style="width: 5% !important;">Atraso</th>
                <th rowspan="2" style="width: 5% !important;">Coment&aacute;rios</th>
                <th rowspan="2" style="width: 1% !important;">&nbsp;</th>
            </tr>
            <tr>
                <th style="width: 5% !important;">In&iacute;cio</th>
                <th style="width: 5% !important;">Fim</th>
                <th style="width: 3% !important;">(<abbr title="Quantidade de dias da base line">D/P</abbr>)</th>
                <th style="width: 5% !important;">In&iacute;cio</th>
                <th style="width: 5% !important;">Fim</th>
                <th style="width: 3% !important;">(<abbr title="Folga">F</abbr>)</th>
                <th style="width: 3% !important;">(<abbr title="Quantidade de dias realizados">D/R</abbr>)</th>
            </tr>
            <?php if (count($this->conteudo['cronograma']) > 0): ?>
            <tr style="font-weight: bold">
                <td colspan="8" style="width: 34% !important;"><i
                            class="icon-folder-open"></i>&nbsp;<?php echo $this->conteudo['projeto']['nomprojeto']; ?>
                </td>
                <td style="text-align: center;width: 5% !important;"><?php echo $this->conteudo['projeto']['datiniciobaseline']; ?></td>
                <td style="text-align: center;width: 5% !important;"><?php echo $this->conteudo['projeto']['datfimbaseline']; ?></td>
                <td style="text-align: center !important;width: 3% !important;"><?php echo $this->conteudo['projeto']['numdiasbaseline']; ?></td>
                <td style="text-align: right !important;width: 5% !important;"><?php echo (!empty($this->conteudo['projeto']['vlratividadet']) && $this->conteudo['projeto']['vlratividadet'] > 0) ? mb_substr($this->conteudo['projeto']['vlratividadet'],
                            0, -2) . '.' . mb_substr($this->conteudo['projeto']['vlratividadet'], -2) : number_format(0,
                        2); ?></td>
                <td style="text-align: center !important;width: 5% !important;"><?php echo $this->conteudo['projeto']['datinicioReal']; ?></td>
                <td style="text-align: center !important;width: 5% !important;"><?php echo $this->conteudo['projeto']['datfimReal']; ?></td>
                <td style="width: 3% !important;">&nbsp;</td>
                <td style="text-align: center !important;width: 3% !important;"><?php echo $this->conteudo['projeto']['numdiasrealizados']; ?></td>
                <td style="text-align: center;width: 5% !important;"><?php echo number_format($this->conteudo['projeto']['numpercentualconcluido'],
                        0); ?></td>
                <td style="width: 15% !important;">&nbsp;</td>
                <td style="text-align: center;width: 5% !important;"><span
                            class="badge badge-<?php echo (number_format($this->conteudo['projeto']['numpercentualconcluido'],
                                    0) == 100) ? "default" : $this->conteudo['projeto']['descricaoPrazo']; ?>"
                            title="<?php echo $this->conteudo['projeto']['prazoEmDias']; ?> dias"><?php echo $this->conteudo['projeto']['prazoEmDias']; ?>
                        dias</span>
                    </span></td>
                <td style="width: 5% !important;">&nbsp;</td>
                <td style="width: 1% !important;">&nbsp;</td>
            </tr>
            </thead>
        </table>
        <div class="bodycontainer scrollable"
             style="width: 100% !important; margin: 0; padding: 0; overflow-y: scroll; ">
            <table class="table table-hover table-condensed table-scrollable" style="margin: 0; padding: 0;">
                <tbody>
                <?php foreach ($this->conteudo['cronograma'] as $item):
                    $item['descricaoconclusao'] = "";
                    $numDiasReais = 0;
                    $numDiasPlanejada = 0;
                    $countPredecessoras = 0;
                    $item['contPredecessoras'] = 0;
                    $atraso = $item['atraso'];

                    $farol = $item['domcoratraso'];

                    if (isset($item['predecessoras']) && !empty($item['predecessoras']) && $item['predecessoras'] != "{NULL}") {
                        if (is_numeric(strpos($item['predecessoras'], '&&&&&'))) {
                            $result = explode("&&&&&", $item['predecessoras']);
                            $item['contPredecessoras'] = count($result);
                            $predecess = array();
                            foreach ($result as $array):
                                $arraynumPredecessora = explode("#-#", $array);
                                $predecess[] = $arraynumPredecessora[0];
                            endforeach;
                            $item['listaPredecessoras'] = implode(';', $predecess);
                        } else {
                            $arraynumPredecessora = explode("#-#", $item['predecessoras']);
                            $item['listaPredecessoras'] = $arraynumPredecessora[0];
                            $item['contPredecessoras'] = 1;
                        }
                    }

                    $hoje = new DateTime('now');
                    $item['descricaoconclusao'] = 'item-em-dia';

                    if ($item['numpercentualconcluido'] == 100.00) {
                        $item['descricaoconclusao'] = 'item-concluido';
                    } else {
                        if (!empty($item['datfim']) && $item['domtipoatividade'] == 3 ||
                            (!empty($item['datfim'])) && $item['domtipoatividade'] == 4
                        ) {
                            $dtFim = DateTime::createFromFormat('d/m/Y', $item['datfim']);
                            if ($dtFim < $hoje) {
                                $item['descricaoconclusao'] = 'item-atrasado';
                            }
                        }
                    }

                    if ((($item['domtipoatividade'] == 3)
                            || ($item['domtipoatividade'] == 4)) && $item['flacancelada'] == 'S'
                    ) {
                        $item['descricaoconclusao'] = 'item-cancelado';
                    }

                    switch ($item['domtipoatividade']) :
                        case 1: ?>
                            <tr>
                                <td style="width: 2% !important;">
                                    <input type="radio"
                                           name="item_cronograma"
                                           class="input-item-cronograma item-grupo"
                                           data-group=".btn-group-grupo"
                                           data-dados='{"flashowhide": "'<?php echo $item['flashowhide']; ?>'"}'
                                    data-text='{<?php echo trim(number_format($item['numpercentualconcluido'], 0)); ?>
                                    ,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>
                                    ,<?php echo trim($item['numfolga']); ?>
                                    ,<?php echo trim($item['domtipoatividade']); ?>
                                    ,<?php echo trim($item['idgrupo']); ?>
                                    ,<?php echo trim($item['numdiasrealizados']); ?>
                                    ,<?php echo trim($item['idatividadecronograma']); ?>
                                    ,<?php echo trim($item['idparteinteressada']); ?>
                                    ,<?php echo trim($item['contPredecessoras']); ?>}'
                                    value="<?php echo trim($item['idatividadecronograma']); ?>" >
                                    <input type="hidden" name="domtipoatividade" id="domtipoatividade"
                                           value="<?php echo $item['domtipoatividade']; ?>">
                                </td>
                                <td style="width: 2% !important;">
                                    <i class='icon-edit grupo'
                                       title='Editar Grupo'
                                       data-text='{<?php echo trim(number_format($item['numpercentualconcluido'],
                                           0)); ?>,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>,<?php echo trim($item['numfolga']); ?>,<?php echo trim($item['domtipoatividade']); ?>,<?php echo trim($item['idgrupo']); ?>,<?php echo trim($item['numdiasrealizados']); ?>,<?php echo trim($item['idatividadecronograma']); ?>,<?php echo trim($item['idparteinteressada']); ?>,<?php echo trim($item['contPredecessoras']); ?>}'/>
                                </td>
                                <td style="text-align: center; width: 3% !important;"><?php echo $item['numseq']; ?></td>
                                <td style="width: 2% !important;" class="colapseGrupo"
                                    data-value="<?php echo $item['pai']; ?>"><i class="icon-folder-open"/></td>
                                <td colspan="3"
                                    style="width: 20% !important;text-align: justify !important;"><?php echo $item['nomatividadecronograma']; ?></td>
                                <td style="width: 6% !important;">&nbsp;</td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datiniciobaseline']; ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datfimbaseline']; ?></td>
                                <td style="text-align: center !important; width: 3% !important;"><?php echo $item['numdiasbaseline']; ?></td>
                                <td style="text-align: right !important; width: 5% !important;"><?php echo (!empty($item['vlratividade']) && $item['vlratividade'] > 0) ? mb_substr($item['vlratividade'],
                                            0, -2) . '.' . mb_substr($item['vlratividade'], -2) : number_format(0,
                                        2); ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datinicio']; ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datfim']; ?></td>
                                <td style="width: 3% !important;">&nbsp;</td>
                                <td style="text-align: center !important; width: 3% !important;"><?php echo $item['numdiasrealizados']; ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo number_format($item['numpercentualconcluido'],
                                        0); ?></td>
                                <td style="font-size:9px;width: 15% !important;text-align: left !important;"><?php echo $item['nomparteinteressada']; ?></td>
                                <td style="text-align: center; width: 5% !important;"><span
                                            class="badge badge-<?php echo (number_format($item['numpercentualconcluido'],
                                                    0) == 100) ? "default" : $farol; ?>"
                                            title="<?php echo $atraso; ?> dias"><?php echo $atraso; ?> dias</span></td>
                                <td style="width: 5% !important;">
                                    <a class="comentarios"
                                       data-target="#dialog-comentario"
                                       data-text="<?php echo $item['idatividadecronograma']; ?>"
                                       title="<?php echo $item['cont_comentario']; ?> Comentário(s)"
                                       href="<?php echo $this->url(
                                           array(
                                               'module' => 'projeto',
                                               'controller' => 'cronograma',
                                               'action' => 'addcomentario',
                                               'idprojeto' => $this->idprojeto
                                           )); ?>">
                                        <?php if ($item['cont_comentario'] == 0): ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments.png') ?>"/>
                                        <?php else: ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments_blak.png') ?>"/>
                                        <?php endif; ?>
                                    </a>
                                </td>
                            </tr>

                            <?php
                            $countGrupo++;
                            break;
                        case 2 : ?>
                            <tr class="item-cronograma nivelPai-<?php echo $item['pai']; ?>">
                                <td>
                                    <input type="radio"
                                           name="item_cronograma"
                                           class="input-item-cronograma item-entrega"
                                           data-group=".btn-group-entrega"
                                           data-pai="<?php echo $item['pai']; ?>"
                                           data-dados='{"flashowhide": "'<?php echo $item['flashowhide']; ?>'"}'
                                    data-text='{<?php echo trim(number_format($item['numpercentualconcluido'], 0)); ?>
                                    ,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>
                                    ,<?php echo trim($item['numfolga']); ?>
                                    ,<?php echo trim($item['domtipoatividade']); ?>
                                    ,<?php echo trim($item['idgrupo']); ?>
                                    ,<?php echo trim($item['numdiasrealizados']); ?>
                                    ,<?php echo trim($item['idatividadecronograma']); ?>
                                    ,<?php echo trim($item['idparteinteressada']); ?>
                                    ,<?php echo trim($item['contPredecessoras']); ?>}'
                                    value="<?php echo $item['idatividadecronograma']; ?>" >
                                    <input type="hidden" name="domtipoatividade" id="domtipoatividade"
                                           value="<?php echo $item['domtipoatividade']; ?>">
                                </td>
                                <td style="text-align: center;cursor: pointer;width: 2px !important;">
                                    <i class='icon-edit entrega'
                                       title='Editar Entrega'
                                       data-text='{<?php echo trim(number_format($item['numpercentualconcluido'],
                                           0)); ?>,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>,<?php echo trim($item['numfolga']); ?>,<?php echo trim($item['domtipoatividade']); ?>,<?php echo trim($item['idgrupo']); ?>,<?php echo trim($item['numdiasrealizados']); ?>,<?php echo trim($item['idatividadecronograma']); ?>,<?php echo trim($item['idparteinteressada']); ?>,<?php echo trim($item['contPredecessoras']); ?>}'/>
                                </td>
                                <td style="text-align: center"><?php echo $item['numseq']; ?></td>
                                <td style="width: 2% !important;">&nbsp;</td>
                                <td class="colapseEntrega" style="width: 2% !important;"
                                    data-value="<?php echo $item['idatividadecronograma']; ?>"><i class="icon-tag"/>
                                </td>
                                <td colspan="2"
                                    style="width: 18% !important;text-align: justify !important;"><?php echo $item['nomatividadecronograma']; ?></td>
                                <td style="width: 6% !important;">&nbsp;</td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datiniciobaseline']; ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datfimbaseline']; ?></td>
                                <td style="text-align: center !important; width: 3%"><?php echo $item['numdiasbaseline']; ?></td>
                                <td style="text-align: right !important;  width: 5% !important;"><?php echo (!empty($item['vlratividade']) && $item['vlratividade'] > 0) ? mb_substr($item['vlratividade'],
                                            0, -2) . '.' . mb_substr($item['vlratividade'], -2) : number_format(0,
                                        2); ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datinicio']; ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo $item['datfim']; ?></td>
                                <td style="width: 3% !important;">&nbsp;</td>
                                <td style="text-align: center !important; width: 3% !important;"><?php echo $item['numdiasrealizados']; ?></td>
                                <td style="text-align: center !important; width: 5% !important;"><?php echo number_format($item['numpercentualconcluido'],
                                        0); ?></td>
                                <td style="font-size:9px;width: 15% !important;text-align: left !important;"><?php echo $item['nomparteinteressada']; ?></td>
                                <td style="text-align: center; width: 5% !important;"><span
                                            class="badge badge-<?php echo (number_format($item['numpercentualconcluido'],
                                                    0) == 100) ? "" : $farol; ?>"
                                            title="<?php echo $atraso; ?> dias"><?php echo $atraso; ?> dias</span>
                                </td>
                                <td style="width: 5% !important;">
                                    <a class="comentarios"
                                       data-target="#dialog-comentario"
                                       data-text="<?php echo $item['idatividadecronograma']; ?>"
                                       title="<?php echo $item['cont_comentario']; ?> Comentário(s)"
                                       href="<?php echo $this->url(
                                           array(
                                               'module' => 'projeto',
                                               'controller' => 'cronograma',
                                               'action' => 'addcomentario',
                                               'idprojeto' => $this->idprojeto
                                           )); ?>">
                                        <?php if ($item['cont_comentario'] == 0): ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments.png') ?>"/>
                                        <?php else: ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments_blak.png') ?>"/>
                                        <?php endif; ?>
                                    </a>
                                </td>
                            </tr>
                            <?php
                            $countEntrega++;
                            break;
                        case 3: ?>
                            <!--                data-dados='{"flashowhide": "{{flashowhide}}"}'-->
                            <tr class="item-cronograma <?php echo $item['descricaoconclusao']; ?> nivelPai-<?php echo $item['pai']; ?> nivelEntrega-<?php echo $item['idgrupo']; ?>">
                                <td style="width: 2px !important;">
                                    <input type="radio"
                                           name="item_cronograma"
                                           class="input-item-cronograma item-atividade"
                                           data-group=".btn-group-atividade"
                                           data-text='{<?php echo trim(number_format($item['numpercentualconcluido'],
                                               0)); ?>,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>,<?php echo trim($item['numfolga']); ?>,<?php echo trim($item['domtipoatividade']); ?>,<?php echo trim($item['idgrupo']); ?>,<?php echo trim($item['numdiasrealizados']); ?>,<?php echo trim($item['idatividadecronograma']); ?>,<?php echo trim($item['idparteinteressada']); ?>,<?php echo trim($item['contPredecessoras']); ?>}'
                                           value="<?php echo $item['idatividadecronograma']; ?>">
                                    <input type="hidden" name="domtipoatividade" id="domtipoatividade"
                                           value="<?php echo $item['domtipoatividade']; ?>">
                                </td>
                                <td style="text-align: center;cursor: pointer;width: 2px !important;">
                                    <i class='icon-edit atividadeCron'
                                       title='Editar Atividade'
                                       data-text='{<?php echo trim(number_format($item['numpercentualconcluido'],
                                           0)); ?>,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>,<?php echo trim($item['numfolga']); ?>,<?php echo trim($item['domtipoatividade']); ?>,<?php echo trim($item['idgrupo']); ?>,<?php echo trim($item['numdiasrealizados']); ?>,<?php echo trim($item['idatividadecronograma']); ?>,<?php echo trim($item['idparteinteressada']); ?>,<?php echo trim($item['contPredecessoras']); ?>}'/>
                                </td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo $item['numseq']; ?></td>
                                <td style="width: 2% !important;">&nbsp;</td>
                                <td style="width: 2% !important;">&nbsp;</td>
                                <td style="width: 2% !important;"><i class="icon-list-alt"/></td>
                                <td style="width: 16% !important;text-align: justify !important;"><?php echo $item['nomatividadecronograma']; ?></td>
                                <td style="text-align: left;width: 6% !important;">
                                    <?php if (!empty($item['predecessoras']) && $item['predecessoras'] != "{NULL}") : ?>
                                        <a class="btn btn-mini btn-link dropdown-toggle" title="Predecessoras"
                                           data-toggle="dropdown" href="#">
                                            <?php
                                            $result = null;
                                            $predecess = array();

                                            if (is_numeric(strpos($item['predecessoras'], '&&&&&'))) :
                                                $result = explode("&&&&&", $item['predecessoras']);
                                                foreach ($result as $array):
                                                    $arraynumPredecessora = explode("#-#", $array);
                                                    $predecess[] = $arraynumPredecessora[1];
                                                endforeach;
                                                echo implode(', ', $predecess);
                                            else :
                                                $predecess = explode("#-#", $item['predecessoras']);
                                                echo $predecess[1];
                                            endif;
                                            ?>
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php if (is_numeric(strpos($item['predecessoras'], '&&&&&'))) :
                                                $result = explode("&&&&&", $item['predecessoras']);
                                                foreach ($result as $array):
                                                    $arrayPredecessora = explode("#-#", $array); ?>
                                                    <li>
                                                        <a href="#"><?php echo $arrayPredecessora[1] . " - " . $arrayPredecessora[2] . " - " . $arrayPredecessora[3] . " à " . $arrayPredecessora[4]; ?></a>
                                                    </li>
                                                <?php endforeach;
                                            else :
                                                $predecessoras = explode("#-#", $item['predecessoras']); ?>
                                                <li>
                                                    <a href="#"><?php echo $predecessoras[1] . " - " . $predecessoras[2] . " - " . $predecessoras[3] . " à " . $predecessoras[4]; ?></a>
                                                </li>
                                            <?php endif; ?>
                                        </ul>
                                    <?php endif;
                                    if (isset($item['listaPredecessoras']) && (!empty($item['listaPredecessoras']))) :
                                        ?>
                                        <input type="hidden" name="listaPredec" id="listaPredec"
                                               value="<?php echo $item['listaPredecessoras'] ?>">
                                    <?php endif; ?>
                                </td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datiniciobaseline']; ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datfimbaseline']; ?></td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo $item['numdiasbaseline']; ?></td>
                                <td style="text-align: right !important;width: 5% !important;"><?php echo (!empty($item['vlratividade']) && $item['vlratividade'] > 0) ? mb_substr($item['vlratividade'],
                                            0, -2) . '.' . mb_substr($item['vlratividade'], -2) : number_format(0,
                                        2); ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datinicio']; ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datfim']; ?></td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo "(" . $item['numfolga'] . ")"; ?></td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo $item['numdiasrealizados']; ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo number_format($item['numpercentualconcluido'],
                                        0); ?></td>
                                <td style="font-size:9px;width: 15% !important;text-align: left !important;"><?php echo $item['nomparteinteressada']; ?></td>
                                <td style="text-align: center;width: 5% !important;"><span
                                            class="badge badge-<?php echo (number_format($item['numpercentualconcluido'],
                                                    0) == 100) ? "" : $farol; ?>"
                                            title="<?php echo $atraso; ?> dias"><?php echo $atraso; ?> dias</span>
                                </td>
                                <td style="width: 5% !important;">
                                    <a class="comentarios"
                                       data-target="#dialog-comentario"
                                       data-text="<?php echo $item['idatividadecronograma']; ?>"
                                       title="<?php echo $item['cont_comentario']; ?> Comentário(s)"
                                       href="<?php echo $this->url(
                                           array(
                                               'module' => 'projeto',
                                               'controller' => 'cronograma',
                                               'action' => 'addcomentario',
                                               'idprojeto' => $this->idprojeto
                                           )); ?>">
                                        <?php if ($item['cont_comentario'] == 0): ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments.png') ?>"/>
                                        <?php else: ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments_blak.png') ?>"/>
                                        <?php endif; ?>
                                    </a>
                                </td>
                            </tr>
                            <?php
                            $countAtividade++;
                            break;
                        case 4: ?>
                            <!--                data-dados='{"flashowhide": "{{flashowhide}}"}'-->
                            <tr class="item-cronograma <?php echo $item['descricaoconclusao'] ?> nivelPai-<?php echo $item['pai']; ?> nivelEntrega-<?php echo $item['idgrupo']; ?>">
                                <td style="width: 2% !important;">
                                    <input type="radio"
                                           name="item_cronograma"
                                           id="item_cronograma"
                                           class="input-item-cronograma item-marco"
                                           data-text='{<?php echo trim(number_format($item['numpercentualconcluido'],
                                               0)); ?>,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>,<?php echo trim($item['numfolga']); ?>,<?php echo trim($item['domtipoatividade']); ?>,<?php echo $item['idgrupo']; ?>,<?php echo trim($item['numdiasrealizados']); ?>,<?php echo trim($item['idatividadecronograma']); ?>,<?php echo trim($item['idparteinteressada']); ?>,<?php echo trim($item['contPredecessoras']); ?>}'
                                           data-group=".btn-group-atividade"
                                           value="<?php echo $item['idatividadecronograma']; ?>">
                                    <input type="hidden" name="domtipoatividade" id="domtipoatividade"
                                           value="<?php echo $item['domtipoatividade']; ?>">
                                </td>
                                <td style="text-align: center !important;cursor: pointer;width: 2% !important;"><i
                                            class='icon-edit atividadeCron' title='Editar Marco'
                                            data-text='{<?php echo trim(number_format($item['numpercentualconcluido'],
                                                0)); ?>,<?php echo trim($item['datinicio']); ?>,<?php echo trim($item['datfim']); ?>,<?php echo trim($item['numfolga']); ?>,<?php echo trim($item['domtipoatividade']); ?>,<?php echo trim($item['idgrupo']); ?>,<?php echo trim($item['numdiasrealizados']); ?>,<?php echo trim($item['idatividadecronograma']); ?>,<?php echo trim($item['idparteinteressada']); ?>,<?php echo trim($item['contPredecessoras']); ?>}'/>
                                </td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo $item['numseq']; ?></td>
                                <td style="width: 2% !important;">&nbsp;</td>
                                <td style="width: 2% !important;">&nbsp;</td>
                                <td style="width: 2% !important;"><i class="icon-flag"/></td>
                                <td style="width: 16% !important;text-align: justify !important;"><?php echo $item['nomatividadecronograma']; ?></td>
                                <td style="text-align: left;width: 6% !important;">
                                    <?php if (!empty($item['predecessoras']) && $item['predecessoras'] != "{NULL}") : ?>
                                        <a class="btn btn-mini btn-link dropdown-toggle" title="Predecessoras"
                                           data-toggle="dropdown" href="#">
                                            <?php
                                            $result = null;
                                            $predecess = array();

                                            if (is_numeric(strpos($item['predecessoras'], '&&&&&'))) :
                                                $result = explode("&&&&&", $item['predecessoras']);
                                                foreach ($result as $array):
                                                    $arraynumPredecessora = explode("#-#", $array);
                                                    $predecess[] = $arraynumPredecessora[1];
                                                endforeach;
                                                echo implode(', ', $predecess);
                                            else :
                                                $predecess = explode("#-#", $item['predecessoras']);
                                                echo $predecess[1];
                                            endif;
                                            ?>
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php if (is_numeric(strpos($item['predecessoras'], '&&&&&'))) :
                                                $result = explode("&&&&&", $item['predecessoras']);
                                                foreach ($result as $array):
                                                    $arrayPredecessora = explode("#-#", $array); ?>
                                                    <li>
                                                        <a href="#"><?php echo $arrayPredecessora[1] . " - " . $arrayPredecessora[2] . " - " . $arrayPredecessora[3] . " à " . $arrayPredecessora[4]; ?></a>
                                                    </li>
                                                <?php endforeach;
                                            else :
                                                $predecessoras = explode("#-#", $item['predecessoras']); ?>
                                                <li>
                                                    <a href="#"><?php echo $predecessoras[1] . " - " . $predecessoras[2] . " - " . $predecessoras[3] . " à " . $predecessoras[4]; ?></a>
                                                </li>
                                            <?php endif; ?>
                                        </ul>
                                    <?php endif;
                                    if (isset($item['listaPredecessoras']) && (!empty($item['listaPredecessoras']))) :
                                        ?>
                                        <input type="hidden" name="listaPredec" id="listaPredec"
                                               value="<?php echo $item['listaPredecessoras'] ?>">
                                    <?php endif; ?>
                                </td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datiniciobaseline']; ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datfimbaseline']; ?></td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo $item['numdiasbaseline']; ?></td>
                                <td style="text-align: right !important;width: 5% !important;"><?php echo (!empty($item['vlratividade']) && $item['vlratividade'] > 0) ? mb_substr($item['vlratividade'],
                                            0, -2) . '.' . mb_substr($item['vlratividade'], -2) : number_format(0,
                                        2); ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datinicio']; ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo $item['datfim']; ?></td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo "(" . $item['numfolga'] . ")"; ?></td>
                                <td style="text-align: center !important;width: 3% !important;"><?php echo $item['numdiasrealizados']; ?></td>
                                <td style="text-align: center !important;width: 5% !important;"><?php echo number_format($item['numpercentualconcluido'],
                                        0); ?></td>
                                <td style="font-size:9px;width: 15% !important;text-align: left !important;"><?php echo $item['nomparteinteressada']; ?></td>
                                <td style="text-align: center;width: 5% !important;"><span
                                            class="badge badge-<?php echo (number_format($item['numpercentualconcluido'],
                                                    0) == 100) ? "" : $farol; ?>"
                                            title="<?php echo $atraso; ?> dias">
                                                <?php echo $atraso; ?> dias</span>
                                    </span>
                                </td>
                                <td style="width: 5% !important;">
                                    <a class="comentarios"
                                       data-target="#dialog-comentario"
                                       data-text="<?php echo $item['idatividadecronograma']; ?>"
                                       title="<?php echo $item['cont_comentario']; ?> Comentário(s)"
                                       href="<?php echo $this->url(
                                           array(
                                               'module' => 'projeto',
                                               'controller' => 'cronograma',
                                               'action' => 'addcomentario',
                                               'idprojeto' => $this->idprojeto
                                           )); ?>">
                                        <?php if ($item['cont_comentario'] == 0): ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments.png') ?>"/>
                                        <?php else: ?>
                                            <img id="img<?php echo $item['idatividadecronograma']; ?>"
                                                 src="<?php echo $this->baseUrl('/img/comments_blak.png') ?>"/>
                                        <?php endif; ?>
                                    </a>
                                </td>
                            </tr>
                            <?php
                            $countAtividade++;
                            break;
                    endswitch;
                    ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php else : ?>
            <tr>
                <td colspan="20">Não existe cronograma cadastrado.</td>
            </tr>
        <?php endif; ?>
        <table class="table table-hover table-striped table-condensed">
            <tfoot>
            <tr>
                <td colspan="20"><?php echo $countGrupo; ?>&nbsp;Grupo(s), <?php echo $countEntrega; ?>&nbsp;Entrega(s)
                    e <?php echo $countAtividade; ?>&nbsp;Atividades.
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

    <script type="text/x-handlebars-template"></script>
    <div class="mensagens">
        <div id="dialog-AtivPredecexcluir" style="display: none">
            <div class="alert alert-block" style="font-size: 14px !important;">
                <h4 style="color:#000006 !important">ATEN&Ccedil;&Atilde;O</h4>
                <p>
                    Essa atividade é uma predecessora.<br/>
                    Por favor retire o vínculo com a outra atividade para excluí-la.
                </p>
            </div>
        </div>
        <div id="dialog-Predecessoraexcluir" style="display: none">
            <div class="alert alert-block" style="font-size: 14px !important;">
                <h4>Aviso!</h4>
                <p>Essa atividade é sucessora de outra. Tem certeza que deseja excluí-la?</P>
            </div>
        </div>
        <div id="dialog-excluir" style="display: none">
            <div class="alert alert-block" style="font-size: 14px !important;">
                <h4>Aviso!</h4>
                <p>Tem certeza que deseja excluir essa atividade?</P>
            </div>
        </div>
    </div>
    <div id="dialog-excluir-entrega" style="display: none"></div>
    <div id="dialog-excluir-grupo" style="display: none"></div>
    <div id="dialog-grupo" style="display: none"></div>
    <div id="dialog-entrega" style="display: none"></div>
    <div id="dialog-atividade" style="display: none"></div>
    <div id="dialog-marco" style="display: none"></div>
    <div id="dialog-atualizar-baseline" style="display: none"></div>
    <div id="dialog-atualizar-baseline-ativ" style="display: none"></div>
    <div id="dialog-comentario" style="display: none"></div>
    <!--    --><?php //echo $this->partial('_partials/cron-form-atividade-marco.phtml', array('form' => $this->formMarco)); ?>
    <!--    </div>-->


</div>
<div class="region-east">
    <?php $frmPesquisar = $this->formAtividadePesquisar->getAttribs(); ?>

    <div class="row">
        <div class="portlet portlet-marron span4">
            <div class="title">Pesquisar Atividade</div>
            <div class="content" style="height: 380px !important; overflow-y: scroll !important;">
                <form id="<?php echo $frmPesquisar['id']; ?>"
                      name="<?php echo $frmPesquisar['id']; ?>"
                      action="<?php //echo $frmPesquisar->formAtividadePesquisar->getAction(); ?>"
                      method="<?php echo $frmPesquisar['method']; ?>">
                    <div class="row">
                        <div class="span4" style="height: 95px !important;">
                            <div style="height: 29px !important;">
                                <legend><h6>Data de in&iacute;cio está entre:</h6></legend>
                            </div>
                            <div class="span2"
                                 style="width: 100px !important; height: 65px !important;margin-left:0px !important;">
                                <?php echo $this->formAtividadePesquisar->inicial_dti; ?>
                            </div>
                            <div class="span2"
                                 style="width: 100px !important; height: 65px !important;margin-left:5px !important;">
                                <?php echo $this->formAtividadePesquisar->inicial_dtf; ?>
                            </div>
                        </div>
                        <div class="span4" style="height: 95px !important;">
                            <div style="height: 29px !important;">
                                <legend><h6>Data de fim está entre:</h6></legend>
                            </div>
                            <div class="span2"
                                 style="width: 100px !important; height: 65px !important;margin-left:0px !important;">
                                <?php echo $this->formAtividadePesquisar->final_dti; ?>
                            </div>
                            <div class="span2"
                                 style="width: 100px !important; height: 65px !important;margin-left:5px !important;">
                                <?php echo $this->formAtividadePesquisar->final_dtf; ?>
                            </div>
                        </div>
                        <div class="span3" style="width: 100px !important; height: 65px !important;">
                            <?php echo $this->formAtividadePesquisar->domtipoatividade_pesq; ?>
                        </div>
                        <div class="span3" style="width: 100px !important; height: 65px !important;">
                            <?php echo $this->formAtividadePesquisar->status; ?>
                        </div>
                        <div class="span4 intervalo-percentual" style="display: none;">
                            <div class="span1_5 span120px">
                                <?php echo $this->formAtividadePesquisar->percentualinicio; ?>
                            </div>
                            <div class="span1_5 span120px">
                                <?php echo $this->formAtividadePesquisar->percentualfim; ?>
                            </div>
                        </div>
                        <div class="span3">
                            <?php echo $this->formAtividadePesquisar->idparteinteressada_pesq; ?>
                            <?php echo $this->formAtividadePesquisar->idprojeto_pesq; ?>
                        </div>
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formAtividadePesquisar->submit_pesq; ?>
                                <?php echo $this->formAtividadePesquisar->reset_pesq; ?>
                                <?php echo $this->formAtividadePesquisar->close_pesq; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>