<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/select2-3.4.0/select2.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/projeto/tap/informacoesiniciais.js'), 'text/javascript');


//echo $this->form;
$frmAttr = $this->form->getAttribs();
?>
<div class="region-center">
    <?php echo $this->partial('_partials/menuTap.phtml', array('dados' => 'informacoesiniciais')); ?>
    <div class="portlet portlet-marron span12">
        <h3>Informações</h3>
        <div class="content">
            <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <fieldset>
                    <legend>Iniciais</legend>
                    <div class="row">
                        <div class="span6">
                            <?php echo $this->form->nomprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idprograma; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->vlrorcamentodisponivel; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->nomcodigo; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idobjetivo; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->idnatureza; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->idsetor; ?>
                        </div>
                    </div>
                    <div class="row container-pessoa">
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nomdemandante->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->nomdemandante->renderViewHelper(); ?>
                                    <?php echo $this->form->iddemandante; ?>
                                </div>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nompatrocinador->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idpatrocinador; ?>
                                    <?php echo $this->form->nompatrocinador->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="control-group">
                                <?php echo $this->form->nomgerenteprojeto->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idgerenteprojeto; ?>
                                    <?php echo $this->form->nomgerenteprojeto->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                        <div class="span">
                            <div class="control-group">
                                <?php echo $this->form->nomgerenteadjunto->renderLabel(); ?>
                                <div class="input-prepend ">
                                    <?php echo $this->form->pessoabutton; ?>
                                    <?php echo $this->form->idgerenteadjunto; ?>
                                    <?php echo $this->form->nomgerenteadjunto->renderViewHelper(); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row grid-append" style="display: none;">
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->datinicio; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datfim; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->datinicioplano; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->datfimplano; ?>
                        </div>
                    </div>

                </fieldset>
                <fieldset>
                    <legend>Outras</legend>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->domtipoprojeto; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flacopa; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->numperiodicidadeatualizacao; ?>
                        </div>
                        <div class="span2">
                            <?php echo $this->form->numcriteriofarol; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->form->flapublicado; ?>
                        </div>
                        <div class="span3">
                            <?php echo $this->form->flaaprovado; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span5">
                            <?php echo $this->form->idprojeto; ?>
                            <?php echo $this->form->submit; ?>
                            <?php echo $this->form->reset; ?>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>