<div class="span-15 endereco">
    <!--    <h4>Endereço</h4>   -->
    <div class="complemento"><?php echo $this->endereco['est_endereco']; ?></div>
    <div class="end"><?php echo $this->endereco['bai_desc'], ', ', $this->endereco['cid_desc'], ', ', $this->endereco['uf_nm'], ', ', $this->endereco['uf_id'], ', ', $this->endereco['est_nr_cep']; ?></div>
    <div class="telefone"><strong>Tel: <?php echo $this->endereco['est_nr_fone']; ?></strong></div>
</div>
