<div class="region-center" >
    <div class="portlet portlet-cinza">
        <div class="content">
            <input type="hidden" id="idparteinteressada" name="idparteinteressada" value="<?php echo $this->parte->idparteinteressada; ?>"/>
            <div class="row">              
                <div class="portlet portlet-cinza span9">
                    <div class="title">Nome</div>
                    <div class="content"><?php echo $this->parte->nomparteinteressada; ?></div>
                </div>
            </div>          
            <div class="row">              
                <div class="portlet portlet-cinza span3">
                    <div class="title">Fun&ccedil;&atilde;o</div>
                    <div class="content"><?php echo $this->parte->nomfuncao; ?></div>
                </div>
                <div class="portlet portlet-cinza span3">
                    <div class="title">E-mail</div>
                    <div class="content"><?php echo $this->parte->desemail; ?></div>
                </div>
                <div class="portlet portlet-cinza span3">
                    <div class="title">Telefone</div>
                    <div class="content"><?php echo $this->parte->destelefone; ?></div>
                </div>
            </div>
            <div class="row">              
                <div class="portlet portlet-cinza span5">
                    <div class="title">N&iacute;vel de Influ&ecirc;ncia</div>
                    <div class="content"><?php echo $this->parte->domnivelinfluencia; ?></div>
                </div>
                <div class="portlet portlet-cinza span5">
                    <div class="title">Observação</div>
                    <div class="content"><?php echo $this->parte->observacao; ?></div>
                </div>
            </div>           
        </div>
    </div>
</div>