<script>

$(function() {

    $("#accordion").accordion();

    $.pnotify.defaults.history = false;

    $("#tabs").tabs();

    $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        language: 'pt-BR'
    });

    $('.mask-tel').mask("(99) 9999-9999");


//    $('.origem').click(function() {
//        context = $(this).data('cont');
//        $('.cont').hide().find('input,select').hide().prop('disabled', true);
//        $('.' + context).show().find('select,input:text,input:hidden').fadeIn('slow').prop('disabled', false);
//        $('.origem').removeClass('active');
//        $('.origem-' + context).addClass('active');        
//    });
//
//    $('.origem:first').trigger('click');


     $(".pessoa-button").on('click', function(event) {
        event.preventDefault();
        $(this).closest('.container-pessoa').find('.control-group').removeClass('input-selecionado');
        $(this).closest('.control-group').addClass('input-selecionado');
        if ($("table#list-grid-pessoa").length <= 0) {
            $.ajax({
                url: base_url + "/cadastro/pessoa/grid",
                type: "GET",
                dataType: "html",
                success: function(html) {
                    $(".grid-append").append(html).slideDown('fast');
                }
            });
            $('.pessoa-button')
                .off('click')
                .on('click',function() {
                    var $this = $(this);
                    $(".grid-append").slideDown('fast', function(){
                        $this.closest('.container-pessoa').find('.control-group').removeClass('input-selecionado');
                        $this.closest('.control-group').addClass('input-selecionado');
                    });
                });
        } 
    });        
});

function resetFormPart() {
    $("input, select").not('input#idprojeto').val('');
}

function selectRow(row) {
    $('.input-selecionado')
        .find('input:hidden').val(row.idpessoa).trigger('blur')
        .end()
        .find('input:text').val(row.nompessoa).trigger('blur');
}
</script>
<div class="region-center" >
    <div class="portlet portlet-marron">
        <div class="content">
            <div class="row span">
                <div class="portlet">
                    <ul class="nav nav-pills">
                        <?php if($this->form):?>
                            <li class="origem origem-interno active"  data-cont="interno"><a id="origem-interno-link" class="link" href="#">Interno</a></li>
                        <?php else: ?>
                            <li class="origem origem-externo active" data-cont="externo"><a id="origem-externo-link" class="link" href="#">Externo</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row span12">
            <?php if($this->form): 
                     $frmAttr = $this->form->getAttribs(); 
            ?>
                <div class="interno formulario cont">
                    <form id="<?php echo $frmAttr['id']; ?>"
                          name="<?php echo $frmAttr['id']; ?>"
                          method="<?php echo $frmAttr['method']; ?>">
                            <div class="row"> 
                                <input id="idprojeto" type="hidden" value="<?php echo $this->idprojeto; ?>" name="idprojeto">                                
                                <?php echo $this->form->idparteinteressada; ?>
                                <div class="span">
                                    <div class="row">
                                        <div class="portlet portlet-marron span9">
                                            <div class="title">Nome</div>
                                            <div class="content"><?php echo $this->form->nomparteinteressada->getValue(); ?></div>
                                        </div>
                                                                                                                       
                                    </div>
                                    <div class="row">
                                        <div class="span">
                                            <?php echo $this->form->nomfuncao; ?>
                                        </div>
                                        <div class="span">
                                            <?php echo $this->form->domnivelinfluencia; ?>
                                        </div>
                                        <div class="span">
                                            <?php echo $this->form->desemail; ?>
                                        </div>
                                        <br/><br/>
                                         <div class="span">
                                            <?php echo $this->form->destelefone; ?>
                                        </div>
                                        <div class="span">
                                            <?php echo $this->form->observacao; ?>
                                        </div>
                                    </div>
                                </div>
<!--                                 <div class="span9">
                                    <div class="row">
                                        <div class="span3">
                                            <div class="control-group">
                                                <label class="control-label">Nome</label>
                                                <div style="padding-top: 6px;"><?php //echo $this->form->nomparteinteressada->getValue(); ?></div>
                                            </div>                                        
                                        </div>
                                        <div class="span3">
                                            <div class="control-group">
                                                <label class="control-label">Função da Organização</label>
                                                <div style="padding-top: 6px;"><?php //echo $this->form->nomfuncao->getValue(); ?></div>
                                            </div>                                        
                                        </div>
                                        <div class="span">
                                            <?php //echo $this->form->domnivelinfluencia; ?>
                                        </div>
                                    </div>
                                </div>-->
                            </div>
                    </form>
                </div>
                <?php endif; ?>
                <?php if($this->formExterno): 
                            $frmAttrExterno = $this->formExterno->getAttribs();
                ?>
                <div class="externo formulario cont" >   		   
                    <form id="<?php echo $frmAttrExterno['id']; ?>"
                          name="<?php echo $frmAttrExterno['id']; ?>"
                          method="<?php echo $frmAttrExterno['method']; ?>">
                            <div class="row">                
                                <div class="span">
                                    <div class="row">
                                        <input id="idprojeto" type="hidden" value="<?php echo $this->idprojeto; ?>" name="idprojeto">                                        
                                        <?php echo $this->formExterno->idparteinteressadaexterno;?>
                                        <div class="portlet portlet-marron span9">
                                            <div class="title">Nome</div>
                                            <div class="content"><?php echo $this->formExterno->nomparteinteressadaexterno->getValue();?></div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="span">
                                            <?php echo $this->formExterno->nomfuncaoexterno; ?>
                                        </div>
                                        <div class="span">
                                            <?php echo $this->formExterno->domnivelinfluenciaexterno; ?>
                                        </div>
                                        <div class="span">
                                            <?php echo $this->formExterno->destelefoneexterno; ?>
                                        </div>
                                        <div class="span">
                                            <?php echo $this->formExterno->desemailexterno; ?>
                                        </div>
                                        <br /><br/>
                                        <div class="span">
                                            <?php echo $this->formExterno->observacaoexterno; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                    </form>
                </div>
                <?php endif; ?>           
        </div>
    </div>
</div>



