<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'))
    ->appendStylesheet($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/css/ui.jqgrid.css'));

$this->headScript()->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'),
    'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.form.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/i18n/grid.locale-pt-br.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/src/jquery.fmatter.js'))
    ->appendFile($this->baseUrl('/js/library/jquery.jqGrid-4.4.4/js/jquery.jqGrid.min.js'))
    ->appendFile($this->baseUrl('/js/app/projeto/rh/listar.js?' . time()), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.maskedinput.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/select2-3.4.0/select2_locale_pt-BR.js'),
        'text/javascript')//->appendFile($this->baseUrl('/js/app/projeto/rh/parteinteressada.js'), 'text/javascript')
;

$frmAttrPesquisar = $this->formPesquisar->getAttribs();
?>

<div class="region-west">
    <?php
    echo $this->partial('_partials/menu-projeto.phtml', array('ativo' => 'rh', 'idprojeto' => $this->idprojeto));
    ?>
</div>

<div class="region-center">
    <?php echo $this->action('resumo', 'gerencia', 'projeto', array('idprojeto' => $this->idprojeto)); ?>
    <input type="hidden" name="idprojeto" id="idprojeto" value="<?php echo $this->idprojeto; ?>"/>
    <div class="form-actions form-actions-mini">
        <div class="btn-group">
            <a id="btn-t" href="#" class="toggle-region btn btn-primary" data-region="east">Filtrar</a>
            <a data-target="#dialog-inserir" class="btn actionfrm inserir" title="Cadastrar"
               data-id="<?php echo $this->idprojeto ?>" href="<?php echo $this->url(array(
                'module' => 'projeto',
                'controller' => 'rh',
                'action' => 'addinterno'
            )) ?>">
                Cadastrar
            </a>
        </div>
    </div>
    <table id="list-grid-rh"></table>
    <div id="toolbar-grid-rh"></div>
    <div id="pager-grid-rh"></div>
</div>

<div class="region-east" style="overflow-y: scroll;">
    <div class="row">
        <div class="portlet portlet-marron span4">
            <form id="<?php echo $frmAttrPesquisar['id']; ?>"
                  name="<?php echo $frmAttrPesquisar['id']; ?>"
                  method="<?php echo $frmAttrPesquisar['method']; ?>">
                <div class="title">Pesquisar Parte Interessada</div>
                <div class="content">
                    <?php echo $this->formPesquisar->idprojeto; ?>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->nomparteinteressadapesquisar; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->nomfuncaopesquisar; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->destelefonepesquisar; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->desemailpesquisar; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <?php echo $this->formPesquisar->domnivelinfluenciapesquisar; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            <div class="btn-group">
                                <?php echo $this->formPesquisar->btnpesquisar ?>
                                <?php echo $this->formPesquisar->reset ?>
                                <?php echo $this->formPesquisar->close ?>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="dialog-editar" style="display: none"></div>
<div id="dialog-excluir" style="display: none"></div>
<div id="dialog-detalhar" style="display: none"></div>
<div id="dialog-inserir" style="display: none"></div>