<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'));

$frmAttr = $this->form->getAttribs();
?>
<div class="content">
    <form id="<?php echo $frmAttr['id']; ?>"
          name="<?php echo $frmAttr['id']; ?>"
          action="<?php echo $this->form->getAction(); ?>"
          method="<?php echo $frmAttr['method']; ?>">
        <div class="row">
            <div class="span3">
                <?php echo $this->form->idprocessopai; ?>
            </div>
            <div class="span2">
                <?php echo $this->form->nomprocesso; ?>
            </div>
        </div>
        <div class="row container-pessoa">
            <div class="span3">
                <div class="control-group">
                    <?php echo $this->form->nomdono->renderLabel(); ?>
                    <div class="input-prepend ">
                        <?php echo $this->form->pessoabutton; ?>
                        <?php echo $this->form->nomdono->renderViewHelper(); ?>
                        <?php echo $this->form->iddono; ?>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <?php echo $this->form->nomgestor->renderLabel(); ?>
                    <div class="input-prepend ">
                        <?php echo $this->form->pessoabutton; ?>
                        <?php echo $this->form->idgestor; ?>
                        <?php echo $this->form->nomgestor->renderViewHelper(); ?>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <?php echo $this->form->nomexecutor->renderLabel(); ?>
                    <div class="input-prepend ">
                        <?php echo $this->form->pessoabutton; ?>
                        <?php echo $this->form->idexecutor; ?>
                        <?php echo $this->form->nomexecutor->renderViewHelper(); ?>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <?php echo $this->form->nomconsultor->renderLabel(); ?>
                    <div class="input-prepend ">
                        <?php echo $this->form->pessoabutton; ?>
                        <?php echo $this->form->idconsultor; ?>
                        <?php echo $this->form->nomconsultor->renderViewHelper(); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row grid-append" style="display: none;">
        </div>
        <div class="row">
            <div class="span3">
                <?php echo $this->form->nomcodigo; ?>
            </div>
            <div class="span3">
                <?php echo $this->form->idsetor; ?>
            </div>
            <div class="span3">
                <?php echo $this->form->numvalidade; ?>
            </div>
        </div>
        <div class="row">
            <div class="span2">
                <?php echo $this->form->desprocesso; ?>
            </div>
        </div>
        <div class="row">
            <div class="span5">
                <?php echo $this->form->idprocesso; ?>
                <?php //echo $this->form->submit; ?>
                <?php //echo $this->form->reset; ?>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-span1" style="float: right;">
                    (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento
                    obrigatório
                </div>
            </div>
        </div>
    </form>
</div>