<?php
$this->headLink()
    // ->appendStylesheet($this->baseUrl('/js/jquery.jqGrid-4.4.0/css/ui.jqgrid.css'))
    //->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.default.css'))
    //->appendStylesheet($this->baseUrl('/js/library/pnotify-1.2.0/icons/jquery.pnotify.default.icons.css'))
    ->appendStylesheet($this->baseUrl('/js/library/twitter/bootstrap-datepicker/css/datepicker.css'))
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));

$this->headScript()
    //->appendFile($this->baseUrl('/js/library/twitter/bootstrap-datepicker/js/bootstrap-datepicker.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/library/twitter/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    //->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript')
    //->appendFile($this->baseUrl('/js/library/pnotify-1.2.0/jquery.pnotify.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/app/admin/tipodoc/add.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<div class="row">
    <div class="portlet portlet-marron span12">
        <div class="title">Cadastro de Tipo de Documento</div>
        <div class="content">
            <form id="<?php echo $frmAttr['id']; ?>"
                  name="<?php echo $frmAttr['id']; ?>"
                  action="<?php echo $this->form->getAction(); ?>"
                  method="<?php echo $frmAttr['method']; ?>">
                <div class="row">
                    <div class="span5">
                        <?php echo $this->form->ds_tp_doc; ?>
                    </div>
                    <div class="span4">
                        <?php echo $this->form->st_ativo; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="span8 frm-actions">
                        <?php echo $this->form->cd_tp_doc; ?>
                        <?php echo $this->form->submit; ?>
                    </div>
                </div>
            </form>
            <div class="span2 pull-right">(<span class="campos-obrigatorios"></span>) Campos obrigatórios</div>
        </div>
    </div>
</div>
