<div class="row">
    <div class="portlet portlet-azul span8">
        <h3>Tipo de documento</h3>
        <div class="content">
            <?= $this->doc['DS_TP_DOC']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span1">
        <h3>N&uacute;mero</h3>
        <div class="content">
            <?= $this->doc['NR_DOCUMENTO']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span2">
        <h3>Data</h3>
        <div class="content">
            <?= $this->doc['DT_DOCUMENTO']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span5">
        <h3>Refer&ecirc;ncia</h3>
        <div class="content">
            <?= $this->doc['DS_REFEREN_DOC']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span4">
        <h3>Interessado</h3>
        <div class="content">
            <?= $this->doc['DS_INTERESS_DOC']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span4">
        <h3>Autor</h3>
        <div class="content">
            <?= $this->doc['DS_RUBRICA_DOC']; ?>
        </div>
    </div>
    <div class="portlet portlet-cinza span8">
        <h3>Assunto</h3>
        <div class="content">
            <?= $this->doc['DS_ASSUNTO_DOC']; ?>
        </div>
    </div>
</div>