<form id="tipodoc-excluir" name="tipodoc-excluir" action="" method="post">
    <div class="row">
        <div class="portlet portlet-azul span7">
            <h3>Descrição</h3>
            <div class="content">
                <?= $this->resultado['ds_tp_doc']; ?>
            </div>
        </div>
        <div class="portlet portlet-cinza span2">
            <h3>Ativo</h3>
            <div class="content">
                <?= ($this->resultado['st_ativo'] == 'S') ? 'Sim' : 'Não'; ?>
            </div>
        </div>
    </div>
    <div class="span4">
        <input type="hidden" name="cd_tp_doc" value="<?= $this->resultado['cd_tp_doc'] ?>"/>
    </div>
</form>