<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/inputTextMask.js', 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/js/vtypes.js', 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/js/usuario/senha.js', 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/js/Application.js', 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . '/js/usuario/form.js', 'text/javascript');
echo $this->form;
?>