<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/css/form.css'))
    ->appendStylesheet($this->baseUrl('/css/portlet.css'));

$this->headScript()
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/dist/jquery.validate.min.js'), 'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-validation-1.11.0/localization/messages_pt_BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery-ui-1.8.24.custom/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js'),
        'text/javascript')
    ->appendFile($this->baseUrl('/js/library/jquery.validate.bootstrap.js'), 'text/javascript');

$frmAttr = $this->form->getAttribs();
?>
<form id="<?php echo $frmAttr['id']; ?>"
      name="<?php echo $frmAttr['id']; ?>"
      action="<?php echo $this->form->getAction(); ?>"
      method="<?php echo $frmAttr['method']; ?>">
    <div class="row">
        <div class="span6">
            <?php echo $this->form->nomatividadecronograma; ?>
        </div>
    </div>
    <div class="row">
        <div class="span5">
            <?php echo $this->form->idprojeto; ?>
            <?php echo $this->form->idatividadecronograma; ?>
            <?php echo $this->form->domtipoatividade; ?>
            <?php echo $this->form->submit; ?>
            <?php echo $this->form->reset; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-9 col-sm-span1" style="float: right; padding-top: 10px;">
            (<?php echo "<img src=\"" . $this->baseUrl('/img/required.gif') . "\" />"; ?>)Preenchimento obrigatório
        </div>
    </div>
</form>